EIC-EA/EIC-community-D8

lib/modules/eic_groups/eic_groups.module
lib/modules/eic_groups/src/Hooks/EntityOperations.php

- Add link to create a new wiki page at the current level;
- Hide book select list from wiki page forms;
- Create a group and publish it;
- Go to /admin/content and click on the Book page that was automatically created (<Group name> - Wiki);
- From the book page you should see only 1 link to create the first wiki page: "Add a new wiki page";
- Create the first top level wiki page;
- When viewing the wiki page you should now see 2 links: " **Add a new wiki page at the current level**" and "**Add a new wiki page bellow this level**";

EICNET-760: Add button to create top level wiki page

---

lib/modules/eic_groups/src/EICGroupsHelper.php
lib/modules/eic_groups/src/EICGroupsHelperInterface.php
lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php

- Limit group operation links to nodes and remove "Wiki page".
- Update method **::getGroupOperationLinks** from EICGroupsHelper service in order to limit the results for specific entities;

EICNET-764: Limit group operation links

---

lib/themes/eic_community/.storybook/preview-head.html
lib/themes/eic_community/js/components/drupal.navigation-list.js
lib/themes/eic_community/js/compositions/drupal.editorial-article.js
lib/themes/eic_community/patterns/components/navigation-list/navigation-list.html.twig
lib/themes/eic_community/patterns/compositions/editorial-article.html.twig
lib/themes/eic_community/patterns/compositions/group/group.full--wiki.html.twig
lib/themes/eic_community/patterns/layout/base.html.twig
lib/themes/eic_community/sass/components/_navigation-list.scss
lib/themes/eic_community/sass/compositions/_base-layout.scss
lib/themes/eic_community/sass/compositions/_editorial-article.scss
lib/themes/eic_community/snippets/index.js
lib/themes/eic_community/styleguide/bundles/group.stories.js
lib/themes/eic_community/styleguide/components/navigation-list.docs.mdx
lib/themes/eic_community/styleguide/compositions/editorial-article.stories.js

This PR implements the collapse feature for the editorial-article component. The Wiki page used this component where the sidebar could be collapsed with the navigation-list component. The editorial-article component will now collapse the sidebar within the `Storybook > Group > Group Wiki Private` example. This will place the navigation list button next to the other buttons of the wiki page.

EICNET-772: Adjusts wiki navigation.

---

lib/themes/eic_community/data/fact-figures.data.js
lib/themes/eic_community/patterns/pages/homepage/homepage.public.html.twig
lib/themes/eic_community/sass/compositions/_fact-figures-wrapper.scss

This PR adjusts the homepage example within storybook that shows a compact version of the facts and figures component. 4 items are displayed within this example. The typography also some minor changes to match with the latest design.

EICNET-700: Make facts figures for homepage more compact.

---

lib/themes/eic_community/patterns/compositions/group/group.teaser.html.twig
lib/themes/eic_community/sass/components/_icon.scss
lib/themes/eic_community/sass/compositions/_teaser.scss
lib/themes/eic_community/sass/eic_community.screen.scss
lib/themes/eic_community/styleguide/bundles/group.stories.js

This PR updates the group teaser component and will show the group icon as fallback image.
Storybook has been updated and the example can be found at: `Storybook > Group > Group Overview Public`.

EICNET-766: Show fallback icon for group teaser, updates storybook example

---

lib/modules/eic_groups/eic_groups.module
lib/modules/eic_groups/src/Hooks/FormAlter.php
lib/modules/eic_groups/src/Hooks/FormOperations.php

Test:
- Features field should not be visible when creating a new group
- It should be visible when editing an existing group

EICNET-765: Hide features field from group creation form.

---

config/sync/context.context.search.yml
config/sync/facets.facet.search_content_type.yml
config/sync/facets.facet.search_regions_countries.yml
config/sync/facets.facet.search_topics.yml
config/sync/facets.facet_source.search_api__views_page__global_overviews__search.yml
config/sync/facets_summary.facets_summary.search_summary.yml
config/sync/search_api.index.global.yml
config/sync/search_api_sorts.search_api_sorts_field.views_page---global_overviews__search_aggregated_created.yml
config/sync/search_api_sorts.search_api_sorts_field.views_page---global_overviews__search_search_api_relevance.yml
config/sync/views.view.global_overviews.yml

* Add fields to Search API. Some aggregated fields to combine values from node and group fields.
* Add search page to global overviews view.
* Add facets and facet summary for global search. (facets for content type, regions & countries, topics)
* Filters for date taxonomy, themes taxonomy, language taxonomy.
* Sorts for comment count, number of views, recommendations, recently updated.
* Go to `/search`
* Check search, filters and sorts.

EICNET-658: Create the global search page

---

lib/modules/oec_group_flex/src/Plugin/GroupJoiningMethod/TuGroupMembershipRequest.php
lib/modules/oec_group_flex/src/Plugin/GroupJoiningMethod/TuOpenMethod.php

As found in the internal demo meeting the joining method should be available for all visibility types, except private. This solves it.
Test:

EICNET-750/657: Joining methods available for all visibility types (except private)

---

lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-header-block.inc
lib/themes/eic_community/includes/preprocess/content/media--document--default.inc

This PR contains changes to the group header block in order to print the membership links. It also includes improvements to in the preprocess functions.

EICNET-803: Add membership links to group header

---

config/sync/user.role.content_administrator.yml
config/sync/user.role.trusted_user.yml
lib/modules/eic_groups/eic_groups.module
lib/modules/eic_groups/src/Hooks/EntityOperations.php
lib/modules/eic_groups/src/Hooks/Preprocess.php

This PR contains changes to the book and wiki pages so that it removes extra links from the front-end which come from the book module.
List of changes:

EICNET-794: Disable access to manually create book pages in groups

---

config/sync/context.context.groups_overview.yml
lib/themes/eic_community/eic_community.info.yml
lib/themes/eic_community/includes/alter/theme_suggestions/views.inc
lib/themes/eic_community/includes/preprocess/groups/group--teaser.inc
lib/themes/eic_community/templates/facets/facets-item-list--checkbox--groups.html.twig
lib/themes/eic_community/templates/facets/facets-summary-item-list.html.twig
lib/themes/eic_community/templates/layout/page--groups.html.twig
lib/themes/eic_community/templates/region/region--sidebar.html.twig
lib/themes/eic_community/templates/views/views-view--teaser-overview.html.twig

Added content_before and content_after regions to the theme.
Moved sort by and selected topics/regions to content_before.
Made collapsing of Topics/regions work.
Show default picture if the group has no image.

EICNET-667: Match storybook html with current Drupal theme.

---

lib/modules/eic_groups/src/Hooks/EntityOperations.php

EICNET-809: Update text link of buttons to create wiki pages.

---

lib/themes/eic_community/sass/compositions/_teaser.scss

This PR should fix the issue where the teaser had incorrect padding for related groups within a group template. This bug was only visible for the overview sections with a coloured background.

EICNET-768: Fixes padding for card group teaser.

---

lib/modules/eic_groups/src/Hooks/EntityOperations.php
lib/modules/oec_group_flex/oec_group_flex.links.menu.yml
lib/modules/oec_group_flex/oec_group_flex.links.task.yml
lib/modules/oec_group_flex/oec_group_flex.module
lib/modules/oec_group_flex/oec_group_flex.routing.yml
lib/modules/oec_group_flex/src/Entity/Form/GroupForm.php
lib/modules/oec_group_flex/src/Form/GroupVisibilitySettingsForm.php
lib/modules/oec_group_flex/src/Plugin/CustomRestrictedVisibility/RestrictedEmailDomains.php
lib/modules/oec_group_flex/src/Plugin/GroupVisibility/CustomRestrictedVisibility.php
lib/modules/oec_group_flex/src/Plugin/RestrictedGroupVisibilityBase.php
lib/themes/eic_community/includes/preprocess/groups/group--teaser.inc

Fixes:
- Validation of the custom restricted visibility option. At least one needs to be selected. 
bd775c6
- Checks if the Group is published before giving access. c7b6344 3f71c71
- Retrieve the group outsider roles via a service provided by Group. 
e8295dc
- Small notice when saving a group with community member visibility. 
e0b270c
- We forgot to change the key email_domains_conf to restricted_email_domains_conf . The access is not working for this plugin right now. See: b8e603a
- Making visibility plugin work on Group Type level again.
4420c45
da4f495
14ed336
- Added Group Visibility settings on `/admin/group/visibility-settings`.

EICNET-762 : Restricted group follow-ups

---

config/sync/field.field.paragraph.contributor.field_user_ref.yml
config/sync/views.view.entity_reference_user.yml

- Create views entity reference display to be able to reference trusted users and content admins in contributors paragraph.
- Create a group
- Create a discussion and check if you can reference trusted users and content admins.

EICNET-849: Allow referencing content admins in discussion contributor

---

lib/modules/eic_groups/eic_groups.module
lib/modules/eic_groups/src/Hooks/CronOperations.php
lib/modules/eic_groups/src/Hooks/EntityOperations.php
lib/modules/eic_groups/src/Hooks/Pathauto.php
lib/modules/eic_groups/src/Plugin/QueueWorker/GroupContentUrlAliasUpdate.php

- Create a queue of groups when their urls alias has changed;
- Create queue worker to update group content url alias;
- Implement hook_cron to process queues;
Note: you can also try to create different group content entities and check if the url aliases have been updated as well.

EICNET-813: Create cron job to update group content URL aliases when group url alias is updated

---

lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
lib/themes/eic_community/includes/preprocess/content/node--discussion.inc

Fix description text in group header and discussion teaser components.

EICNET-848: html tags shown in teaser components as plain text

---

config/sync/context.context.book_page.yml
config/sync/core.extension.yml
config/sync/node.type.wiki_page.yml
lib/modules/eic_content/eic_content.services.yml
lib/modules/eic_content/modules/eic_content_book/eic_content_book.info.yml
lib/modules/eic_content/modules/eic_content_book/eic_content_book.module
lib/modules/eic_content/modules/eic_content_book/src/Hooks/EntityOperations.php
lib/modules/eic_content/modules/eic_content_book/src/Hooks/Preprocess.php
lib/modules/eic_content/modules/eic_content_book/src/Plugin/Block/EICBookNavigationBlock.php
lib/modules/eic_content/src/EICContentHelper.php
lib/modules/eic_content/src/EICContentHelperInterface.php
lib/modules/eic_groups/eic_groups.services.yml
lib/modules/eic_groups/src/EventSubscriber/BookPageRedirectSubscriber.php

* Add book navigation in sidebar for books that do not belong to a group
* Add links to add book page on current level or child page
* Fix circular redirect issue for book pages outside groups (BookPageRedirectSubscriber)
* Hide author and publish date information from wiki pages
* Create a new book page not linked to a group - /node/add/book
* SA/SCM can see and use add book page links ("Add a new book page" on top level book page) ("Add a new page on the current level" and "Add a new page below this page" on other book pages)
* All site users can see the book navigation in the sidebar for all book pages
* Book and wiki pages that belong to a group are not affected by these changes

EICNET-829: Book page sidebar navigation and add book page links (current level / child)

---

lib/modules/oec_group_flex/oec_group_flex.module
lib/modules/oec_group_flex/src/Plugin/GroupVisibility/PublicVisibility.php

- Create class that overrides public group visibility plugin in order to allow anonymous and trusted users to view group content of a public group.

EICNET-850: Public group content should be available to trusted users and anonymous user

---

lib/modules/eic_groups/eic_groups.services.yml
lib/modules/eic_groups/src/Breadcrumb/GroupBreadcrumbBuilder.php

- Create breadcrumb builder for groups and nodes that belong to groups.

EICNET-857: Breadcrumb doesn't show the correct group title

---

config/sync/pathauto.pattern.group_content.yml
config/sync/pathauto.pattern.group_group.yml
config/sync/pathauto.pattern.library.yml
config/sync/pathauto.pattern.news.yml
config/sync/pathauto.pattern.stories.yml
config/sync/pathauto.pattern.wiki_pages.yml
lib/themes/eic_community/includes/preprocess/content/node--document.inc

- New pathauto patterns: Library, News and Stories;
- Updated pathauto patterns: Group, Wiki pages;
- Fixed error when trying to show a document teaser without a media.

EICNET-865: Add prefix of entity type to URL to make it clear what type of content the site user is viewing

---

lib/modules/oec_group_flex/src/Plugin/CustomRestrictedVisibility/RestrictedEmailDomains.php
lib/modules/oec_group_flex/src/Plugin/CustomRestrictedVisibility/RestrictedUsers.php
lib/modules/oec_group_flex/src/Plugin/CustomRestrictedVisibilityBase.php

- Create form validation to validate when a custom restriction with (email domains or specific trusted users) are empty.

EICNET-866: Validation on custom restrictions when creating a restricted group

---

lib/modules/eic_flags/src/FlaggedEntitiesListBuilder.php
lib/modules/eic_flags/src/Form/RequestCloseForm.php
lib/modules/eic_flags/src/Service/AbstractRequestHandler.php
lib/modules/eic_flags/src/Service/DeleteRequestHandler.php
lib/modules/eic_flags/src/Service/HandlerInterface.php
lib/modules/eic_messages/eic_messages.module

Error on approuval of a comment delete request
Count of open requests
Hook being not triggerred when request is created

Fixes some issues when deleting comments

---

lib/themes/eic_community/includes/preprocess/blocks/block--latest-news-stories.inc
lib/themes/eic_community/templates/content/node--story--teaser.html.twig

- Strip tags from field_introduction when viewing News/Story teasers.

EICNET-848: <p> tag is shown in teaser components (News/Story teaser)

---

config/sync/core.extension.yml
config/sync/rest.resource.eic_webservices_user.yml
config/sync/rest.resource.eic_webservices_user_update.yml

- Disabled basic authentication module since it's not being used at the moment and it brings some issues in staging;

EICNET-990: Disable basic authentication module

---

composer.lock

`drupal/group_permissions` could not be updated from `1.0.0-alpha4` to `1.0.0-alpha5` because `group_flex` requires `1.0.0-alpha4` (https://git.drupalcode.org/project/group_flex/-/blob/1.x/composer.json)
```
Package operations: 2 installs, 62 updates, 0 removals
Gathering patches from patch file.
Gathering patches for dependencies. This might take a minute.
- Updating composer/installers (v1.10.0 => v1.11.0): Loading from cache
- Updating cweagans/composer-patches (1.7.0 => 1.7.1): Loading from cache
- Updating drupal/core-composer-scaffold (9.1.6 => 9.2.0): Loading from cache
- Updating commerceguys/addressing (v1.2.0 => v1.2.1): Loading from cache
- Updating composer/ca-bundle (1.2.9 => 1.2.10): Loading from cache
- Installing psr/cache (3.0.0): Loading from cache
- Updating …
```

EICNET-969: Update dependencies.

---

lib/modules/eic_content/modules/eic_content_book/src/Plugin/Block/EICBookNavigationBlock.php
lib/modules/eic_groups/src/Plugin/Block/GroupWikiBookNavigationBlock.php

- Re-adapt block plugin classes eic_groups_wiki_book_navigation and eic_content_book_navigation due to changes on the BookNavigationBlock base class.

EICNET-1036: Re-adapt group wiki navigation block plugin to meet drupal API changes

---

lib/themes/eic_community/sass/components/_author.scss

The author picture is now visible again, the css bug affected the display everywhere.
It was noticed on the discussion detail page contributor grid. But I also saw it in the discussion teaser on the group page and in the comments on the discussion detail page.

EICNET-983: Problem with author picture fixed

---

lib/modules/eic_private_content/eic_private_content.module

- Adapt text of News/Stories private checkbox field.
- **Label**: Only visible to community members
- **Help text**: When checked, only community members are able to see this article and interact with it.

EICNET-1025: News/story: Adapt the wording of the private checkbox

---

config/sync/group.role.group-admin.yml
config/sync/group.role.group-owner.yml

- Allow group admins and group owners to view book pages.

EICNET-965: Update permissions to view book pages for admins and owners

---

lib/modules/eic_content/eic_content.services.yml
lib/modules/eic_content/src/ContentBreadcrumbBuilder.php
lib/modules/eic_groups/src/Breadcrumb/GroupBreadcrumbBuilder.php
lib/themes/eic_community/includes/preprocess/navigation/breadcrumb.inc

- Minor improvements in the GroupBreadcrumbBuilder class.
- Fix breadcrumb for group contents: discussion, document, gallery.
- Fix breadcrumb for group discussion nodes.
- Fix breadcrumb for group about page;
- Create breadcrumb builder to handle breadcrumb links for nodes that dont belong to a group. Currently only needs to handle "News" and "Stories";
Check if breadcrumb is ok for all the following cases:
- Story detail page
- News detail page
- Content page
- Help and guidance (book pages)
- **All global overviews**:
> - Group overview
> - News and story overview - The overview page has not been yet developed.
> - Member overview
- **Groups**:
> - landingpage
> - Discussion detail
> - Wiki detail page
Group document and gallery:
- The library overview page is not yet developed and …

EICNET-943: As a site user I can see the breadcrumbs when navigating through the platform

---

lib/modules/eic_groups/eic_groups.module

- Implement hook_entity_field_access() to restrict access on group fields (**field_related_groups** and **field_related_news_stories**) when group moderation state is pending.

EICNET-928: As a GO I want to edit my group after creating it (when it's not reviewed by a SA/SCM yet)

---

lib/modules/eic_groups/eic_groups.module
lib/modules/eic_groups/eic_groups.services.yml
lib/modules/eic_groups/src/EICGroupsHelper.php
lib/modules/eic_groups/src/EICGroupsHelperInterface.php
lib/modules/eic_groups/src/Hooks/EntityOperations.php

- New group permission helper methods added to eic_groups.helper service;
- Add/remove **group delete** permission from group owner when moderation state is **pending**.

EICNET-942: As a GO I can delete my group when it's in pending state

---

lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php

- Add group "delete" operation to the group header block.

EICNET-942: Add group "delete" operation to the group header block.

---

composer.lock
composer.patches.json
config/sync/field.field.profile.member.field_social_links.yml
config/sync/field.storage.profile.field_social_links.yml

- Apply patch to fix with limited values being randomised (see https://www.drupal.org/project/social_link_field/issues/3155628).
- Limit field to only 3 social network links (LinkedIn, Twitter and Facebook).

EICNET-954: User profile - add validation to social channel links (Part 2)

---

lib/modules/eic_groups/src/Hooks/FormOperations.php

- Try to access group creation form and check if there is not PHP error.

Remove book.manager service from Drupal\eic_groups\Hooks\FormOperations::create() method.

---

lib/modules/eic_groups/src/Hooks/EntityOperations.php
lib/modules/oec_group_comments/oec_group_comments.services.yml
lib/modules/oec_group_comments/src/Controller/GroupCommentController.php
lib/modules/oec_group_comments/src/EventSubscriber/GroupCommentsRouteSubscriber.php
lib/themes/eic_community/includes/preprocess/comments/comment.inc

- Improve code to update group permissions in` \Drupal\eic_groups\Hook\EntityOperations` class.
- Deny access to reply to comments when user does not have permission to post comments in groups.
Hide Reply button when the user doesn't have access to reply. @xwero we need to add a condition in pattern `comment-base.html.twig` to check if the reply_path exists (**line 177**):
```twig
{% if reply_path %}
<div class="ecl-comment__action">
{% include "@ecl-twig/ec-component-link/ecl-link.html.twig" with {
link: {
label: reply_label|default('Reply'),
path: reply_path,
},
extra_classes: 'ecl-comment__reply ecl-link--button ecl-link--button-ghost',
extra_attributes: action_attributes,
} %}
</div>
{% endif %}
```

EICNET-1062: As a TU I can reply to a comment on discussion in a public group without being a GM

---

drush/drush.yml

Will allow anyone to create a drush.local.yml to set the base uri for drush and any other needed configuration
Example:
```
options:
uri: 'http://localhost:8080'
```

[EICNET-831] feat: Introduce drush.yml and load drush.local.yml with it

---

lib/modules/eic_user/eic_user.module
lib/modules/eic_user/src/Hooks/FieldWidgetOperations.php

- Add custom validation on social links from user profile in order to remove the social network base url when users fill in the social links field.
- Currently it fixes the usernames when the user inserts the full url (including https://). If the full url is not presented a form error will be thrown.

EICNET-1070: Improve - validation of URLs of social channels on the user profile

---

config/sync/views.view.group_related_news_stories.yml

- Show correct label when selecting private related Stories/News in groups.

EICNET-1060: Show correct label when choosing a story/news article in the related news section of a group

---

config/sync/context.context.group_group_homepage.yml
lib/modules/eic_groups/eic_groups.module
lib/modules/eic_groups/src/EICGroupsHelper.php
lib/modules/eic_groups/src/Plugin/Block/EICGroupOverviewMessageBlock.php
lib/modules/eic_groups/templates/eic-group-moderated-message-box.html.twig
lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-moderated-message-box.inc
lib/themes/eic_community/templates/blocks/eic-group-moderated-message-box.html.twig

Displays messages to the GO on the group homepage when the status is draft or pending. For draft groups, content actions are also added

Feature/EICNET-926: Display a message + actions for pending & draft groups

---

config/sync/core.extension.yml
lib/modules/eic_content/modules/eic_content_wiki_page/eic_content_wiki_page.info.yml
lib/modules/eic_content/modules/eic_content_wiki_page/eic_content_wiki_page.module
lib/modules/eic_content/modules/eic_content_wiki_page/eic_content_wiki_page.services.yml
lib/modules/eic_content/modules/eic_content_wiki_page/src/WikiPageBookManager.php
lib/modules/eic_groups/eic_groups.info.yml
lib/modules/eic_groups/src/Hooks/EntityOperations.php
lib/modules/eic_groups/src/Hooks/FormOperations.php

- Create custom module "eic_content_wiki_page" that provides extra logic for Content Type Wiki page;
- Override book manager service in order to change the maximum depth of the wiki page book tree;
- Add "eic_content_wiki_page" module dependency in eic_groups module;
- Fix issue where child wiki pages were not being set as parent when we create a wiki page bellow the current level.
- Hide link **"Add a new wiki page below this page"** when we reached the maximum wiki page depth.

EICNET-1102: Limit the max depth of the wiki pages to 3 levels

---

lib/themes/eic_community/patterns/compositions/comment/comment-base.html.twig

Test:
* Login with admin
* Create group
* Publish the group
* Create topic and region taxonomy term
* Go to the group
* Create a discussion with a comment
* **You should see a reply link on the comment**
* Create a user with the role; trusted user
* Switch to the user
* Go to the group discussion
* **You should see no reply link on the comment**

EICNET-1106: Hide comment reply button when link is not present.

---

lib/modules/eic_groups/eic_groups.module
lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php

- Fix PHP error when showing group header flags for anonymous users.
- Flagging access check that was preventing users from viewing group flags when group is published.

Bugfix/EICNET-1055: Fix group header flags

---

lib/modules/eic_groups/eic_groups.module
lib/modules/eic_groups/src/Plugin/Block/EICGroupOverviewMessageBlock.php

[EICNET-1137] fix: add a cache tag for group content

---

config/sync/context.context.group_discussion_detail.yml
lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php

Tests:
- Create published public group
- Create discussion
- Go as anonymous user to discussion
- *You should see that the destination in the login link is the current page*
Extra bugfix:
I saw the group header was displayed twice, so I updated the context.

EICNET-981: Based login redirect on current url instead of group url.

---

lib/modules/eic_groups/eic_groups.module

- Return access allowed by default when checking falagging access since neutral access result will always deny the access.

EICNET-1129: Missing some flags in the group header

---

config/sync/group.role.group-a416e6833.yml
config/sync/user.role.administrator.yml

- Rename drupal admin role to "Drupal admin".

EICNET-1134: Rename the admin role to "Drupal admin"

---

composer.json
composer.lock
config/sync/core.extension.yml
config/sync/entity_usage.settings.yml
config/sync/search_api.index.global.yml
lib/modules/eic_groups/eic_groups.info.yml
lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.info.yml
lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.install
lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.module
lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.services.yml
lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatistic.php
lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticTypes.php
lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatistics.php
lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsHelper.php
lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsHelperInterface.php
lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsSearchApiReindex.php
lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsStorage.php
lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsStorageInterface.php
lib/modules/eic_statistics/modules/eic_group_statistics/src/Hooks/EntityOperations.php
lib/modules/eic_statistics/modules/eic_group_statistics/src/Plugin/search_api/processor/GroupStatisticsIndexer.php
lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-header-block.inc

- Instal module entity_usage;
- Create module eic_group_statistics;
- Create new custom schema for saving group statistics;
- Implement statistics counter for group members, comments and files (discussion, document, wiki page and gallery files);
- Delete group statistics when group is deleted;
- Update group statistics when installing the module.
- Index group statistics in SOLR.
- Create a cron job to update all group statistics everyday.

EICNET-1113: Implement the missing statistics to the group header

---

config/sync/core.entity_form_display.node.story.default.yml

[EICNET-1150] Backend - Empty Contributor paragraph added by default

---

config/sync/core.entity_form_display.group.group.default.yml

Enable the URL alias field for groups in the form display to use the already existing config

[EICNET-962] chore: As a GO I want to choose a URL alias for my group

---

lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
lib/modules/eic_search/src/Search/Sources/GroupSourceType.php
lib/modules/eic_search/src/Search/Sources/SourceTypeInterface.php
lib/themes/eic_community/react/components/Block/Overview/index.js

Integrate a new configuration to handle the group context via the current route
How to test it :

[EICNET-580]feature: As a group member I want to view the group member overview

---

config/sync/search_api.index.global.yml
lib/modules/eic_search/eic_search.module
lib/modules/eic_search/src/Controller/SolrSearchController.php
lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
lib/modules/eic_search/templates/search-overview-block.html.twig
lib/themes/eic_community/react/components/Block/Overview/Search/Field/CheckboxSpecialField.js
lib/themes/eic_community/react/components/Block/Overview/Search/Sidebar.js
lib/themes/eic_community/react/components/Block/Overview/Search/TopOptions/ActiveFacet.js
lib/themes/eic_community/react/components/Block/Overview/entrypoint.js
lib/themes/eic_community/react/components/Block/Overview/index.js

New fields in block configuration to be able to filter on SOLR via search API + integrate it into react
how to test it:

[EICNET-984]feature: Add into search the possibility to filter by interests and group/contents

---

lib/modules/eic_groups/eic_groups.module
lib/modules/eic_groups/eic_groups.services.yml
lib/modules/eic_groups/src/Access/GroupContentCreateEntityAccessCheck.php

- Deny access to create book pages inside groups for all users including admins and user 1.
- Show "Add book page" link if for some reason the Drupal admin removed the book page manually.

EICNET-963: Remove "add book page" from options to post content inside a group

---

lib/modules/eic_user/src/Hooks/FieldWidgetOperations.php

Remove helper text from LinkedIn field and prepend string "in/" if missing from the values.

EICNET-1130: Remove the helptext shown on the LinkedIn field on a member profile

---

lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsHelper.php

- Group statistics: adapt field condition "group_id" in method loadGroupStatisticsFromSearchIndex according to the new machine name of the indexed field ("group_id_integer").

Bugfix: Load group statistics from SOLR

---

lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php

- Group header - load group statistics from Database instead of SOLR (SOLR updates index asynchronously and this causes group header to show old values).

EICNET-1165: Group statistics doesn't update for logged in users

---

lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GlobalResultItem.js

[EICNET-787]fix: Remove the word "page" after content type

---

lib/themes/eic_community/includes/preprocess/paragraphs/paragraph--contributor.inc

Currently the contributor paragraphs is optional, if you don't add one everything is ok. But the user can add one whitout filling the fields. This PR prevents an error when this happens

[EICNET-1164] fix: Prevent error for optional contributor fields

---

lib/themes/eic_community/includes/preprocess/content/node--news--story.inc

- Strip html tags from document title in CType Story.

EICNET-975: Fix Story document title

---

config/sync/user.role.content_administrator.yml
config/sync/user.role.site_admin.yml
config/sync/user.role.trusted_user.yml
config/sync/workflows.workflow.groups.yml

- Created new workflow transition to allow GO/SA/SCM users to be able to keep the group in draft state.

EICNET-1192: Group in Draft state can not be saved as Draft state

---

config/sync/flag.flag.recommend.yml
lib/modules/eic_content/eic_content.services.yml
lib/modules/eic_content/src/ContentBreadcrumbBuilder.php

- Remove recommend flag from CTypes News and Story;
- Fix Notice: Undefined property: Drupal\eic_content\ContentBreadcrumbBuilder::$account in Drupal\eic_content\ContentBreadcrumbBuilder when viewing a News or Story page.

EICNET-1185: Delete the recommend flag on stories

---

config/sync/core.entity_form_display.node.document.default.yml
config/sync/core.entity_form_display.node.gallery.default.yml
config/sync/field.field.node.document.field_vocab_topics.yml
config/sync/field.field.node.gallery.field_vocab_topics.yml

- EICNET-1211: Make topics field required for CTypes Document and Gallery;
- EICNET-1212: Replace select list with autocomplete widget for Topics field in CType Document.

EICNET-1211/EICNET-1212: Make topic field required for CT Document and CT Gallery

---

lib/modules/eic_groups/eic_groups.module
lib/modules/eic_groups/src/Plugin/GroupContentEnabler/GroupInvitation.php

- Allow GO/GA to invite users when group is in DRAFT state;
- Allow GA to access own group when is in DRAFT state.

EICNET-1129: Missing invite flag in group header

---

lib/modules/eic_messages/src/Hooks/FormOperations.php

- Use `DependencySerializationTrait `in `Drupal\eic_messages\Hooks\FormOperation` class since we are adding a submit handler from a class using dependency injection.

EICNET-1166: Fix ajax callback issues in forms

---

lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsStorage.php

- GroupStatisticsStorage::setMultipleGroupStatistics() method was throwing an issue trying to merge multiple rows at once so we internally call the "setGroupStatistics" for each group (queries are executed per group).
Before testing make sure you do the following:
Test phase:

EICNET-1165: Fix Group statistics update on install

---

config/sync/eic_groups.group_features.eic_groups_discussions.yml
config/sync/eic_groups.group_features.eic_groups_members.yml
config/sync/eic_groups.group_features.eic_groups_wiki.yml
lib/modules/eic_groups/config/install/eic_groups.group_features.eic_groups_discussions.yml
lib/modules/eic_groups/config/install/eic_groups.group_features.eic_groups_members.yml
lib/modules/eic_groups/config/install/eic_groups.group_features.eic_groups_wiki.yml
lib/modules/eic_groups/config/schema/eic_groups.group_features.schema.yml
lib/modules/eic_groups/src/Plugin/GroupFeature/EicGroupsGroupFeaturePluginBase.php

- Improve handlePermissions() method from EicGroupsGroupFeaturePluginBase class so that it also adds and removes group feature permissions for public roles (anonymous and outsiders);
- Update group features schema in order to be able to define the group feature permissions for the public roles.

EICNET-1193: Discussions tab of public group not shown for anonymous user/TU

---

lib/themes/eic_community/includes/preprocess/content/node--news--story.inc

[EICNET-1173] chore: Do not display social_share block on private news & stories

---

config/sync/core.entity_form_display.node.discussion.default.yml
config/sync/core.entity_form_display.node.document.default.yml
config/sync/core.entity_form_display.node.gallery.default.yml
config/sync/core.entity_form_display.node.news.default.yml
config/sync/core.entity_form_display.node.story.default.yml
config/sync/core.entity_form_display.node.video.default.yml
lib/modules/eic_content/src/Plugin/Field/FieldWidget/EntityTreeWidget.php
lib/themes/eic_community/react/components/Field/EntityTree/entrypoint.js
lib/themes/eic_community/react/components/Field/EntityTree/index.js

How to test : 
PS: be sure that you organize correctly terms of topics taxonomy for eg : 
- Thematic
- Thematic A
- Thematic B
- Horizontal
- Horizontal A
Horizontal and Thematic shouldn't be selectable

[EICNET-1163]feature: Add "disable top level selection" so moderator will not be able to select top options

---

lib/modules/eic_groups/eic_groups.module
lib/modules/eic_groups/src/Hooks/FormOperations.php

[EICNET-1172]fix: Remove the "group owner" option in the group invite form

---

lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php

How to test it :
**case 1: a member cannot leave group if it still on pending or draft**
**case 2: group owner cannot leave group**

[EICNET-1182]fix: Remove the "leave group" link if group in draft/pending or if the user is the group owner

---

config/sync/core.entity_view_display.group.group.default.yml
lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php

- Truncate group description to 350 chars in group header;

EICNET-955: Truncate group description to 350 chars in group header.

---

config/sync/eic_groups.group_features.eic_groups_latest_activity_stream.yml
config/sync/group.role.group-a416e6833.yml
config/sync/group.role.group-bf4b46c3a.yml
config/sync/group.role.group-eca6128ca.yml
lib/modules/eic_groups/config/install/eic_groups.group_features.eic_groups_latest_activity_stream.yml
lib/modules/eic_groups/eic_groups.group.permissions.yml
lib/modules/eic_groups/eic_groups.routing.yml
lib/modules/eic_groups/src/Plugin/GroupFeature/GroupLatestActivityStream.php

- Create group permissions: "access latest activity stream";
- Create group feature plugin to show/hide group menu link for the latest activity stream page (this should take into account permission "access latest activity stream");

EICNET-1079: Create a group feature for "Latest activity"

---

config/sync/core.entity_form_display.message.stream_comment_insert_update.default.yml
config/sync/core.entity_form_display.message.stream_discussion_insert_update.default.yml
config/sync/core.entity_form_display.message.stream_document_insert_update.default.yml
config/sync/core.entity_view_display.message.stream_comment_insert_update.default.yml
config/sync/core.entity_view_display.message.stream_discussion_insert_update.default.yml
config/sync/core.entity_view_display.message.stream_document_insert_update.default.yml
config/sync/core.entity_view_display.message.stream_wiki_page_insert_update.default.yml
config/sync/field.field.message.stream_comment_insert_update.field_entity_type.yml
config/sync/field.field.message.stream_comment_insert_update.field_group_ref.yml
config/sync/field.field.message.stream_comment_insert_update.field_operation_type.yml
config/sync/field.field.message.stream_comment_insert_update.field_referenced_comment.yml
config/sync/field.field.message.stream_comment_insert_update.field_referenced_node.yml
config/sync/field.field.message.stream_discussion_insert_update.field_entity_type.yml
config/sync/field.field.message.stream_document_insert_update.field_entity_type.yml
config/sync/field.field.message.stream_wiki_page_insert_update.field_entity_type.yml
config/sync/field.storage.message.field_entity_type.yml
config/sync/field.storage.message.field_referenced_comment.yml
config/sync/search_api.index.global.yml
lib/modules/eic_messages/eic_messages.module
lib/modules/eic_messages/eic_messages.services.yml
lib/modules/eic_messages/src/Service/CommentMessageCreator.php
lib/modules/eic_messages/src/Service/GroupContentMessageCreator.php

[EICNET-1084] feat: Send activity messages in solr for comments

---

lib/themes/eic_community/includes/preprocess/content/node--discussion.inc

- Show discussion teaser as HTML instead of plain text.

EICNET-1216: Discussion teaser shows HTML code

---

lib/modules/eic_content/src/ContentBreadcrumbBuilder.php

- Replace breadcrumb link "Story" with "Stories".

EICNET-1156: Breadcrumb - Story should be Stories

---

lib/modules/eic_search/src/Service/SolrDocumentProcessor.php

[EICNET-783]fix: Use correctly the group directly instead of loading wrong group content

---

lib/modules/eic_content/src/Plugin/Field/FieldWidget/EntityTreeWidget.php

This PR impact the entity tree field widget
How to test:

[EICNET-1253]fix: Set 5000 as length cause custom widget have labels in value

---

lib/modules/eic_overviews/src/GlobalOverviewPages.php

EICNET-1337: Fix the global overview page IDs.

---

config/sync/core.entity_form_display.media.eic_document.default.yml
config/sync/core.entity_view_display.media.eic_document.default.yml
config/sync/core.entity_view_display.media.eic_document.download.yml
config/sync/core.entity_view_display.media.eic_document.media_library.yml
config/sync/core.entity_view_display.media.eic_document.oe_theme_main_content.yml
config/sync/field.field.media.eic_document.field_language.yml
config/sync/field.storage.media.field_language.yml
lib/themes/eic_community/includes/preprocess/content/node--document.inc

- Add new taxonomy term field "Language" in Media Type "Document";
- Show the media document field language when viewing the teaser version.

EICNET-477: Add document language field to document media type

---

lib/themes/eic_community/includes/preprocess/content/node--document.inc

- Fix error Class 'File' not found in eic_community_preprocess_node__document().

Fix node document preprocess

---

lib/modules/eic_search/src/Plugin/search_api/processor/GroupAccessContent.php

- Allow Administrators to see all groups in the overview page;

EICNET-1352: Group overview - Admins don't see all groups

---

lib/themes/eic_community/includes/preprocess/content/node--document.inc

- Fix PHP error: `InvalidArgumentException: Field field_language is unknown. in Drupal\Core\Entity\ContentEntityBase->getTranslatedField()`

EICNET-XXXX: Fix issue when field_language doesn't exist.

---

lib/modules/eic_search/src/Controller/SolrSearchController.php

[EICNET-1276]fix: Do not multiply rows by current page

---

lib/modules/eic_groups/src/Hooks/EntityOperations.php
lib/modules/eic_groups/src/Plugin/GroupFeature/GroupFiles.php
lib/modules/eic_groups/src/Plugin/GroupFeature/GroupLatestActivityStream.php
lib/modules/eic_groups/src/Plugin/GroupFeature/GroupMembers.php
lib/modules/eic_groups/src/Plugin/GroupFeature/GroupWiki.php

- Update weights of group menu links.

EICNET-1332: Define weight of every menu item in the group menu

---

lib/modules/oec_group_flex/src/OECGroupFlexGroupSaverDecorator.php

- Use method `loadByGroup()` from GroupPermissionsManager class to load group permissions when saving the group form. Before it was using the method `getGroupPermission()` but this method was returning an old object.

EICNET-1359: Error when changing visibility of the group

---

lib/modules/eic_groups/src/Hooks/EntityOperations.php
lib/themes/eic_community/templates/content/node--book--full.html.twig

- Show link to add new wiki pages only if the user has access to create a wiki page in the group.

EICNET-1237: Wiki - Link Add wiki page is shown on moderated group

---

lib/modules/eic_search/src/Controller/SolrSearchController.php
lib/modules/eic_search/src/Service/SolrDocumentProcessor.php

[EICNET-1356]fix: Avoid adding array into array when value currently exists for a document

---

lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php

- Add read more link to the group header description when the number of chars exceed 350.

EICNET-1365: Group description > leads to about page

---

lib/modules/eic_groups/src/Plugin/Block/LastGroupActivitiesBlock.php
lib/modules/eic_search/src/Controller/SolrSearchController.php

[EICNET-1251]fix: Get correct user id from group content membership

---

config/sync/core.entity_form_display.node.video.default.yml
config/sync/core.entity_view_display.node.video.default.yml
config/sync/field.field.node.video.field_comments.yml
config/sync/field.field.node.video.field_related_contributors.yml
lib/modules/eic_content/eic_content.module
lib/modules/eic_content/modules/eic_content_discussion/eic_content_discussion.module
lib/modules/eic_content/src/Hooks/EntityOperationsContributor.php

- Create contributors field in CType Video and apply contributors logic from discussions;
- Move logic from eic_content_discussion to eic_content.

EICNET-1369: Adapt comment section on video detail page (group library)

---

lib/modules/eic_block_types/eic_block_types.module
lib/modules/eic_block_types/src/Hooks/EntityOperations.php
lib/modules/eic_statistics/src/NodeStatisticsDatabaseStorage.php
lib/themes/eic_community/includes/preprocess/blocks/block--latest-news-stories.inc

- Add News and Story statistics to the latest news and stories block in the homepage.

EICNET-1354: Generate the statistics for the stories / news in the backend

---

lib/modules/eic_groups/eic_groups.routing.yml
lib/modules/eic_groups/src/Breadcrumb/GroupBreadcrumbBuilder.php
lib/modules/eic_overviews/eic_overviews.routing.yml
lib/modules/eic_overviews/src/GroupOverviewPages.php

- Move group overview route definitions to eic_overviews module;
- Add group library overview constants;
- Fix group breadcrumb builder when viewing CTypes Document, Gallery and Video.

EICNET-1402: Show correct breadcrumb when viewing CTypes Gallery and Document

---

lib/modules/eic_media/eic_media.module
lib/themes/eic_community/includes/preprocess/content/node--news--story.inc
lib/themes/eic_community/templates/content/node--story--full.html.twig

- Show video download button when viewing detail page of a News/Story.
- Implement hook eic_media_media_access() in order to validate access to media files via "system.files" route. There was an issue where users could download a video file without having access to any node or group where the media is attached to.

EICNET-1267-1268: As a AU/GM, I can download videos from the content of a News/Story detailed page

---

config/sync/core.entity_form_display.node.discussion.default.yml
config/sync/core.entity_view_display.node.discussion.default.yml
config/sync/core.entity_view_display.node.discussion.teaser.yml
config/sync/field.field.node.discussion.field_video.yml
lib/themes/eic_community/includes/preprocess/content/node--discussion.inc
lib/themes/eic_community/templates/content/node--discussion--full.html.twig

- Create field_video in CT Discussion to allow users to upload videos;
- Show discussion video in the frontend (new theme variables and updated twig template).
- For now the frontend only serves as an example which means that it might suffer changes in the future.

EICNET-391: As a GO/GA, I can manage videos in the content of a Discussion detailed page

---

lib/modules/eic_statistics/modules/eic_group_statistics/drush.services.yml
lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.install
lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.services.yml
lib/modules/eic_statistics/modules/eic_group_statistics/src/Commands/GroupStatisticsCommands.php
lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsHelper.php
lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsStorage.php
lib/modules/eic_statistics/modules/eic_group_statistics/src/Hooks/EntityOperations.php

- Create drush command to update all group statistics;
- Updated eic_group_statistics schema so that it now supports negative values for each statistic;
- Re-factor logic to count files statistics for a given group;
- Improve logic to count group file statistics when user creates/updates/deletes a node and make the group statistics work with Content Type Gallery.
NOTES: don't remove nodes using bulk operations otherwise the group statistics will be wrong. For now we have to remove nodes 1 by 1.

EICNET-1371: Fix group file statistics for group content Gallery

---

lib/themes/eic_community/includes/preprocess/content/node--news--story.inc
lib/themes/eic_community/includes/preprocess/content/node--video.inc

- Show contributors in CT Video.
FE fixes will be done in a follow-up ticket -> https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-1433

EICNET-1369: Adapt comment section on video detail page (group library) Part 2

---

config/sync/context.context.local_tasks.yml

- Create new global context to display local tasks when viewing node pages.

EICNET-1395: Add local tasks on all contents

---

lib/themes/eic_community/includes/preprocess/field/field--media--eic-document.inc

- Improvements in hook eic_community_preprocess_field__field_related_downloads() so that it includes video files in the list of related downloads.

EICNET-392: As a GO/GA, I can manage videos in the content of a Wiki detailed page

---

lib/modules/eic_groups/eic_groups.module
lib/modules/eic_groups/src/Plugin/Validation/Constraint/GroupMembershipConstraint.php
lib/modules/eic_groups/src/Plugin/Validation/Constraint/GroupMembershipConstraintValidator.php

- Create entity constraint to validate if a group already has a owner before saving a membership.

EICNET-1172: A group can only have one GO

---

config/sync/core.entity_form_display.node.gallery.default.yml
config/sync/field.field.node.gallery.field_body.yml
config/sync/field.field.node.gallery.field_document_type.yml

- Update form display of CT Gallery;
- Make field_body and field_document_type required in CT Gallery.
- When creating a new gallery in a group, make sure the back-end form is shown correctly:
See requirements -> https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-1188.

EICNET-1188: CT gallery back-end (rework)

---

config/sync/core.entity_form_display.node.video.default.yml
config/sync/field.field.node.video.field_document_type.yml
config/sync/field.field.node.video.field_video_media.yml
config/sync/pathauto.pattern.library.yml
lib/themes/eic_community/includes/preprocess/content/node--video.inc

- Update form display;
- Make field_document_type;
- Allow only remote videos;
- Enable CT Video in pathauto pattern "Library";
When creating a new Video in a group, make sure the back-end form is shown correctly:
See requirements -> https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-1187.

EICNET-1187: CT Video back-end (rework)

---

lib/modules/eic_groups/src/Hooks/EntityOperations.php

- Fix cache issue when user is viewing a wiki page and then joins the group.

EICNET-1237: Wiki - Link Add wiki page is shown on moderated group (Part 2)

---

lib/modules/eic_groups/eic_groups.module
lib/modules/eic_groups/src/Access/GroupContentCreateEntityAccessCheck.php
lib/modules/eic_groups/src/Plugin/GroupContentEnabler/GroupNode.php

- Override GroupNode class in order to fix issue where group operations were empty for SA/SCM users that were not members of the group;
- Allow SA/SCM to create group content (override permission system).

EICNET-1345: SA/SCM should be able to edit all group content of any group (Part 2)

---

config/sync/core.entity_form_display.node.discussion.default.yml
config/sync/core.entity_view_display.node.discussion.default.yml
config/sync/core.entity_view_display.node.discussion.teaser.yml
config/sync/field.field.node.discussion.field_related_downloads.yml
lib/themes/eic_community/includes/preprocess/content/node--discussion.inc
lib/themes/eic_community/includes/preprocess/field/field--media--eic-document.inc
lib/themes/eic_community/templates/content/node--discussion--full.html.twig

- Remove field_video from CT Discussion, re-use field_related_downloads from wiki page in order to keep congruence.

EICNET-391: As a GO/GA, I can manage videos in the content of a Discussion detailed page (Rework)

---

lib/themes/eic_community/includes/preprocess/blocks/block--latest-news-stories.inc
lib/themes/eic_community/includes/preprocess/paragraphs/paragraph--contributor.inc
lib/themes/eic_community/includes/preprocess/users/user.inc
lib/themes/eic_community/patterns/components/author.html.twig

- Add author profile URL in user teaser if the current user has access to view profile pages.

EICNET-1355: Do not make avatar clickable for anonymous users

---

lib/modules/eic_search/src/Plugin/search_api/processor/GroupAccessContent.php

[EICNET-798]fix: site_admin should also see content with community restriction

---

lib/themes/eic_community/includes/preprocess/content/node--news--story.inc

- Hide Story contributors from detail page when paragraphs are empty.

EICNET-1164: When contributor field is left empty, the story can't be saved

---

lib/modules/eic_flags/src/Hooks/EntityOperations.php
lib/modules/eic_groups/eic_groups.module
lib/modules/eic_groups/src/Access/FlagAccessCheck.php
lib/modules/eic_groups/src/Access/UnFlagAccessCheck.php
lib/modules/eic_groups/src/EICGroupsHelper.php
lib/modules/eic_groups/src/Hooks/EntityOperations.php
lib/themes/eic_community/includes/preprocess/common.inc
lib/themes/eic_community/includes/preprocess/content/node--discussion.inc
lib/themes/eic_community/includes/preprocess/content/node--document.inc
lib/themes/eic_community/includes/preprocess/content/node--news--story.inc

- Re-factor access conditions to prevent users to flag group content of a group that is in pending/draft state;
- Show node flags in the frontend based on flag access;
- Invalidate group content node cache tags when group status has changed.
- We disable/enable all flags (not just the follow flag) of the node depending on the group status.

EICNET-1412 Follow flag based on group status

---

lib/modules/oec_group_features/src/GroupFeaturePluginBase.php

- Fix error that was happening after disabling a group feature (`Drupal\Core\Entity\EntityStorageException: Field enable is unknown`).

Bugfix: error disabling a group feature

---

lib/modules/eic_flags/eic_flags.info.yml
lib/modules/eic_search/eic_search.info.yml

- Add missing dependency (flag:flag) in eic_search module;
- Add missing dependency (eic_search:eic_search) in eic_flags module.

Bugfix: Add missing dependencies in eic_search and eic_flags module

---

lib/themes/eic_community/sass/components/_attachment.scss
lib/themes/eic_community/sass/components/_link.scss
lib/themes/eic_community/snippets/wysiwyg-example.html.twig

- Fixed styling for hover on links with icons (global fix for all ecl-links)
- Fixed separator between meta data (should work correctly even if author field is not present)

EICNET-975: Story attachment styling fixes.

---

lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
lib/themes/eic_community/includes/preprocess/field/field.inc

- Add ID attribute on the group field_body so that we can add an achor to the read more button in the group header.

EICNET-1365: Group description > leads to about page (rework)

---

composer.json
composer.lock
config/sync/core.extension.yml
config/sync/smtp.settings.yml
config/sync/system.mail.yml

Added SMTP module to have more settings/controls about mail send to SMTP server. We will use MAILTRAP on environement (except local that will keep the mailhog one).
How to test:

[EICNET]feat: Add SMTP module

---

lib/themes/eic_community/includes/preprocess/content/node--document.inc

- Call to a member function toString() on string in eic_community_preprocess_node__document().

Bugfix: Fix error in eic_community_preprocess_node__document()

---

lib/themes/eic_community/includes/preprocess/groups/group.inc

- Fix issue when showing group administrators in the group about page for anonymous users.

EICNET-1410: Unexpected error when viewing About page of public group as TU

---

lib/modules/oec_group_flex/src/Entity/Form/GroupForm.php
lib/modules/oec_group_flex/src/Plugin/CustomRestrictedVisibility/RestrictedUsers.php

- Fix regression where custom restricted options where not saved after saving the group;
- Disable maxlength when selecting restricted users;

EICNET-1467: Groups - Specific user not saved in visibility Custom restriction

---

lib/themes/eic_community/includes/preprocess/content/node--news--story.inc

- Show media name instead of body when viewing story documents.

EICNET-1403: Story - Document shows body text instead of title

---

config/sync/views.view.admin_groups.yml
lib/modules/eic_admin/eic_admin.links.menu.yml

- Create groups administration view for SA/SCM.

EICNET-1511: Group overview in Drupal admin

---

lib/themes/eic_community/includes/preprocess/content/node--news--story.inc
lib/themes/eic_community/includes/preprocess/field/field--media--eic-document.inc
lib/themes/eic_community/templates/content/node--story--full.html.twig

- Show all list of documents when viewing Story detail page;
- Fix error where toString() method is called twice in eic_community_preprocess_field__field_related_downloads().

EICNET-1404: Story - Only 1st document is shown

---

config/sync/context.context.group_global.yml
lib/modules/eic_groups/src/Plugin/Block/GroupMenuBlock.php
lib/themes/eic_community/includes/preprocess/blocks/block.inc
lib/themes/eic_community/templates/blocks/block--eic-group-content-menu.html.twig

- Create new custom block plugin that overrides GroupMenuBlock in order to set the menu active trails when viewing a group content node.

EICNET-1133: Fix the group menu active item

---

lib/modules/eic_search/eic_search.module
lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GroupResultItem.js

- Fix group owner url in groups overview.

EICNET-1493: Groups - Group owner in group teaser links to groups overview

---

lib/modules/eic_groups/src/Plugin/Block/GroupMenuBlock.php

- Fix error when trying to create a group as a TU.

EICNET-1133: Fix error when trying to create a group as a TU

---

config/sync/field.field.media.eic_document.field_media_file.yml

- Update allowed file extensions for MT Document.

EICNET-1535: Basic file extensions for MT document

---

config/sync/core.entity_view_display.node.discussion.default.yml
config/sync/field.field.node.discussion.field_related_documents.yml
lib/themes/eic_community/templates/content/node--discussion--full.html.twig

- Show related documents in Discussion detail page.
- Allow only CT Documents when referencing entities in field_related_documents

EICNET-1343: Documents in Discussion are not shown

---

lib/themes/eic_community/sass/components/_tag.scss

http://localhost:9000/?path=/story/bundles-group--overview-public
https://www.figma.com/file/WZH3qhNynnmm0H6FKmD3hi/EASME_v1?node-id=2949%3A0
**BEFORE**
- BG: Lightgrey
- TXT: White
**NOW**
- BG: Lightgrey
- TXT: Grey

Fix: correct color for public tag

---

composer.json
composer.lock
composer.patches.json
config/sync/core.extension.yml
config/sync/menu_trail_by_path.settings.yml
config/sync/system.menu.main.yml
lib/modules/eic_menus/eic_menus.info.yml
lib/modules/eic_menus/eic_menus.services.yml
lib/modules/eic_menus/src/EICMenuTrailByPathActiveTrail.php

- Install contrib module menu_trail_by_path;
- Create new custom module eic_menus for custom logic around menus;
- Fix menu active trails when viewing group pages.

EICNET-1602: Fix main menu active trail when viewing group pages

---

lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.module
lib/modules/eic_statistics/modules/eic_group_statistics/src/Hooks/EntityOperations.php

- Increment/decrement group file statistics when uploading documents in CT Event.

EICNET-1601: Increment event files in group file statistics

---

config/sync/views.view.admin_groups.yml
lib/modules/eic_admin/eic_admin.links.menu.yml

- New Events administration view.

EICNET-1679: Create Events admin view

---

lib/modules/eic_groups/src/EICGroupsHelper.php

- Fix issue checking if a page is a group page when page has not been found.

EICNET-1506: As a TU, I want to see a message on blocked groups (Part 3)

---

lib/modules/eic_overviews/src/Controller/GroupOverviewsController.php

- Allow TU and GM to view group overview pages when features are enabled in the group.

EICNET-1645: TU (as GM or GO) only sees Overview, About & wiki page of the group (Bugfix)

---

config/sync/context.context.group_event_homepage.yml
config/sync/context.context.homepage.yml
config/sync/views.view.group_discussions.yml
config/sync/views.view.group_documents.yml
config/sync/views.view.group_related_groups.yml
config/sync/views.view.group_related_news_stories.yml
lib/themes/eic_community/templates/views/views-view--featured-content-collection.html.twig

- Add empty text to group overview page lists;
- Hide group overview lists if features are disabled.

EICNET-1656: Empty states for enabled empty blocks

---

lib/themes/eic_community/sass/compositions/_teaser.scss

add height 100% on teaser groups elements

[EICNET-1702] Fix: height of the teaser groups when title take 2 lines

---

config/sync/views.view.admin_groups.yml

EICNET-1679: Fix Admin Events page title

---

lib/modules/eic_flags/src/Hooks/EntityOperations.php
lib/modules/eic_groups/eic_groups.module

- Fix block/publish operation links so that the destination URL takes into account the base path.

EICNET-1546: Fix group block/publish operation links

---

lib/modules/oec_group_flex/src/Entity/Form/GroupForm.php

- Set "invite members" enabled by default when creating a new group with joining method set to "tu_open_method" instead of "tu_group_membership_request"

EICNET-1373: Change "invite member" default settings in group creation form (Rework)

---

lib/themes/eic_community/patterns/compositions/topic/topic.details.html.twig
lib/themes/eic_community/patterns/compositions/topic/topic.overview.html.twig
lib/themes/eic_community/patterns/compositions/topic/topic.overview.item.html.twig
lib/themes/eic_community/patterns/compositions/topic/topic.overview.list.html.twig
lib/themes/eic_community/patterns/compositions/topic/topic.overview.subitem.html.twig
lib/themes/eic_community/sass/compositions/_topic.scss
lib/themes/eic_community/snippets/index.js
lib/themes/eic_community/styleguide/bundles/topic.stories.js
lib/themes/eic_community/styleguide/compositions/topics.docs.mdx
lib/themes/eic_community/styleguide/compositions/topics.stories.js

- Add topic overview in storybook
- Rename old topic overview to topic details
- https://www.figma.com/file/WZH3qhNynnmm0H6FKmD3hi/EASME_v1?node-id=9649%3A48224
- http://localhost:9000/?path=/story/bundles-topic--topic-overview
New: need to add stats (client request) so I remove the arrow

[EICNET] Feat: Topics overview in storybook

---

config/sync/context.context.group_events_overviews.yml
config/sync/core.extension.yml
config/sync/field.field.node.event.field_vocab_geo.yml
lib/modules/eic_events/eic_events.info.yml
lib/modules/eic_events/eic_events.module
lib/modules/eic_events/eic_events.services.yml
lib/modules/eic_events/src/Commands/UpdateSolrEventsCommands.php
lib/modules/eic_events/src/Constants/Event.php
lib/modules/eic_search/src/Search/Sources/GlobalEventSourceType.php
lib/modules/eic_search/src/Search/Sources/GroupEventSourceType.php
lib/modules/eic_search/src/Service/SolrDocumentProcessor.php

Send the state of the event (ongoing, future, past) to solr. Also add a Drupal cron that will update event each 12hours
How to test:

[EICNET]feat: Add state label of the event in group overview

---

lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/DocumentLibraryResultItem.js

[EICNET-1696]fix: Separate filename by comma

---

config/sync/user.role.content_administrator.yml

[EICNET-1676] chore: Add the manage archival/deletion requests permission to SCM

---

lib/themes/eic_community/patterns/compositions/topic/topic.stats.html.twig
lib/themes/eic_community/styleguide/bundles/topic.stories.js

I just change the name of the key to have the same everywhere

[EICNET] Fix topic details stats keys name

---

lib/modules/eic_private_message/src/Form/PrivateMessageForm.php

EICNET-1642: Modify user messages for the user contact form.

---

config/sync/oec_group_features.group_type_features.event.yml
config/sync/oec_group_features.group_type_features.group.yml
lib/modules/oec_group_features/config/schema/oec_group_features.group_type_features.schema.yml
lib/modules/oec_group_features/oec_group_features.module
lib/modules/oec_group_features/oec_group_features.services.yml
lib/modules/oec_group_features/src/GroupFeatureHelper.php
lib/modules/oec_group_features/src/Hooks/EntityOperations.php

- Although it would be a nice addition, currently there's no interface to manage the enabled features per group type (not in the scope)

EICNET-1733: Define different set of group features depending on the group type.

---

config/sync/user.role.content_administrator.yml
config/sync/user.role.site_admin.yml

- Add permissions to edit custom blocks and access custom blocks overview page (for SA and SCM users).

EICNET-286: Allow SA/SCM users to edit custom blocks

---

lib/themes/eic_community/includes/preprocess/layout/page.inc

- Fixed caching issues that prevented anonymous users to see the correct access denied message depending on the group.
Notes: Make sure you **DO NOT** clear the cache between those 2 steps.

EICNET-1506: Show group under review message (cache issues)

---

lib/modules/eic_flags/src/Hooks/EntityOperations.php

- Do not flag topic of interest if the user is already following the topic.

EICNET-1725: Error when adding a topic of interest in user profile

---

config/sync/pathauto.pattern.books.yml
config/sync/pathauto.pattern.discussions.yml
config/sync/pathauto.pattern.events.yml
config/sync/pathauto.pattern.library.yml
config/sync/pathauto.pattern.news.yml
config/sync/pathauto.pattern.stories.yml
config/sync/pathauto.settings.yml

EICNET-1771: Configure pathauto to not create new aliases automatically on title change.

---

config/sync/core.entity_form_display.message.notify_content_status_changed.default.yml
config/sync/core.entity_view_display.message.notify_content_status_changed.default.yml
config/sync/core.entity_view_display.message.notify_content_status_changed.mail_body.yml
config/sync/core.entity_view_display.message.notify_content_status_changed.mail_subject.yml
config/sync/field.field.message.notify_content_status_changed.field_entity_prev_status_label.yml
config/sync/field.field.message.notify_content_status_changed.field_entity_status_label.yml
config/sync/field.field.message.notify_content_status_changed.field_entity_url.yml
config/sync/field.field.message.notify_content_status_changed.field_message_subject.yml
config/sync/field.field.message.notify_content_status_changed.field_referenced_entity_label.yml
config/sync/field.storage.message.field_entity_prev_status_label.yml
config/sync/field.storage.message.field_entity_status_label.yml
config/sync/field.storage.message.field_entity_url.yml
config/sync/language/en/message.template.notify_content_status_changed.yml
config/sync/message.template.notify_content_status_changed.yml
lib/modules/eic_messages/src/Hooks/EntityOperations.php

- Create new generic message type to use when an entity has changed status;
- Send notification message to group owner when SA/SCM unblocks a group.

EICNET-1510: Email notification for a group transitioned to unblocked

---

lib/themes/eic_community/includes/preprocess/layout/page.inc

Bugfix: when the value of private field is empty (NULL), it was showing Community members only while remaining available for anonymous users.
This mostly applies to contents not created throught the UI where the value would be set automaticlaly depending on the checkbox. (like content generation)

EICNET-1673: Fix issue with wrong visibility for stories/news.

---

lib/themes/eic_community/sass/components/_tag.scss

- create a restricted group and check if tag "custom" is orange
https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&view=detail&selectedIssue=EICNET-1722&quickFilter=26822

[EICNET] Fix color for custom group's tags

---

docker/nginx/servers/default.conf
lib/modules/eic_helper/eic_helper.services.yml
lib/modules/eic_helper/src/StackMiddleware/HeaderMapper.php
web/sites/default/default.settings.local.php

Unfortunately our dev environments aren't supporting standard X-Forwarded-* headers. This PR introduces an HTTP middleware which maps custom headers into standard X-Forwarded-* headers and let's the symfony/http-foundation component do its job.

[EICNET] Convert non-standard reverse proxy headers to standard ones

---

config/sync/core.entity_form_display.group_content.group-group_membership.default.yml

[EICNET-1692] fix: Remove the url alias field from the join form

---

config/sync/core.entity_view_display.overview_page.overview_page.default.yml
lib/modules/eic_default_content/eic_default_content.services.yml
lib/modules/eic_default_content/src/Generator/MenuGenerator.php
lib/modules/eic_default_content/src/Generator/OverviewPageGenerator.php
lib/modules/eic_overviews/eic_overviews.module
lib/modules/eic_overviews/src/GlobalOverviewPages.php
lib/modules/eic_search/eic_search.services.yml
lib/modules/eic_search/src/Search/Sources/NewsStorySourceType.php
lib/themes/eic_community/includes/preprocess/views.inc

- There is a new MenuGenerator that will create the main menu links

EICNET-1780: Create News & Stories and Events overview pages in default content

---

config/sync/context.context.global.yml
config/sync/context.context.global_breadcrumbs.yml
lib/themes/eic_community/includes/preprocess/common.inc
lib/themes/eic_community/includes/preprocess/overview_pages/overview-page.inc
lib/themes/eic_community/templates/overview_pages/overview-page.html.twig

- Create common function to load breadcrumb block;
- Place breadcrumb block bellow the global overview banner.

EICNET-1838: Display breadcrumbs below global overview banner

---

config/sync/user.role.content_administrator.yml
config/sync/user.role.site_admin.yml

- Allow SA/SCM users to add links to any page when filling in a link field.

EICNET-286: As a site admin I want to be able to adapt the non logged in homepage welcome header content (Rework)

---

config/sync/flag.flag.follow_user.yml
config/sync/user.role.trusted_user.yml
lib/modules/eic_flags/eic_flags.module
lib/modules/eic_flags/src/Plugin/ActionLink/EICFlagCountLink.php
lib/modules/eic_flags/src/Plugin/ActionLink/EICFlagCountLinkButton.php
lib/modules/eic_user/src/Hooks/FieldWidgetOperations.php
lib/themes/eic_community/includes/preprocess/users/user.inc
lib/themes/eic_community/sass/components/_link.scss
lib/themes/eic_community/templates/flag/eic-flag-count.html.twig

- Show user type label in profile detail page.
- Adds user operation links dropdown when viewing profile detail page.
- Show contact link and follow flag if current user is not viewing its own profile page.
- Do not show LinkedIn profile link if empty.
- Allow trusted users to be able to edit their own member profile.
As Trusted user:

EICNET-1627: As a user, I want to have a profile page so that I can see the personal informations of another user (Back-end)

---

composer.lock
composer.patches.json
config/sync/entity_usage.settings.yml

- Add custom_block and group entities as entity usage source so that anonymous users can view private images that are attached to custom_blocks and groups.
- Create and apply contrib patch that fixes endless loop during batch operation to update all entity usages (see https://www.drupal.org/project/entity_usage/issues/3168418#comment-14331779).

EICNET-1839: Private images re-used in homepage banner are not shown for anonymous

---

lib/modules/eic_groups/eic_groups.module
lib/modules/eic_groups/src/EICGroupsHelper.php
lib/modules/eic_groups/src/Plugin/views/field/GroupMembersByRole.php
lib/modules/eic_groups/src/Plugin/views/field/RestrictedOrganisationTypes.php
lib/modules/eic_groups/src/Plugin/views/field/RestrictedOrganisations.php
lib/modules/oec_group_flex/oec_group_flex.module
lib/modules/oec_group_flex/src/Plugin/views/field/GroupFlexFieldPluginBase.php
lib/modules/oec_group_flex/src/Plugin/views/field/GroupVisibility.php
lib/modules/oec_group_flex/src/Plugin/views/field/RestrictedEmailDomains.php
lib/modules/oec_group_flex/src/Plugin/views/field/RestrictedUsers.php

This PR provides following views field plugins to the `oec_group_flex` module:
- Visibility
- Visibility Custom: Restricted email domains
- Visibility Custom: Restricted users
Also following views field plugins to the `eic_groups` module:
- Visibility Custom: Restricted organisations
- Visibility Custom: Restricted organisation types
- Group members
This PR doesn't provide in any way a data export, this is just a first chunk.

Feature/eicnet 1860 data export [Part 1]

---

lib/modules/eic_user/src/Hooks/FormAlter.php

[EICNET-1728]fix: remove empty email when trying to invite people

---

lib/themes/eic_community/images/sprite/custom/document.svg
lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/DocumentLibraryResultItem.js
lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/GalleryLibraryResultItem.js
lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/Partials/LikeLink.js
lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/Partials/Meta.js
lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/VideoLibraryResultItem.js
lib/themes/eic_community/sass/compositions/_teaser.scss

https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&projectKey=EICNET&view=detail&selectedIssue=EICNET-1851&quickFilter=26822
The thumbnail for single file should be a file icon. Currently it is empty or showing an image of the file which is incorrect
The thumbnail for multiple files should be a multiple files icon. Currently it is empty or showing an image of the file which is incorrect
The thumbnail should be displayed as cover 1:1 ratio. It is currently display as fit. This is the case for videos and single image
The language icon is missing for the language meta-data
The uploaded by icon is missing for the uploaded by meta-data
The like action is not displayed. It should be.
The highlight action is not displated. It should be.
For multiple files, we need …

[EICNET-1851]  group library overview teaser rework

---

config/sync/views.view.groups.yml
lib/themes/eic_community/includes/preprocess/users/user.inc
lib/themes/eic_community/templates/user/user--full.html.twig

- Fix titles in user profile tabs.

EICNET-1835: User profile my groups (rework)

---

config/sync/context.context.global_breadcrumbs.yml
lib/themes/eic_community/includes/preprocess/taxonomy/taxonomy_term.inc
lib/themes/eic_community/templates/layout/page--taxonomy--term.html.twig

- Show breadcrumb bellow page banner when viewing topic detail page.

EICNET-1872: Display breadcrumb bellow page banner in topic detail page

---

config/sync/field.field.group.group.field_group_invite_members.yml
lib/modules/oec_group_flex/src/Entity/Form/GroupForm.php

- Revert logic that automatically enables membership invitations when creating a group.
- Make Invite members checkbox enabled by default when a user creates a group.

EICNET-1373: Keep user invite members choice when creating a group

---

lib/modules/eic_content/modules/eic_content_book/src/Hooks/BookTokens.php
lib/modules/eic_groups/eic_groups.module

- Re-creates URL alias of the group content related entity if pathauto settings "update_action" setting is set to 0;
- Fix URL alias generation for patterns using "node_book_parent_url" token.

EICNET-1602: Fix URL aliases for group content entities

---

config/sync/user.role.content_administrator.yml
config/sync/user.role.site_admin.yml
lib/modules/eic_content/modules/eic_content_book/eic_content_book.module
lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
lib/modules/eic_groups/src/Plugin/GroupContentEnabler/GroupInvitation.php

- Fix access to invite users when user is not a member of a group and also depending on the group status.
- Allow SA/SCM users to update book outlines.
Invite members:
Book outline

EICNET-1649: Display local tasks in a select field (rework)

---

lib/modules/eic_overviews/src/Entity/OverviewPage.php
lib/modules/eic_overviews/src/OverviewPageHtmlRouteProvider.php

- Create OverviewPageHtmlRouteProvider class to set permission requirement when access overview page collection route.

EICNET-852: Overview page banner (rework)

---

lib/modules/eic_content/src/Hooks/EntityOperationsContributor.php
lib/modules/eic_groups/src/Plugin/Block/CommentsFromDiscussionBlock.php

- Show users who commented nodes as contributors next to the comment section;
- Change comment section title to "Replies"
- Fix cache issues when showing the comment avatar after user logs in with a different account;

EICNET-1369: EICNET-1369 Adapt comment section on video detail page (rework)

---

lib/modules/eic_overviews/src/Controller/GroupOverviewsController.php

EICNET-1526: Fix group overviews access. (rework)

---

lib/modules/eic_comments/src/Constants/Comments.php
lib/modules/eic_groups/src/EICGroupsHelper.php
lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.module
lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.services.yml
lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsHelper.php
lib/modules/eic_statistics/modules/eic_group_statistics/src/Hooks/EntityOperations.php
lib/modules/eic_statistics/modules/eic_group_statistics/src/Plugin/views/field/GroupLatestActivity.php

- Provide logic to calculate group latest activity, with cache
- Provide a views field plugin to display the value
- The date should also be updated when deleting a comment, but since we don't hard-delete comments, it doesn't apply

EICNET-1860: Group latest activity

---

composer.lock
composer.patches.json

- Apply patch to fix access issues when selecting a media in a blocked group.

EICNET-1699: SA & SCM cannot add documents to a blocked group

---

lib/themes/eic_community/includes/preprocess/layout/page.inc

- Split footer menu links in 2 columns if there are more than 3 links.

EICNET-1761: Fix footer menu links

---

lib/modules/eic_private_message/src/Form/PrivateMessageForm.php

[EICNET-1604]fix: Encapsulate the email FROm by <>

---

lib/modules/eic_groups/src/Plugin/Block/GroupMenuBlock.php
lib/modules/eic_overviews/src/GroupOverviewPages.php

[EICNET-1634]fix: Handle events group menu active on detail

---

config/sync/views.view.groups_homepage.yml
lib/modules/eic_search/src/Plugin/views/cache/SearchApiTagCachePerUser.php

- Change groups homepage view cache to tag based per user because group visibility can be changed and there is an issue where anonymous users can see private groups in the list.

EICNET-1689: Homepage last updated groups (rework 2)

---

composer.lock
composer.patches.json
config/sync/user.role.content_administrator.yml
config/sync/user.role.trusted_user.yml

- Apply patch to fix issue where user cannot save draft version of a published story because of book privileges.
- Allow content owners to access latest revision.

EICNET-1927: TU cannot create draft from published story

---

lib/themes/eic_community/includes/preprocess/layout/page.inc

- Add footer site info block to the footer section.

EICNET-1754: Footer site name

---

lib/modules/oec_group_flex/src/Plugin/GroupVisibility/CustomRestrictedVisibility.php

- Fix issue where custom restriction visibility options were not shown in group add form;
- Fix error when editing a group without visibility.

EICNET-1937: Custom restriction visibility options not shown in group add form

---

lib/modules/eic_groups/src/Plugin/QueueWorker/GroupContentUrlAliasUpdate.php

- Create redirect for the old group content node url alias when group alias changes.

EICNET-962: Group alias update create redirects (rework group content node URL alias)

---

lib/themes/eic_community/includes/preprocess/users/user.inc

- Fix titles in user profile tab "My interests"

EICNET-1835: Fix title in user profile tab "My interests"

---

lib/modules/eic_content/src/ContentBreadcrumbBuilder.php

EICNET-1920: Fix breadcrumb for News and Stories.

---

lib/modules/eic_search/src/Controller/SolrSearchController.php

EICNET-1697: Show non published groups to power users. (rework)

---

lib/modules/eic_groups/src/Hooks/Pathauto.php

- Fix issue where group alias url queue was being filled when using pathauto generator to retrieve a group URL alias.

EICNET-XXXX: Group URL alias cron issues

---

lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Answer.js
lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/CommentForm.js
lib/themes/eic_community/sass/compositions/_comment-form.scss
lib/themes/eic_community/sass/compositions/_discussion-thread.scss

https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&projectKey=EICNET&view=detail&selectedIssue=EICNET-1917&quickFilter=26822
_When indenting to level 3 I see a small horizontal rule instead of the vertical ruler_
> It's only for mobile because the desktop version take to much place on mobile so it's a variant

[EICNET-1917] Comments front-end mobile

---

lib/modules/eic_groups/src/Plugin/GroupFeature/EicGroupsGroupFeaturePluginBase.php
lib/modules/oec_group_features/src/GroupFeaturePluginBase.php
lib/modules/oec_group_features/src/Hooks/EntityOperations.php

EICNET-1974: Fix Group feature permissions issue

---

lib/modules/eic_messages/modules/eic_message_subscriptions/src/Hooks/FormOperations.php
lib/modules/eic_messages/src/Hooks/FormOperations.php

[EICNET-1238]feat: Disable by default field notification and activity for certain types

---

config/sync/group.type.event.yml

- Assign owner role to the Event group creator.

EICNET-1977: Error when creating a Global event as a Trusted user

---

lib/modules/eic_content/src/Plugin/Block/ContentOperationsBlock.php

- Fix URLs to add a group or event in the homepage actions.

EICNET-1975: Adapt URL for adding a group/event on homepage

---

lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Partials/StatisticsFooterResult.js

- Show correct statistics in activity stream items;
- Remove like counter statistic from wiki page items in the activity stream.
- Remove comments counter statistic from wiki page items in the activity stream.

EICNET-1450: Counters in activity stream (improvements)

---

lib/themes/eic_community/includes/preprocess/layout/page.inc

- Add cache context "session" in hook_preprocess_page() so that the account header shows the updated user information and links according to the current logged in user.

EICNET-1987: Cache issues in account header

---

config/sync/search_api.index.global.yml
lib/modules/eic_overviews/src/GlobalOverviewPages.php
lib/modules/eic_search/src/Search/Sources/OrganisationSourceType.php
lib/themes/eic_community/includes/preprocess/groups/organisation.inc

PS: be sure you enabled the facets on the overview page (Topics, activity sector, target sector)

[EICNET-1880]feat: Add overview url prefiltered by topic

---

config/sync/context.context.group_files_overviews.yml
lib/modules/eic_search/src/Search/Sources/LibrarySourceType.php

How to test:
```
Alphabetic order (A-Z): sorted on title (A-Z)
Alphabetic order (Z-A): sorted on title (Z-A)
Date uploaded (most recent first)
Highlighted files: first show all highlighted files, then the remaining files according to date uploaded (most recent first)
Number of downloads (desc): according to highest download count first
Number of views (desc): according to highest view count first
Number of likes
```

[EICNET-1101]fix: Use correct label + sort option

---

lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-moderated-message-box.inc
lib/themes/eic_community/templates/blocks/eic-group-moderated-message-box.html.twig

- Add missing icon to operations dropdown in group draft message banner.

EICNET-2003: Group creation status draft banner improvements 

---

lib/themes/eic_community/templates/group/group--group--about-page.html.twig

- Override group--group--about-page template (for some reason group--about-page is not picked).

EICNET-873: Regression issues in group about page

---

lib/modules/eic_flags/src/FlaggedEntitiesListBuilder.php

- Enable sort feature in entity list builder of request flags;

EICNET-2014: Allow SA/SCM to sort archival and delete request in administration view

---

config/sync/core.entity_form_display.message.stream_gallery_insert_update.default.yml
config/sync/core.entity_form_display.message.stream_video_insert_update.default.yml
config/sync/core.entity_view_display.message.stream_gallery_insert_update.default.yml
config/sync/core.entity_view_display.message.stream_video_insert_update.default.yml
config/sync/field.field.message.stream_gallery_insert_update.field_entity_type.yml
config/sync/field.field.message.stream_video_insert_update.field_entity_type.yml

- If you have previous actvity messages of types Gallery or Video, this might break the atcivity stream. Either delete them or start on new install

EICNET-1573: Add missing fields to gallery and video activity stream messages.

---

lib/themes/eic_community/includes/preprocess/groups/group.inc

- Fix label and color of group visibility in homepage lists.

EICNET-1896: Color group states on homepage

---

lib/modules/eic_groups/eic_groups.module
lib/modules/eic_groups/src/EventSubscriber/BookPageRedirectSubscriber.php
lib/modules/eic_groups/src/Hooks/EntityOperations.php

- Fix redirect issue when accessing wiki section as anonymous user;
- Update wiki redirection when changing wiki page weights;

EICNET-2064: As a non logged in (anonymous user) I cannot access wiki pages on the upper level

---

lib/themes/eic_community/react/components/Block/Overview/Search/Field/CheckboxField.js
lib/themes/eic_community/react/components/Block/Overview/Search/Field/CollapsedOptions.js
lib/themes/eic_community/react/components/Block/Overview/Search/TopOptions/ActiveFacet.js

https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-1847

[EICNET-1847] cancel the jump when we use a filter on mobile

---

lib/themes/eic_community/sass/compositions/_organisation.scss
lib/themes/eic_community/styleguide/bundles/organisation.stories.js
lib/themes/eic_community/templates/group/group--organisation--full.html.twig

https://citnet.tech.ec.europa.eu/CITnet/jira/projects/EICNET/issues/EICNET-1907?filter=myopenissues
https://www.figma.com/file/j583oU3vO3YfrU3SnZp4vQ/EIC---Analysis?node-id=3%3A3566

[EICNET-1907] change image style - change tag style

---

lib/themes/eic_community/data/featured-content-collection/discussion.data.js
lib/themes/eic_community/sass/compositions/_discussion-thread.scss

https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-1569?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel
http://localhost:9000/?path=/story/bundles-topic--topic-details
https://www.figma.com/file/WZH3qhNynnmm0H6FKmD3hi/EASME_v1?node-id=9625%3A46422

[EICNET-1569] restyle correctly related discussion in topics

---

lib/themes/eic_community/includes/preprocess/groups/group.inc

- Change group visibility label for custom restricted groups to "Restricted"

EICNET-1896: Color group states on homepage (Custom restricted groups)

---

lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
lib/themes/eic_community/includes/preprocess/common.inc

- Hide group management dropdown for anonymous users;
- Improvements in logic to check access to a flag in the theme.

EICNET-2085: Anonymous user sees Group management button

---

lib/modules/oec_group_flex/src/OECGroupFlexHelper.php
lib/themes/eic_community/includes/preprocess/groups/group.inc

- Change group visibility label for custom restricted groups sitewide.

EICNET-1896: Color group states (sitewide)

---

lib/themes/eic_community/sass/components/_filelist.scss

Fixed the issue where the header for the filelist wraps to the next line when a filename is too long.

EICNET-1532: Filelist header width fix.

---

config/sync/context.context.group_members_overviews.yml
lib/modules/eic_groups/eic_groups.install
lib/modules/eic_groups/src/Plugin/GroupFeature/GroupAnchorFeature/GroupAnchorMembers.php
lib/modules/eic_overviews/eic_overviews.routing.yml
lib/modules/eic_overviews/src/Controller/GroupOverviewsController.php
lib/modules/eic_overviews/src/GroupOverviewPages.php
lib/themes/eic_community/includes/preprocess/groups/organisation.inc

[EICNET-1908]feat: Create new endpoint for organisation "/team" overview

---

config/sync/field.field.block_content.basic.body.yml
config/sync/field.field.block_content.basic.field_title.yml

- Make title and body fields as mandatory in Block type Basic.
- ~~Currently the block type that is used (Basic) is also used in other pages such as the contact form (https://qa-eic-7998fed89ac0.victhorious.com/community/contact). The problem is that in the contact form, we have the user name text in bold which means we cannot use plain text here. The only solution would be creating a new block type but I would discard that option even because the only people who can manage those blocks are content manager and site admins.~~

EICNET-1753: Footer site name (rework)

---

lib/themes/eic_community/includes/preprocess/overview_pages/overview-page.inc

- Fix regression in create new group CTA button in groups overview page;

EICNET-2102: Create-a-new-group CTA not working and wrong color

---

config/sync/context.context.my_profile.yml
lib/modules/eic_search/src/Controller/SolrSearchController.php
lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobal.php
lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGroupContent.php
lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorMessage.php
lib/modules/eic_search/src/Search/Sources/Profile/ActivityStreamSourceType.php
lib/modules/eic_search/src/Search/Sources/SourceType.php
lib/modules/eic_search/src/Search/Sources/SourceTypeInterface.php
lib/themes/eic_community/react/components/Block/Overview/Search/Results.js
lib/themes/eic_community/react/components/Block/Overview/Search/Sidebar.js

How to test:
In this one I also updated the feed results:

[EICNET-1945]feat: Implement correct filter for profile activity feed + set correct datasource feed

---

lib/themes/eic_community/includes/preprocess/groups/organisation.inc

[EICNET-1907]fix: Use group getMembers method instead of statistics

---

config/sync/context.context.contact_page.yml
config/sync/context.context.contact_page_anonymous.yml
config/sync/context.context.global_breadcrumbs.yml

- Move breadcrumb block bellow the page banner image in the contact page.

EICNET-2095: Breadcrumbs on contact must be below the banner

---

lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php
lib/modules/eic_search/src/Search/Sources/Profile/ActivityStreamSourceType.php
lib/modules/eic_search/src/Search/Sources/SourceType.php
lib/modules/eic_search/src/Search/Sources/SourceTypeInterface.php
lib/themes/eic_community/react/components/Block/Overview/index.js

How to test:
PS: if you do not have enough items, add group contents with another use. Cause your user's content will be prefiltered on results

[EICNET]fix: use load more for activity feed

---

config/sync/core.entity_view_display.comment.node_comment.notification_teaser.yml
lib/themes/eic_community/templates/content/comment--notification-teaser.html.twig

- Remove extra comma from rendered output of tagged users in comments.

EICNET-1940: Email notification for user tagging in comments (Improvements)

---

lib/modules/eic_groups/src/EICGroupsHelper.php
lib/modules/eic_groups/src/Hooks/EntityOperations.php
lib/themes/eic_community/includes/preprocess/events.inc
lib/themes/eic_community/includes/preprocess/groups/event.inc
lib/themes/eic_community/templates/group/group--event--about-page.html.twig

- Fix event about page;
- Improve method to retrieve group visibility descriptions;

EICNET-2087: About section in global events

---

lib/themes/eic_community/react/components/Block/Overview/index.js

When there is a sort field the search query was executed before applying the facets. This resulted in 2 search calls being launched and thus the results on the page might not be correct (depending on which request finishes last). I added a check to make sure the update sort request is not executed when the component is still initializing.

EICNET-1907: Overview double load fix.

---

config/sync/search_api.index.global.yml
lib/modules/eic_overviews/src/GroupOverviewPages.php
lib/modules/eic_search/eic_search.services.yml
lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobalEvent.php
lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGroupEvent.php
lib/modules/eic_search/src/Search/Sources/GlobalEventSourceType.php
lib/themes/eic_community/includes/preprocess/content/node--event.inc
lib/themes/eic_community/includes/preprocess/groups/event.inc
lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GlobalEventResultItem.js
lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GroupEventResultItem.js

[EICNET-1909]fix: Set event type instead of topics in teaser tag + format image

---

config/sync/eic_groups.group_features.eic_groups_anchor_group_events.yml
config/sync/eic_groups.group_features.eic_groups_anchor_members.yml
config/sync/eic_groups.group_features.eic_groups_anchor_news.yml

[EICNET-190]fix: do not enable add news/event add content for GM

---

config/sync/views.view.groups_homepage.yml

- Fix "view all events" link in group homepage events.

EICNET-2086: Homepage - upcoming events should show "view all events"

---

config/sync/views.view.latest_news_and_stories.yml
lib/modules/eic_default_content/src/Generator/NewsGenerator.php
lib/modules/oec_group_flex/oec_group_flex.module
lib/modules/oec_group_flex/src/Plugin/views/filter/GroupVisibility.php

- Create new views filter plugin for group visibility;
- Update entity browser for selecting News and Stories to show in the homepage so that it only allows SA/SCM users to select published content (including content from public groups).

EICNET-2116: News articles within organisation can be promoted on homepage

---

config/sync/field.field.group.organisation.field_header_visual.yml
config/sync/field.field.group.organisation.field_thumbnail.yml

EICNET-1991: Make image fields optional for organisations.

---

lib/themes/eic_community/sass/compositions/_teaser.scss

Fixed regression issue caused by update to image height for story teaser. This caused group overview teasers to not have correct height. Moved fix for story teaser to a more specific selector.
Check that height of images on group overview is correct.

EICNET-2097: Teaser image height fix.

---

lib/themes/eic_community/sass/components/_progress.scss
lib/themes/eic_community/sass/eic_community.screen.scss

Fixed styling of the progress bar for GA.
- Go to a group logged in as group admin. 
- Click on "invite users"
- Select a number of users and submit form
- While sending the invite a progress bar should be visible

EICNET-1728: Fix styling of progress bar.

---

lib/themes/eic_community/includes/preprocess/groups/event.inc
lib/themes/eic_community/includes/preprocess/groups/group.inc

- Show custom restricted options (restricted users + restricted organisations + restricted organisation types) when viewing Group/Event about page.

EICNET-2114: Fix permission tab in Event about page

---

lib/themes/eic_community/includes/preprocess/groups/event.inc

[EICNET]fix: Set type as multi array in teaser event

---

lib/themes/eic_community/includes/preprocess/groups/group.inc
lib/themes/eic_community/patterns/compositions/extended-list/extended-list-item.html.twig

[EICNET-2129]fix: put body of about page as raw

---

config/sync/views.view.admin_groups.yml
config/sync/workflows.workflow.groups.yml
lib/modules/eic_groups/modules/eic_share_content/eic_share_content.services.yml
lib/modules/eic_groups/modules/eic_share_content/src/Service/ShareManager.php
lib/modules/eic_groups/src/GroupsModerationHelper.php
lib/themes/eic_community/includes/preprocess/common.inc

- Moved the logic to get target groups to the ShareManager module
- Now filtering traget groups based on user
- Created a static method to check if group is blocked
- Created a static method to check if group is archived
- Changed the Archived state to remain published

EICNET-2110: Share content: make sure users can share to the groups they belong only

---

config/sync/user.role.content_administrator.yml
config/sync/user.role.site_admin.yml

- Add permission to access entity browser for the Latest News and Stories.

EICNET-2116: News articles within organisation can be promoted on homepage (rework)

---

lib/themes/eic_community/sass/compositions/_editorial-header.scss

https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&view=detail&selectedIssue=EICNET-2071&quickFilter=26822
- remove bg color on img in editorial header

[EICNET-2071] remove bg color on img in editorial header

---

lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobal.php

- Fix group owner url in groups overview.

EICNET-1493: Groups - Group owner in group teaser links to groups overview (rework)

---

lib/modules/eic_content/src/Constants/DefaultContentModerationStates.php
lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.module
lib/modules/eic_statistics/modules/eic_group_statistics/src/Hooks/EntityOperations.php

- Rework group statistics in order to make it work with content moderation.

EICNET-2134: Default workflow breaks group statistics

---

config/sync/block_content.type.contact_box.yml
config/sync/context.context.book_pages.yml
config/sync/core.entity_form_display.block_content.contact_box.default.yml
config/sync/core.entity_view_display.block_content.contact_box.default.yml
config/sync/field.field.block_content.contact_box.body.yml
config/sync/field.field.block_content.contact_box.field_cta_button.yml
config/sync/field.field.block_content.contact_box.field_title.yml
config/sync/field.storage.block_content.field_cta_button.yml
config/sync/language.content_settings.block_content.contact_box.yml
lib/modules/eic_content/modules/eic_content_book/src/Hooks/EntityOperations.php
lib/modules/eic_default_content/src/Generator/BlockContentGenerator.php
lib/modules/eic_deploy/eic_deploy.install
lib/modules/eic_messages/modules/eic_message_subscriptions/src/Hooks/FormOperations.php
lib/themes/eic_community/includes/preprocess/blocks/block--contact-box.inc
lib/themes/eic_community/includes/preprocess/blocks/block.inc
lib/themes/eic_community/patterns/components/navigation-list/navigation-list-items.html.twig
lib/themes/eic_community/patterns/components/navigation-list/navigation-list.html.twig
lib/themes/eic_community/templates/blocks/block--eic-contact-box-help-guindance.html.twig
lib/themes/eic_community/templates/blocks/block--eic-content-book-navigation.html.twig
lib/themes/eic_community/templates/layout/page--node--book.html.twig
lib/themes/eic_community/templates/layout/page--node--wiki-page.html.twig

- Create new block type contact_box and place it in book page contexts;
- Add new block contact_box to fixtures and create hook_update_n;
- Fix twig templates in order to include blocks in the book page sidebar and preprocess variables for the contact box block.
Test contact box:
Test book page creation:

EICNET-2054: Help and guidance contact box: back-end

---

lib/modules/eic_messages/modules/eic_message_subscriptions/src/Hooks/FormOperations.php
lib/modules/eic_messages/src/Hooks/FormOperations.php

- Skip entity activity stream and subscription message creation when user creates a new DRAFT from a PUBLISHED version.

EICNET-1993: Drupal default workflow improvements in message creations 

---

lib/modules/eic_user/eic_user.routing.yml
lib/modules/eic_user/src/Breadcrumb/UserBreadcrumbBuilder.php

How to test:
[My profile]
[My activity feed][My followings (or your current overview title)]

[EICNET-1959]fix: Put parent breadcrumb for activities user

---

lib/modules/eic_groups/modules/eic_share_content/src/Service/ShareManager.php
lib/themes/eic_community/includes/preprocess/common.inc

EICNET-2120: Make sure we don't show the group sharing link if user doesn't have access to it

---

config/sync/views.view.group_discussions.yml
config/sync/views.view.group_documents.yml
config/sync/views.view.group_events.yml
config/sync/views.view.group_related_groups.yml
lib/themes/eic_community/includes/preprocess/views.inc

- Fix "View all" links in group overview page blocks.
- Removed link "View all" from **Related News and Stories** and **Related groups**
Created a follow-up ticket to discuss what to do with link "View all" -> https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-2177

EICNET-2072: Group overview with "view all" links below every content block have a faulty link

---

lib/modules/eic_search/src/Controller/SolrSearchController.php

[EICNET-1952]fix: Replace method used to get unpublished groups where user is owner

---

lib/modules/eic_content/modules/eic_content_book/src/Hooks/EntityOperations.php

- Fix error when creating book page with book outline settings as empty.

EICNET-2169: Error when create a book page without assigning it to a book

---

lib/modules/eic_default_content/src/Generator/BlockContentGenerator.php
lib/modules/eic_deploy/eic_deploy.install

- Update CTA button URI of contact box block when generating with fixtures.

EICNET-1818: Update CTA button URI of contact box block

---

lib/modules/eic_topics/src/Constants/Topics.php

[EICNET-2179]fix: Use new SOLR field for group topic name

---

lib/modules/eic_groups/eic_groups.module
lib/modules/eic_groups/src/Plugin/Block/EICGroupOverviewMessageBlock.php
lib/themes/eic_community/templates/blocks/eic-group-moderated-message-box.html.twig

- Group approved banner "Click here" link redirects to global contact form.

EICNET-2003: Group approved banner "Click here" link improvements

---

lib/themes/eic_community/includes/preprocess/paragraphs/paragraph--quote.inc
lib/themes/eic_community/sass/components/_blockquote.scss
lib/themes/eic_community/styleguide/components/blockquote.stories.js

- Fix regression where quote paragraphs in News were not showing the author name + image anymore.

EICNET-2171: Fix quote author in News

---

lib/modules/eic_deploy/eic_deploy.install
lib/modules/eic_groups/src/Plugin/GroupFeature/GroupLatestActivityStream.php

- Remove group permission "access latest activity stream" from anonymous users.
- We need to run drush updb in order to remove the group permission (for anonymous user role) from all groups.

EICNET-2174: Group activity stream cannot be viewed by non logged (anonymous) users

---

config/sync/core.entity_view_display.node.document.default.yml

- Update field topics in document default view mode in order fix the topic link when viewing the document detail page

EICNET-2181: Documents - Topic label links to same page

---

lib/themes/eic_community/includes/preprocess/layout/page.inc

- Show author avatar when viewing News/Story detail page.

EICNET-2172: No avatar shown on news articles

---

lib/modules/eic_flags/src/EventSubscriber/FlagEventSubscriber.php
lib/modules/eic_groups/src/Controller/DiscussionController.php
lib/modules/eic_statistics/eic_statistics.services.yml
lib/modules/eic_statistics/src/NodeStatisticsDatabaseStorage.php
lib/modules/eic_statistics/src/StatisticsHelper.php
lib/themes/eic_community/includes/preprocess/common.inc

[EICNET-1745]fix: set correct statistics + invalidate cache when event like

---

config/sync/views.view.organisation_content.yml

[EICNET]fix: Set default order for news in organisation by created date

---

lib/themes/eic_community/sass/compositions/_editorial-article.scss
lib/themes/eic_community/sass/compositions/_featured-list.scss
lib/themes/eic_community/templates/group/group--organisation--full.html.twig

https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&projectKey=EICNET&view=detail&selectedIssue=EICNET-2142&quickFilter=26822
- Now in organisation contact sidebar, we can collapse/expand the addresses items

organisation contact collapsed adress

---

lib/modules/eic_deploy/eic_deploy.install
lib/modules/eic_deploy/eic_deploy.module
lib/modules/oec_group_flex/src/Plugin/GroupVisibility/PublicVisibility.php
lib/themes/eic_community/sass/compositions/_comment-overview.scss

- Adds "view comments" permission to outsiders in public groups;
- Create hook_update to update all existing groups.
- As TU you will still see the reply button in the comments but that will be fixed in PR #1288

EICNET-2135: TU cannot view comments of content in public groups

---

lib/modules/eic_admin/eic_admin.links.menu.yml
lib/modules/eic_admin/eic_admin.routing.yml
lib/modules/eic_admin/src/Form/UpdateAllGroupPermissionsForm.php

[EICNET]feat: Create a form to update every groups permissions from their group types

---

config/sync/pathauto.pattern.books.yml
lib/themes/eic_community/includes/preprocess/blocks/block--eic-content-book-navigation.inc

- Update URL pattern for Book pages;
- Fix book navigation preprocess in order to re-use the logic of wiki page book navigation.
- The help and guidance book navigation should have the same structure as seen on wiki pages.

EICNET-2196: Update book page URL pattern and add missing variables to the Theme

---

lib/modules/eic_topics/eic_topics.module

EICNET-2187: Fix issue with double base path in views more links.

---

lib/modules/eic_topics/eic_topics.module

[EICNET-2179]feat: Set correct topic name field in solr to prefilter on

---

config/sync/core.entity_form_display.media.eic_document.default.yml

[EICNET-1990]fix: Use entity reference autocomplete widget for file document topics

---

lib/modules/eic_groups/templates/eic-group-comments-from-discussion.html.twig
lib/themes/eic_community/patterns/layout/base.html.twig

[EICNET-2105]fix: Do not render empty content_after region

---

config/sync/group.role.organisation-dcb2f93df.yml
config/sync/workflows.workflow.groups.yml

[EICNET]fix: remove view unpublished group permission from TU

---

config/sync/core.entity_form_display.message.notify_group_deleted.default.yml
config/sync/core.entity_view_display.message.notify_group_deleted.default.yml
config/sync/core.entity_view_display.message.notify_group_deleted.mail_body.yml
config/sync/core.entity_view_display.message.notify_group_deleted.mail_subject.yml
config/sync/field.field.message.notify_group_deleted.field_entity_type.yml
config/sync/field.field.message.notify_group_deleted.field_event_executing_user.yml
config/sync/field.field.message.notify_group_deleted.field_referenced_entity_label.yml
config/sync/language/en/message.template.notify_group_deleted.yml
config/sync/message.template.notify_group_deleted.yml
lib/modules/eic_groups/eic_groups.api.php
lib/modules/eic_groups/eic_groups.module
lib/modules/eic_groups/src/Entity/Group.php
lib/modules/eic_messages/eic_messages.module
lib/modules/eic_messages/src/Service/GroupMessageCreator.php
lib/modules/eic_messages/src/Util/NotificationMessageTemplates.php

- Create message notification to send to GO/SA/SCM users when a group is deleted
- Override group entity class since we need to create the message notifications before deleting all the group content
- create custom hook to act before group predelete.
1st test
2nd test

EICNET-2034: Group type notification - group deleted

---

docker-compose.yml
e2e/cypress/integration/global/access-page-check.spec.js

How to test:
PS: /people is a bug at the moment

[EICNET]chore: add access test for organisation/s, people, 404

---

config/sync/migrate_plus.migration.upgrade_d7_user.yml
config/sync/migrate_plus.migration.upgrade_d7_user_to_profile.yml
lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_user.yml
lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_user_to_profile.yml
lib/modules/eic_migrate/src/Plugin/migrate/source/UserWithSMEDIds.php

- Migrate missing user profile taxonomy term fields coming from SMED: **Topics of expertise**, **Topics of interest**, **Regions and Countries**, **Spoken languages** and **Job titles**.
- Fix user roles migration.
- Run a fresh install (**NOTE: DO NOT IMPORT CONTENT FROM FIXTURES**)
- Run `drush mim upgrade_d7_file_image_to_media --execute-dependencies`
- Run `drush mim upgrade_d7_user --update` (15932 should be migrated) -> this migration needs to run twice because we need to update the user profile picture after the files have been migrated. 
- Run `drush mim upgrade_d7_user_to_profile` (15932 should be migrated)
- There is still one remaining taxonomy term field to be migrated in the user profile: **User type**
- There is no piwik administrator role in D9, and therefore all users with …

EICNET-899: Migration of users (phase 2)

---

config/sync/migrate_plus.migration.upgrade_d7_file_document_to_media.yml
lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_file_document_to_media.yml
lib/modules/eic_migrate/src/Plugin/migrate/source/FileCompleteWithSMEDIds.php

- Migrate SMED languages into media documents.
Note that some of the documents don't have a language because it's missing from the document node in D7.

EICNET-284: Migrate "document" media type (phase 2)

---

lib/themes/eic_community/templates/html/html.html.twig

- I add the [Hotwire/turbo](https://turbo.hotwired.dev/handbook/drive) to the website, now we have an Ajax navigation, no reloading of the whole HTML but just the body.

[EICNET] improve Front end navigation

---

lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/DiscussionResultItem.js

[EICNET-2274]fix: Add correct group id to highlight content from

---

composer.lock
composer.patches.json
config/sync/migrate_plus.migration.upgrade_d7_file.yml
config/sync/migrate_plus.migration.upgrade_d7_file_private.yml
lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_file.yml
lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_file_private.yml

- Now file migrations do not fail anymore when some files are missing, they are just ignored

EICNET-2279: Patch Drupal core to ignore missing files instead of fail.

---

lib/modules/eic_messages/modules/eic_message_subscriptions/src/Hooks/FormOperations.php
lib/modules/eic_messages/src/Service/GroupContentMessageCreator.php

[EICNET-2061] Notification fixes related to group & group contents

---

lib/modules/eic_messages/src/Service/RequestMessageCreator.php

- Send notification message about group deletion to the group owner when done via request deletion.

EICNET-2034: Group type notification - group deleted (rework)

---

config/sync/migrate_plus.migration.upgrade_d7_node_complete_document.yml
lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_document.yml

- Migrate regions and countries + moderation state in node document migration.

EICNET-1316: Node 'Document' migration (phase 2)

---

config/sync/core.entity_form_display.node.wiki_page.default.yml
config/sync/core.entity_view_display.node.wiki_page.default.yml
config/sync/core.entity_view_display.node.wiki_page.teaser.yml
config/sync/field.field.node.wiki_page.field_language.yml
config/sync/migrate_plus.migration.upgrade_d7_node_complete_wiki_page.yml
lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_wiki_page.yml

- Migrate regions and countries + related downloads from document nodes + node property "Editable by members".
- Create field_language in Wiki pages + add it to the migration.

EICNET-1321: Node 'Wiki page' migration (phase 2)

---

config/sync/language/en/message.template.notify_delete_request_accepted.yml
config/sync/language/en/message.template.notify_group_deleted.yml
config/sync/message.template.notify_delete_request_accepted.yml
config/sync/message.template.notify_group_deleted.yml
lib/modules/eic_messages/src/Service/RequestMessageCreator.php

- Prevent entity owner from receiving notification about group deletion twice.
1st scenario:
2nd scenario:

EICNET-2034: Group type notification - group deleted (rework 2)

---

composer.lock
composer.patches.json
config/sync/core.entity_form_display.message.stream_event_insert_update.default.yml
config/sync/field.field.message.stream_event_insert_update.field_entity_type.yml
config/sync/field.field.message.stream_event_insert_update.field_group_ref.yml
config/sync/field.field.message.stream_event_insert_update.field_operation_type.yml
config/sync/field.field.message.stream_event_insert_update.field_referenced_node.yml
config/sync/group.role.event-admin.yml
config/sync/group.role.event-owner.yml
config/sync/group.role.group-admin.yml
config/sync/group.role.group-owner.yml
lib/modules/eic_deploy/eic_deploy.install
lib/modules/eic_messages/src/Util/ActivityStreamMessageTemplates.php

- Add missing activity stream message template constant for inserted/updated events;
- Update event activity stream message to include mandatory fields that are needed for showing in the activity stream;
- Apply patch to fix notice when trying to load message subscribers (see https://www.drupal.org/project/message_subscribe/issues/3190511).
Test with QA DB:
Test with fresh install or QA DB:

EICNET-1993: Add Drupal default workflow to all content types (Improvements phase 2)

---

config/sync/migrate_plus.migration.upgrade_d7_comment.yml
lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_comment.yml

- Improve comment migration.
- Some comments have html tags that are not properly decoded when viewing the comments

EICNET-2078: Migration of comments (phase 2)

---

config/sync/migrate_plus.migration.upgrade_d7_file_download_counter.yml
lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_file_download_counter.yml
lib/modules/eic_migrate/src/Plugin/migrate/source/FileDownloadCounter.php

- Implement file download counter migration.

EICNET-1445: File download counter migration

---

lib/modules/eic_groups/eic_groups.install
lib/modules/oec_group_flex/src/OECGroupFlexHelper.php
lib/modules/oec_group_flex/src/Plugin/GroupJoiningMethod/TuGroupMembershipRequest.php

- Add permission to administer membership request when joining method is set to "tu_group_membership_request";
- Create hook_update to update group permissions for old groups.
Using QA DB:
On a fresh install:

EICNET-2315: GO can not access Members Pending page

---

config/sync/migrate_plus.migration.upgrade_d7_node_complete_photoalbum.yml
config/sync/migrate_plus.migration.upgrade_d7_node_photo_to_media.yml
lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_photoalbum.yml
lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_photo_to_media.yml

- Fix field regions and countries in Photo album migration + migrate Photo nodes into media type image.
- There is a field "Document type" in CType gallery which doesn't exist in D7. What should we do?

EICNET-1313: Node 'Photo' migration (improvements)

---

lib/modules/eic_groups/eic_groups.module
lib/modules/eic_groups/eic_groups.services.yml
lib/modules/eic_groups/src/PathautoGenerator.php

- Decorate pathauto generator service in order to prevent generating URL aliases for group content nodes before the group content relationship is created.

EICNET-2281: Not authorized and wrong link in status message after creating gallery

---

config/sync/language/en/message.template.sub_new_comment_on_content.yml
config/sync/language/en/message.template.sub_new_comment_reply.yml
config/sync/message.template.sub_new_comment_on_content.yml
config/sync/message.template.sub_new_comment_reply.yml
lib/modules/eic_messages/modules/eic_message_subscriptions/eic_message_subscriptions.module

Results:
- All users following the content should get a notification for user A's top level comment
- Only authors of parent comments should get a reply notification

[EICNET-2267] 2nd indent on comments also triggers a message for parent comment which is 2 levels higher

---

config/sync/language/en/message.template.notify_contact_user.yml
config/sync/message.template.notify_contact_user.yml

[EICNET-2232]fix: Add correct user link to contact in the email

---

lib/modules/eic_groups/src/Plugin/Block/CommentsFromDiscussionBlock.php

[EICNET-2426]fix: If node delete form route, do not show comments

---

lib/modules/eic_user/src/Hooks/FormAlter.php

- Fix error when trying to invite a deleted user to a group.

EICNET-2387: Group invitation - if user does not exist anymore, it throws 500 error

---

config/sync/group.role.group-anonymous.yml
lib/modules/eic_search/src/Plugin/Block/ActivityStreamBlock.php

[EICNET-2174]feat: Always allow access for latest activity

---

lib/modules/eic_groups/src/Breadcrumb/GroupBreadcrumbBuilder.php

[EICNET-2389]chore: Adapt the breadcrumb for the add group pages

---

config/sync/views.view.admin_groups.yml
lib/modules/eic_admin/eic_admin.links.menu.yml
lib/modules/eic_admin/eic_admin.links.task.yml

[EICNET-2223]chore: Add an organisations list page under community/groups

---

lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Partials/StatisticsFooterResult.js

[EICNET-1086]fix: Remove comment stats on activity stream for documents

---

config/sync/group.role.group-member.yml
lib/modules/eic_groups/eic_groups.module

[EICNET-2386]chore: Remove view members permission from GM role

---

lib/modules/eic_groups/src/Plugin/Block/CommentsFromDiscussionBlock.php

[EICNET-2426]fix: Do not show comments block in edit form

---

config/sync/migrate_plus.migration.upgrade_d7_comment.yml
lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_comment.yml

- I don't know why but when the migration starts, it says 1126 items. Then migration is completed it says `[notice] Processed 1127 items (1125 created, 2 updated, 0 failed, 0 ignored) - done with 'upgrade_d7_comment'`. And when I check the migration result in the UI, it says 1126/1126 imported. But this deosn't the migration to be successful with all content

EICNET-XXXX: Fix comments migration.

---

lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Answer.js
lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/TopAnswer.js

- Remove small dot from FE when viewing a comment that cannot be liked.

EICNET-2422: Comments can not be liked

---

lib/modules/eic_statistics/modules/eic_group_statistics/src/Hooks/EntityOperations.php

- Fix warnings when counting group file statistics during migration.

EICNET-2377: Warning when importing content membership

---

config/sync/context.context.group_discussions_overviews.yml
lib/modules/eic_search/eic_search.services.yml
lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorDiscussion.php
lib/modules/eic_search/src/Search/Sources/DiscussionSourceType.php
lib/modules/eic_statistics/src/StatisticsHelper.php

here is the formula: 3*(number of comments) + number of likes + 2*(number of followers)

[EICNET-2049]feat: Add most active score for discussions

---

lib/modules/eic_groups/src/Access/GroupContentCreateEntityAccessCheck.php

- Deny access to create group content if it's disabled in the group.

EICNET-2463: Error when trying to create a News in a group

---

lib/themes/eic_community/includes/preprocess/form/form-element.inc

- Remove "container-inline" class from select lists.

EICNET-2473: Fix moderation state field in FE forms

---

lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/DiscussionResultItem.js

[EICNET-2342]fix: Add like stats to discussion teaser

---

config/sync/group.role.event-a416e6833.yml
config/sync/group.role.event-admin.yml
config/sync/group.role.event-bf4b46c3a.yml
config/sync/group.role.event-eca6128ca.yml
config/sync/group.role.event-owner.yml
config/sync/group.role.group-a416e6833.yml
config/sync/group.role.group-admin.yml
config/sync/group.role.group-bf4b46c3a.yml
config/sync/group.role.group-eca6128ca.yml
config/sync/group.role.group-owner.yml
config/sync/group.role.organisation-a416e6833.yml
config/sync/group.role.organisation-admin.yml
config/sync/group.role.organisation-bf4b46c3a.yml
config/sync/group.role.organisation-eca6128ca.yml
config/sync/group.role.organisation-owner.yml
config/sync/views.view.eic_group_members.yml
lib/modules/eic_deploy/eic_deploy.install
lib/modules/eic_deploy/eic_deploy.module
lib/modules/eic_groups/eic_groups.group.permissions.yml

- Create new group permission to access members management
- Create hook_update to update all group permissions.
With QA DB
With local DB
- We need to manually trigger the job to run drush updb. CI/CD job `rollback_trigger_updb_qa` -> `Key = UPDB_VERSION, value = 9008`

EICNET-2460: I should not be able to see "manage members" as GM in organizations

---

lib/modules/eic_groups/modules/eic_share_content/eic_share_content.routing.yml
lib/modules/eic_groups/modules/eic_share_content/src/Controller/ShareContentController.php
lib/modules/eic_groups/modules/eic_share_content/src/Service/ShareManager.php
lib/themes/eic_community/includes/preprocess/common.inc

- Prevent members from sharing content in groups with content type plugin disabled;
- Improvements to the share group service and controller.

EICNET-2461: Sharing content to another group should be filtered on the availability of that CT in that specific group

---

lib/modules/eic_groups/modules/eic_group_membership/eic_group_membership.module

- Prevent GO from being removed from its own group.

EICNET-2462: I should not be able to delete myself as a member of a group without transferring ownership

---

lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Partials/StatisticsFooterResult.js

- Remove comments counter from document teaser in overview pages.

EICNET-2341: CT document does not have the comment block listed

---

lib/themes/eic_community/templates/content/node--document--full.html.twig
lib/themes/eic_community/templates/content/node--event--full.html.twig
lib/themes/eic_community/templates/content/node--gallery--full.html.twig
lib/themes/eic_community/templates/content/node--story--full.html.twig
lib/themes/eic_community/templates/content/node--video--full.html.twig

- Fix sidebar flags in node full html twig templates.

EICNET-2477: Content flags in sidebar look bigger than it should

---

config/sync/context.context.node_local_tasks.yml
lib/modules/eic_content/modules/eic_content_book/src/Hooks/EntityOperations.php
lib/themes/eic_community/templates/content/node--book--full.html.twig

- Move manage content dropdown next to the buttons to add book pages.

EICNET-2269: Help and guidance edit button is aligned all the way to the left

---

lib/modules/eic_default_content/src/Generator/BlockContentGenerator.php

- Fix contact box block when generating with fixtures.

EICNET-2141: regression - error when trying to publish a book

---

lib/modules/eic_groups/eic_groups.module
lib/modules/eic_groups/src/Plugin/QueueWorker/GroupContentSearchApi.php
lib/modules/eic_groups/src/Plugin/QueueWorker/ReIndexContentSearchApi.php

[EICNET-2045]feat:Resync also owner of the content when new content

---

config/sync/context.context.group_wiki_page.yml
lib/modules/eic_default_content/eic_default_content.services.yml
lib/modules/eic_default_content/src/Generator/GroupTypeEventGenerator.php
lib/modules/eic_groups/src/EICGroupsHelper.php

- Create fixture to generate global events.
- Fix issue where group book pages could not be returned for group type event when using EICGroupsHelper service.
- Show wiki page navigation in wiki pages from global events

EICNET-2489: Create fixture for Global events

---

lib/modules/eic_groups/src/EICGroupsHelper.php
lib/modules/eic_groups/templates/eic-group-last-activities-members.html.twig
lib/modules/eic_search/src/Plugin/Block/ActivityStreamBlock.php

- Show member names as html links for authenticated users when viewing activity stream;
- Show list of user organisations for each member.

EICNET-2456: Latest members show placeholder [ORGANISATION NAME]

---

config/sync/field.field.media.eic_document.field_body.yml
config/sync/field.field.media.eic_document.field_language.yml

- Make body and language fields optional in media type document.

EICNET-284: Make body and language fields optional in media type document

---

lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-header-block.inc
lib/themes/eic_community/includes/preprocess/content/node--discussion.inc
lib/themes/eic_community/includes/preprocess/content/node--document.inc
lib/themes/eic_community/includes/preprocess/content/node--event.inc
lib/themes/eic_community/includes/preprocess/content/node--gallery.inc
lib/themes/eic_community/includes/preprocess/content/node--video.inc
lib/themes/eic_community/includes/preprocess/events.inc

[EICNET-1173] Do not display the social share button on private contents

---

config/sync/core.entity_form_display.node.document.default.yml
config/sync/field.field.node.document.field_body.yml
config/sync/field.field.node.document.field_language.yml
config/sync/field.storage.node.field_document_type.yml
config/sync/field.storage.node.field_language.yml
config/sync/migrate_plus.migration.upgrade_d7_node_with_group_url_alias_to_path_redirect.yml
lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_with_group_url_alias_to_path_redirect.yml
lib/modules/eic_migrate/src/Plugin/migrate/source/UrlAliasToPathRedirect.php

- Make body and language fields optional in content type document;
- Make language and document type fields unlimited and use entity tree widget in form display;
- Create migration to import node URL redirects (from URL alias) including group prefix from PURL module.

EICNET-1316: Node 'Document' migration (Improvements)

---

config/sync/eic_groups.group_features.eic_groups_anchor_group_events.yml
config/sync/eic_groups.group_features.eic_groups_anchor_members.yml
config/sync/eic_groups.group_features.eic_groups_anchor_news.yml
lib/modules/eic_webservices/src/Utility/SmedTaxonomyHelper.php
lib/modules/oec_group_features/oec_group_features.info.yml
lib/modules/oec_group_features/oec_group_features.services.yml
lib/modules/oec_group_features/src/GroupFeatureHelper.php
lib/modules/oec_group_features/src/Hooks/EntityOperations.php

- Create the Group Permission entity when a new group is created through code (fixtures and webservice)

EICNET-2164: Group permission fix

---

config/sync/mailsystem.settings.yml

- Force using eic_community theme on email templates (ginvite emails were using the admin theme).

EICNET-2031: Group type notification - group invitation (anonymous user notification)

---

lib/modules/eic_default_content/src/Generator/MenuGenerator.php
lib/modules/eic_default_content/src/Generator/OverviewPageGenerator.php

- Fix overview page filters in overview page generator fixture;
- Add missing menu link for organisations overview page.

EICNET-2501: Fix global overview page filters in fixtures

---

config/sync/migrate_plus.migration.upgrade_d7_node_with_group_url_alias_to_path_redirect.yml
lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_with_group_url_alias_to_path_redirect.yml
lib/modules/eic_migrate/src/Plugin/migrate/process/DuplicatedRedirect.php

- Fix URL redirect migration in order to skip duplicated rows instead of throwing an error.
- Create new processor plugin to search for duplicated redirects.

EICNET-2512: Ignore duplicated entries when migrating path redirects from URL alias

---

lib/modules/eic_groups/src/Controller/DiscussionController.php

- Fix issue where tagged users were removed after editing a comment.

EICNET-2513: Editing a comment with user tag makes that user disappear after saving

---

lib/themes/eic_community/includes/preprocess/events.inc
lib/themes/eic_community/includes/preprocess/layout/page.inc

- Fix php error when viewing News, Stories and Event pages without images;

EICNET-2430: Theme: fix breaking erros with missing fields

---

config/sync/context.context.group_wiki_page.yml
config/sync/core.entity_form_display.node.wiki_page.default.yml
config/sync/core.entity_view_display.node.wiki_page.default.yml
config/sync/core.entity_view_display.node.wiki_page.teaser.yml
config/sync/field.field.node.wiki_page.field_comments.yml
config/sync/migrate_plus.migration.upgrade_d7_node_complete_event_site.yml
config/sync/migrate_plus.migration.upgrade_d7_node_complete_group.yml
config/sync/migrate_plus.migration.upgrade_d7_node_complete_organisation.yml
lib/modules/eic_groups/eic_groups.module
lib/modules/eic_groups/src/Plugin/Block/CommentsFromDiscussionBlock.php
lib/modules/eic_groups/templates/eic-group-comments-from-discussion.html.twig
lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_book.yml
lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_event_site.yml
lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_group.yml
lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_organisation.yml
lib/modules/eic_migrate/eic_migrate.services.yml
lib/modules/eic_migrate/src/EventSubscriber/PostMigrationSubscriber.php
lib/modules/eic_migrate/src/Plugin/migrate/source/Book.php

- Create field comments in wiki pages.
- Fix migration of group features.
- Fix book migration source plugin so that it grabs group book pages for all group types.
Migration of groups:
Migration of books:
- ~Run `drush mim upgrade_d7_book --update`~
- ~Make sure wiki pages in global events have the book outline correctly migrated~
Wiki page comments:

EICNET-1321: Node 'Wiki page' migration (improvements phase 3)

---

lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-header-block.inc
lib/themes/eic_community/includes/preprocess/content/node--discussion.inc
lib/themes/eic_community/includes/preprocess/content/node--document.inc
lib/themes/eic_community/includes/preprocess/content/node--gallery.inc
lib/themes/eic_community/includes/preprocess/content/node--news--story.inc
lib/themes/eic_community/includes/preprocess/content/node--video.inc
lib/themes/eic_community/includes/preprocess/events.inc

[EICNET-1173]fix: Take the group budle into account

---

lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/CommentForm.js
lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/TaggedUsers.js

[EICNET-2524]fix: Generate temporary url on select users in tagging comment

---

config/sync/migrate_plus.migration.upgrade_d7_node_complete_photoalbum.yml
config/sync/migrate_plus.migration.upgrade_d7_node_photo_to_media.yml
lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_photoalbum.yml
lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_photo_to_media.yml
lib/modules/eic_migrate/src/Plugin/migrate/source/NodeCompletePhotoalbum.php
lib/modules/eic_migrate/src/Plugin/migrate/source/PhotoalbumPhotoRelationship.php
lib/themes/eic_community/includes/preprocess/content/node--gallery.inc

- Fix image alt text in photo migration.

EICNET-1313: Node 'Photo' migration (improvements phase 3)

---

config/sync/core.entity_form_display.node.discussion.default.yml
config/sync/core.entity_form_display.node.document.default.yml
config/sync/core.entity_form_display.node.event.default.yml
config/sync/core.entity_form_display.node.gallery.default.yml
config/sync/core.entity_form_display.node.news.default.yml
config/sync/core.entity_form_display.node.story.default.yml
config/sync/core.entity_form_display.node.video.default.yml
config/sync/core.entity_form_display.node.wiki_page.default.yml

- Enable and configure entity tree widget for language field in all content types.

EICNET-2519: Enable entity tree widget in language fields

---

lib/modules/eic_flags/src/Hooks/EntityOperations.php

- Prevent entities from being followed during migrations.
Rollback migrations:
Migrate groups/events and follow group flags:
Group:
- D7 -> https://eic.accp.eismea.eu/community7/eic-procurers-day-with-ruag-ag-private-group
- D9 -> `/groups/eic-procurers-day-ruag-ag-private-group`
Make sure the group has 11 followers
Event:
- D7 -> https://eic.accp.eismea.eu/community7/eic-ghg-co-creation-peer-to-peer---2nd-cohort
- D9 -> `/events/eic-ghg-co-creation-peer-peer-2nd-cohort `
Make sure the event has 6 followers

EICNET-2435: Migrate Flags (Improvements)

---

config/sync/field.field.node.gallery.field_document_type.yml

- Just made the document type field optional

EICNET-1318: Make field_document_type optional for galleries.

---

config/sync/migrate_plus.migration.upgrade_d7_node_complete_event.yml
lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_event.yml

- Event CT is using body field unlike the other CTs, as a quick fix I fixed the destination field

EICNET-2294: Fix wrong destiniation field name.

---

config/sync/core.entity_form_display.group.event.default.yml
lib/modules/eic_events/eic_events.module
lib/modules/eic_events/src/Constants/Event.php
lib/modules/eic_events/src/Hooks/EntityOperations.php
lib/modules/eic_events/src/Hooks/FormOperations.php

EICNET-191: Handle paragraphs field for Event GT.

---

composer.lock
composer.patches.json
config/sync/core.entity_form_display.node.story.default.yml
config/sync/core.entity_view_display.node.story.default.yml
config/sync/core.entity_view_display.node.story.mail_teaser.yml
config/sync/core.entity_view_display.node.story.teaser.yml
config/sync/field.field.node.story.field_related_groups.yml
config/sync/field.field.node.story.field_vocab_geo.yml
lib/modules/eic_migrate/src/EventSubscriber/PostMigrationSubscriber.php

- Fix migration of related stories when running the story migration (there were duplicated values because we were updating only the latest revision);
- Fix migration of related groups in stories;
- Create field "Related groups" in Story;
- Fix migration of related groups in groups.
- Migrate related groups from Story into Groups. Before the relationship was done via the story and now is done in the group. The logic has been done but it's commented in the code. We need to decide if it makes sense to migrate the related stories in groups instead of the related groups in stories.
- Fix the body format in story migration. Some users cannot use the full_html format and therefore we need to replace it with filtered_html otherwise the users will not be able to edit the body.
If you are already …

EICNET-1320: Node 'Story' migration (improvements phase 2)

---

lib/modules/eic_admin/src/Form/UpdateAllGroupPermissionsForm.php

- Save group joining methods + visibility + group feature permissions when executing group permissions rebuild process.

EICNET-2285: Rebuild group permission resets Joining method

---

config/sync/message.settings.yml

[EICNET-1743]chore: Include group & group_content within message purge settings

---

lib/modules/eic_migrate/src/EventSubscriber/PostMigrationSubscriber.php

- Enable entity syncronization when saving group visibility + joining methods + features during migration;
- Don't preserve relationships when updating field_related_stories and field_related_groups to avoid duplicated references.

EICNET-1320: Node 'Story' migration (improvements phase 3)

---

config/sync/core.entity_view_display.paragraph.full_text_content.default.yml
config/sync/field.field.paragraph.full_text_content.field_body.yml
lib/themes/eic_community/includes/preprocess/events.inc
lib/themes/eic_community/includes/preprocess/paragraphs/paragraph--full-text-content.inc
lib/themes/eic_community/patterns/compositions/text-block.html.twig
lib/themes/eic_community/templates/group/group--event--full.html.twig
lib/themes/eic_community/templates/paragraphs/paragraph--full-text-content.html.twig

EICNET-191: Allow HTML in full_text_content paragaph body.

---

lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Discussion/Comment.js

- Render discussion comment as html in discussions overview teaser.

EICNET-2563: Comment in discussions overview teaser in not rendered as html

---

lib/modules/eic_groups/src/Controller/DiscussionController.php
lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Answer.js
lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/CollapseActions.js
lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Popup.js
lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/TopAnswer.js

- Validate empty comment on comment edit form.

EICNET-2556: As a user I can create empty comments (Improvements)

---

lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php

- Show pending membership requests link in group management dropdown.

EICNET-2564: Pending membership requests link is not shown in the group management dropdown

---

config/sync/field.field.node.news.field_document_media.yml
config/sync/field.field.node.story.field_document_media.yml
lib/themes/eic_community/includes/preprocess/content/node--news--story.inc

- Allow video medias to be uploaded into field documents in News and Story CTypes.

EICNET-390: Allow video medias in News and Stories documents

---

config/sync/core.entity_form_display.group.event.default.yml

EICNET-2562: Prevent legacy paragraphs to be silently populated.

---

lib/modules/eic_flags/src/Hooks/EntityOperations.php
lib/modules/eic_messages/modules/eic_message_subscriptions/src/EventSubscriber/FlagEventSubscriber.php

- Fix regression in eic_flags module to prevent entities from being followed during migrations.
Rollback migrations:
Migrate groups/events and follow group flags:
Group:
- D7 -> https://eic.accp.eismea.eu/community7/eic-procurers-day-with-ruag-ag-private-group
- D9 -> `/groups/eic-procurers-day-ruag-ag-private-group`
Make sure the group has 11 followers
Event:
- D7 -> https://eic.accp.eismea.eu/community7/eic-ghg-co-creation-peer-to-peer---2nd-cohort
- D9 -> `/events/eic-ghg-co-creation-peer-peer-2nd-cohort`
Make sure the event has 6 followers

EICNET-2435: Migrate Flags (Fix regressions)

---

config/sync/migrate_plus.migration.upgrade_d7_file_image_to_media.yml
lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_file_image_to_media.yml

- Fix migration of alt texts for file images to media migration.

EICNET-226: Migrate "image" media type (Add default alt text)

---

lib/modules/eic_groups/src/Plugin/Block/EICGroupOverviewMessageBlock.php

- Show banner for inviting group members until the GO invites a new user.

EICNET-2004: Group creation status banners - published (Fixes)

---

config/sync/migrate_plus.migration.upgrade_d7_group_old_path_redirect.yml
config/sync/migrate_plus.migration.upgrade_d7_group_path_redirect.yml
lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_group_old_path_redirect.yml
lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_group_path_redirect.yml

- Include events and organisations in group path redirect migrations.
Migrate group redirects:

EICNET-1443: Path redirect migration (improvements)

---

lib/themes/eic_community/sass/compositions/_mainmenu.scss

[EICNET-2590] fix: remove menu search overflow

---

lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/components/WysiswigEditor.js

[EICNET-2558] feat: add Quill link formatter

---

lib/themes/eic_community/sass/components/_messages.scss
lib/themes/eic_community/sass/eic_community.screen.scss

1. As a TU, go to a group
2. Click on Add Content
3. Click on Add Discussion, Document, Event, Gallery, Video (not Wiki)
4. Fill in the required fields of the main page (not the required fields of the tabs)
5. Click on Save
6. Check that "Field is required" is in red

[EICNET-2539] fix: set error text in red

---

lib/themes/eic_community/templates/content/comment--notification-teaser.html.twig

- Remove `<br>` tag between each tagged user in email notification

EICNET-2423: Fix comment notification template

---

lib/modules/eic_groups/modules/eic_share_content/src/Controller/ShareContentController.php
lib/modules/eic_groups/modules/eic_share_content/src/Service/ShareManager.php

- Do not allow users to share draft content;
- Fix issue where group content could be shared multiple times;;

EICNET-2541: Shared event in organisation is not shown

---

lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/Partials/HighlightLink.js

- Hide highlight icon for trusted users if content is not highlighted.

EICNET-1335: Hide highlight icon for trusted users if content is not highlighted

---

lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GroupResultItem.js

Fix group and organisation teasers without an image in react component.

EICNET-2598: Groups without an image in /groups should show the default empty image

---

lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php

EICNET-2603: Add the MAnage invitations link to group dropdown.

---

lib/modules/eic_groups/eic_groups.services.yml
lib/modules/eic_groups/src/EventSubscriber/GinviteSubscriber.php

- Decorate group invite event subscriber so that it avoids showing the invitations message on certain routes;
- Small improvements in code for better performance.

EICNET-2597: Whenever a user accepts his last invitation, he still sees the warning message that an invitation is awaiting his feedback

---

config/sync/field.field.node.news.field_video.yml
config/sync/field.field.node.story.field_video.yml
config/sync/field.field.node.video.field_video_media.yml

- Add alt text to field video in News, Story and Video.

EICNET-2332: Add alt text to field video.

---

composer.lock
composer.patches.json
config/sync/core.entity_form_display.group.organisation.default.yml
config/sync/core.entity_form_display.node.gallery.default.yml
config/sync/core.entity_form_display.node.news.default.yml
config/sync/core.entity_form_display.node.story.default.yml
config/sync/core.entity_form_display.node.video.default.yml
lib/modules/eic_content/eic_content.module
lib/modules/eic_content/src/Plugin/Field/FieldWidget/EntityTreeWidget.php
lib/themes/eic_community/react/components/Field/EntityTree/entrypoint.js
lib/themes/eic_community/react/components/Field/EntityTree/index.js

- Remove html5 validation from all forms;
- Show required field label on entity tree widget react component after user submits the form.

EICNET-2539: No validation error message shown when required fields in inactive tabs are empty

---

lib/modules/eic_groups/src/EICGroupsHelper.php
lib/modules/eic_groups/src/Plugin/Block/EICGroupOverviewMessageBlock.php

[EICNET-2596]fix: Use group bundle when checking for content in groups helper

---

lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/ActivityStreamResultItem.js

- Fix react activity stream result component when activity stream result type is undefined.

EICNET-1438: Fix issue that breaks activity stream list after loading more results

---

lib/modules/eic_messages/modules/eic_message_subscriptions/src/Hooks/FormOperations.php
lib/modules/eic_messages/src/Hooks/FormOperations.php

- Check options "Send notification" and "Post message in the activity stream" by default until there is a published revision.

EICNET-2609: Options to "Send notification" and "Post message in activity stream" should be enabled by default

---

lib/modules/eic_recommend_content/src/Services/RecommendContentManager.php

- Fix issue with allowed html tags that go in the recommendation email (`<br>` was being stripped out).

EICNET-2613: Recommend content - Putting an enter inside comment field does not show up in the email

---

lib/themes/eic_community/includes/preprocess/groups/organisation.inc
lib/themes/eic_community/templates/group/mail_teaser/group--organisation--mail-teaser.html.twig

- Create missing mail_teaser template for organisations that is needed for content recommendation.

EICNET-2621: Cron error when sending notification about recommended organisation

---

lib/themes/eic_community/includes/preprocess/content/node--news--story.inc
lib/themes/eic_community/includes/preprocess/field/field--media--eic-document.inc
lib/themes/eic_community/includes/preprocess/field/field.inc

- Show media language based on media language field or node language field.

EICNET-1160: As a TU I can upload a document when creating a story (Improvements in media language display)

---

lib/themes/eic_community/includes/preprocess/users/user.inc

- Show only operation links the user has access to in user profile page.
- Concerning account deletion, we should discuss this because it will impact all the content in the platform. We need to decide what to do with the content when a user tries to delete his/her account. Should the content be deleted or should we change the author to someone else? What if the user is the owner of a group?

EICNET-2605: TU sees Delete profile button but access to page is not authorized

---

lib/modules/eic_content/modules/eic_content_book/src/Hooks/BookTokens.php

- Fix issue with BookTokens when generating path alias.

EICNET-2612: Fix issue in BookTokens class that is thrown when re-generating URL aliases

---

lib/modules/eic_default_content/eic_default_content.services.yml
lib/modules/eic_default_content/modules/eic_dummy_content/eic_dummy_content.services.yml
lib/modules/eic_default_content/modules/eic_dummy_content/src/Generator/NewsGenerator.php
lib/modules/eic_default_content/modules/eic_dummy_content/src/Generator/StoryGenerator.php
lib/modules/eic_default_content/src/Generator/FragmentGenerator.php
lib/modules/eic_migrate/src/EventSubscriber/PostMigrationSubscriber.php

- Create fixture to generate default fragments;;
- Adds default News and Story disclaimer when migrating from D7.
Test with fresh install

EICNET-1320: Story migration (Set default disclaimer during migration)

---

lib/modules/eic_topics/src/TopicsManager.php

[EICNET]feat: Use expertise field from user instead of topics

---

lib/themes/eic_community/react/components/Block/Overview/Search/Pagination.js

EICNET-2632: fix pagination display

---

lib/modules/eic_groups/src/Hooks/EntityOperations.php

- Fix issue where global event wiki section was not published after publishing the event which was causing TUs, anonymous and GMs to not be able to view the wiki section.

EICNET-2634: Wiki tab is not present for GM (and below) in global events

---

config/sync/group.role.event-a416e6833.yml
config/sync/group.role.event-bf4b46c3a.yml
config/sync/group.role.event-eca6128ca.yml

- You need to rebuild permissions if using an old Event

EICNET-2603: Add missing permissinons in Event GT.

---

lib/themes/eic_community/includes/preprocess/groups/event.inc
lib/themes/eic_community/includes/preprocess/groups/group.inc
lib/themes/eic_community/includes/preprocess/groups/organisation.inc
lib/themes/eic_community/patterns/compositions/event/event.teaser.html.twig
lib/themes/eic_community/patterns/compositions/group/group.teaser.html.twig
lib/themes/eic_community/patterns/compositions/organisation/organisation.teaser.html.twig
lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GlobalEventResultItem.js
lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GroupResultItem.js

- Add moderation state in events overview;
- Send group moderation state to the theme variables so that it can be rendered as a tag.
**As Anonymous and Trusted user:**

EICNET-2204: Group teaser archived status

---

lib/modules/eic_flags/eic_flags.services.yml
lib/modules/eic_flags/src/Service/ArchiveRequestHandler.php
lib/modules/eic_flags/src/Service/DeleteRequestHandler.php
lib/modules/eic_groups/src/Controller/DiscussionController.php

- Re-index discussion when comment is deleted or archived in order to update the latest comment in discussions overview.

EICNET-1334: Add latest comment to discussion teaser on discussions overview

---

config/sync/group.role.event-admin.yml
lib/modules/eic_groups/src/Access/HighlightGroupContentAccessCheck.php
lib/modules/eic_groups/src/EICGroupsHelper.php
lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php

- Allow GO/GA to highlight content in global events.

EICNET-2601: I cannot highlight items in global events

---

config/sync/context.context.drafts.yml
config/sync/context.context.events.yml
config/sync/context.context.groups.yml
lib/modules/eic_default_content/src/Generator/OverviewPageGenerator.php
lib/modules/eic_search/src/Search/Sources/GlobalEventSourceType.php
lib/modules/eic_search/src/Search/Sources/GlobalSourceType.php
lib/modules/eic_search/src/Search/Sources/GroupEventSourceType.php
lib/modules/eic_search/src/Search/Sources/GroupSourceType.php
lib/modules/eic_search/src/Search/Sources/OrganisationSourceType.php
lib/modules/eic_search/src/Search/Sources/Profile/DraftSourceType.php
lib/modules/eic_search/src/Search/Sources/Profile/MyEventsSourceType.php
lib/modules/eic_search/src/Search/Sources/Profile/MyGroupsSourceType.php
lib/modules/eic_search/src/Search/Sources/UserProfile/MyEventsSourceType.php
lib/modules/eic_search/src/Search/Sources/UserProfile/MyGroupsSourceType.php
lib/modules/eic_search/src/Search/Sources/UserProfile/MyOrganisationsSourceType.php
lib/modules/eic_search/src/Service/SolrSearchManager.php
lib/themes/eic_community/includes/preprocess/users/user.inc

- Fix date created and timestamp sorting options for group source types.

EICNET-2457: Fix date created and timestamp sorting options for group source types

---

lib/modules/eic_groups/modules/eic_share_content/src/Service/ShareManager.php

- Fix wrong author name of the user that triggered the shared the content with another group.

EICNET-1091: As a GM I can see when content has been shared inside my group

---

lib/modules/eic_groups/src/Plugin/GroupFeature/GroupLatestActivityStream.php
lib/modules/eic_search/src/Plugin/Block/ActivityStreamBlock.php

- Hide latest members block from activity stream when current user is anonymous.

EICNET-1144: Show latest members on the group activity stream page (Hide for anonymous)

---

config/sync/search_api.index.global.yml

- Removed following entity types from Global search index:
- content_moderation_state
- flagging
- group_permission
- If you use the migrated database, I suggest to run the indexation during the evening as it takes time

EICNET-2626: Remove unneeded entity types from search index.

---

lib/modules/eic_flags/src/Service/ArchiveRequestHandler.php
lib/modules/eic_flags/src/Service/DeleteRequestHandler.php
lib/modules/eic_groups/src/GroupsModerationHelper.php
lib/modules/eic_moderation/src/Constants/EICContentModeration.php

- Fix error when trying to accept archival request for News and Story content types.

EICNET-2636: Accepting request to archive as SA/SCM on news articles within global event returns server error

---

lib/modules/eic_groups/modules/eic_share_content/src/Controller/ShareContentController.php

Either use the migrated database, or make sure you have a user who belongs to multiple groups/events/organisations.
If using the migrated database you can use `drush uli --uid=4`

EICNET-2651: Share modal: share groups alphabetically.

---

lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/ActivityStreamResultItem.js

EICNET-2649: Display the shared content message in activity stream item.

---

lib/modules/eic_webservices/src/Plugin/rest/resource/EicUserResource.php
lib/modules/eic_webservices/src/Plugin/rest/resource/EventResource.php
lib/modules/eic_webservices/src/Plugin/rest/resource/OrganisationResource.php

EICNET-2659: Adapt SMED webservices response in case of existing entity.

---

lib/modules/eic_content/modules/eic_content_book/src/Hooks/EntityOperations.php
lib/modules/eic_content/modules/eic_content_book/src/Plugin/Block/EICBookNavigationBlock.php

- Fix error when trying to access book pages as TU.

EICNET-2660: migrated bookpage challenges generates error with non admin user

---

config/sync/core.entity_form_display.message.notify_content_recommendation.default.yml
config/sync/core.entity_view_display.message.notify_content_recommendation.default.yml
config/sync/core.entity_view_display.message.notify_content_recommendation.mail_body.yml
config/sync/core.entity_view_display.message.notify_content_recommendation.mail_subject.yml
config/sync/field.field.message.notify_content_recommendation.field_receiver_email.yml
config/sync/field.storage.message.field_receiver_email.yml
lib/modules/eic_recommend_content/src/EventSubscriber/FlagEventSubscriber.php
lib/themes/eic_community/includes/preprocess/content/message.inc

- Show user display name in message notification about content recommendation.

EICNET-901: Show user display name in message notification about content recommendation

---

lib/modules/eic_comments/src/Plugin/Block/LoginBlock.php
lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php

EICNET-2643: Make sure to redirect users to the member access page on log in or register CTAs

---

lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/UserGalleryResultItem.js
lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/UserListResultItem.js

EICNET-2686: Remove fake ogranisation from user card.

---

lib/themes/eic_community/includes/preprocess/users/user.inc

EICNET-2684: Remove email address from user profile page.

---

config/sync/field.field.profile.member.field_vocab_geo.yml

[EICNET-2688]fix: Set field to not required for field_vocab_geo

---

lib/modules/eic_user/modules/eic_user_login/src/EventSubscriber/RequestEventSubscriber.php

EICNET-2690: Change incomplete profile message.

---

config/sync/migrate_plus.migration.upgrade_d7_node_complete_organisation.yml
lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_complete_organisation.yml
lib/modules/eic_migrate/src/EventSubscriber/PostMigrationSubscriber.php

- Fix revision timestamp for organisation migration.

EICNET-2695: Migration: missing group features for Events/Organisations

---

lib/themes/eic_community/includes/preprocess/events.inc

- Fix issue where group event sign up link was showing a duplicated URL.

EICNET-2708: [Event] Link to event registration does not work.

---

lib/modules/eic_search/src/Search/Sources/GlobalEventSourceType.php
lib/modules/eic_search/src/Search/Sources/GroupSourceType.php

- Since the overview configuration is content, it has to be manually updated in PROD

EICNET-2720: Switch 'Recently updated' from timestamp to changed time.

---

composer.patches.json

EICNET-2763: Display user display name in authoring information.

---

config/sync/user.role.content_administrator.yml
config/sync/user.role.site_admin.yml

- Allow SA/SCM users to access user interface translation.

EICNET-2776: SA and SCM do not have access to the UIT

---

composer.lock
composer.patches.json
lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobal.php
lib/themes/eic_community/includes/preprocess/content/node--news--story.inc
lib/themes/eic_community/includes/preprocess/layout/page.inc

- Apply patch to fix issue with default publication date when node is not published;
- Show the same date format for News and Story CTypes.

EICNET-2717: Stories - Posting date is wrong by default

---

lib/modules/eic_user/eic_user.module
lib/modules/eic_user/src/Hooks/FormAlter.php
lib/modules/eic_user/src/UserHelper.php

- Disable job title field for SMED users.

EICNET-2734: [User profile] A trusted user should be able to edit his role.

---

config/sync/group.role.organisation-dcb2f93df.yml
config/sync/group.role.organisation-outsider.yml
lib/modules/eic_groups/eic_groups.install

- Remove group permission "Join group" from outsiders and trusted users in group type organisation;
- Create hook_update to remove group permission from existing organisations.

EICNET-2766: [Organisation] Trusted should not join organisation without approaval of the admnistrator/owner

---

lib/modules/eic_search/src/Search/Sources/NewsStorySourceType.php

- Add extra pre filter in NewsStorySourceType used in global overview of News and Stories in order to discard News and Stories that belong to groups.

EICNET-2778: [Event] News and stories created within an event should only be visible to the member of that event

---

lib/modules/eic_groups/src/Form/BulkGroupInvitationConfirm.php

ICNET-2784: Make sure we don't discloe users email address when inviting to groups.

---

lib/modules/eic_contact/eic_contact.module

EICNET-2783: Mimic Drupal\contact\MailHandler::sendMailMessages() logic to handle anonymous users.

---

config/sync/core.entity_form_display.node.news.default.yml

[EICNET-2768]feat: Hide related groups in news

---

lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/ActivityStreamResultItem.js

EICNET-2793: Fix activity stream item URLs.

---

config/sync/user.role.content_administrator.yml
config/sync/user.role.site_admin.yml

EICNET-2829: Add taxonomy overview page access permission.

---

lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobal.php
lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorVisibility.php

- Do not show group content of pending groups in global search (including content inside organisations).

EICNET-2779: [Event] A none logged user should not see pending events

---

config/sync/views.view.admin_groups.yml

EICNET-2797: Disable visibility sorting.

---

lib/modules/eic_webservices/src/Utility/EicWsHelper.php

EICNET-2802: Make sure to include the base_path in sub-requests.

---

lib/modules/eic_search/src/Search/Sources/NewsStorySourceType.php
lib/modules/eic_topics/src/Plugin/Block/TopicStatisticsBlock.php

- Add cache url.path as cache context in topic statistics block.
- Fix issue where News content type was not shown in Stories overview page.

EICNET-2798: Filters on a the topics do not point to correct taxonomy

---

lib/modules/eic_search/src/Plugin/search_api/processor/GroupAccessContent.php
lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobal.php
lib/modules/eic_search/src/Service/SolrSearchManager.php

- Allow group members to view their own groups;
- Fix issue where draft content was shown for non authors in group overviews and global overview.

EICNET-2850: [Groups] TU cannot see created group in groups list

---

lib/modules/eic_content/eic_content.module
lib/modules/eic_flags/src/Service/ArchiveRequestHandler.php
lib/modules/eic_flags/src/Service/DeleteRequestHandler.php

- Removes certain local tasks links depending on the current route and moderation status.

EICNET-2715: [Stories] Manage content display wrong information for draft

---

lib/modules/eic_flags/src/Service/ArchiveRequestHandler.php

- Fix issue with method isPublished() from ArchiveRequestHandler when checking if user entity is published.

EICNET-2715: [Stories] Manage content display wrong information for draft (Rework)

---

lib/modules/eic_recommend_content/templates/eic-recommend-content-link.html.twig

- Render data attribute translations in recommend content link as encoded json.

EICNET-900: Recommend content (small fixes)

---

lib/modules/eic_recommend_content/src/Services/RecommendContentManager.php

EICNET-900: Fix endpoint URL in recommend content data attributes.

---

lib/modules/eic_groups/src/EICGroupsHelper.php
lib/modules/eic_webservices/src/Plugin/rest/resource/EventResource.php
lib/modules/eic_webservices/src/Plugin/rest/resource/GroupResourceBase.php
lib/modules/eic_webservices/src/Plugin/rest/resource/OrganisationResource.php

- Set default group features when creating a global event or organisation via webservices.

EICNET-2857: [Organisation] created organisation miss of the default features

---

config/sync/eic_admin.action_forms.ginvite.invitation.bulk.confirm.yml
config/sync/eic_admin.action_forms.ginvite.invitation.bulk.yml

- Fix group type name in page title of group users invitation form.

EICNET-2765: [Organsiation] inviting a user page replace reference to groups with "Organsiation"

---

lib/modules/eic_messages/modules/eic_message_subscriptions/src/Hooks/FormOperations.php

- Change label text of checkbox to send notification.
- Add description text to the checkbox to send notification.

EICNET-2865: Change the "Send notification" checkbox label and add field description

---

lib/themes/eic_community/includes/preprocess/content/message.inc

- Add missing condition to check if field_sender references anonymous user when preprocessing global contact messages.

EICNET-2875: mails from contact form are stuck in the queue

---

lib/modules/oec_group_flex/oec_group_flex.install
lib/modules/oec_group_flex/oec_group_flex.services.yml
lib/modules/oec_group_flex/src/GroupJoiningMethodDatabaseStorage.php
lib/modules/oec_group_flex/src/GroupJoiningMethodDatabaseStorageInterface.php
lib/modules/oec_group_flex/src/GroupJoiningMethodRecord.php
lib/modules/oec_group_flex/src/GroupJoiningMethodRecordInterface.php
lib/modules/oec_group_flex/src/OECGroupFlexGroupDecorator.php
lib/modules/oec_group_flex/src/OECGroupFlexGroupSaverDecorator.php
lib/modules/oec_group_flex/src/Plugin/GroupJoiningMethod/TuCloseMethod.php

- Create new joining method plugin "tu_close_method";
- Create new table schema to save information about the group joining method;
- Create hook update to update joining method for existing groups.
Using PROD DB

EICNET-2745: Closed joining method for events

---

lib/themes/eic_community/includes/preprocess/groups/group.inc

EICNET-2697: Do not link users to their profile for anonymous users.

---

config/sync/cas.settings.yml

EICNET-2823: Don't assign roles upon cas user registration.

---

lib/modules/eic_migrate/src/Plugin/migrate/source/UrlAliasToPathRedirect.php

- Run `drush mim upgrade_d7_node_with_group_url_alias_to_path_redirect`

EICNET-2856: Take into account the user of group prefix in the alias migration

---

lib/themes/eic_community/includes/preprocess/groups/organisation.inc

EICNET-2438: Always display News and Events views in Organisation GT.

---

lib/modules/eic_content/src/Constants/HelpAndGuidance.php
lib/modules/eic_groups/src/Plugin/Block/EICGroupOverviewMessageBlock.php

- Created a new `Drupal\eic_content\Constants\HelpAndGuidance` class for related constants

EICNET-1138: Change the link to help and guidance.

---

config/sync/views.view.eic_group_invitations.yml
config/sync/views.view.eic_group_pending_members.yml
config/sync/views.view.group_invitations.yml
lib/modules/eic_groups/eic_groups.services.yml
lib/modules/eic_groups/modules/eic_group_membership/eic_group_membership.module
lib/modules/eic_groups/src/Access/GroupViewsModerationStatePermissionChecker.php
lib/modules/eic_groups/src/Form/BulkGroupInvitationConfirm.php
lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
lib/modules/eic_groups/src/Plugin/views/access/EICGroupPermissionWithContentModeration.php
lib/modules/eic_groups/src/Routing/RouteSubscriber.php

- Create custom views access plugin to restrict access to based on the group permission and moderation state;
- Apply views custom access plugin in manage members page and manage invitations page;
- Create custom view EIC Group Invitations and replace it with the default one provided by the group module.

EICNET-2667: I can still manage members/memberships/invitations of a blocked group

---

lib/modules/eic_groups/eic_groups.install

EICNET-2882: Remove obsolete News group menu items.

---

config/sync/group.type.event.yml
lib/modules/oec_group_flex/src/OECGroupFlexGroupSaverDecorator.php

- Enable closed joining method in Global events + Fix error when saving private groups.

EICNET-2745: Closed joining method for events (Rework)

---

lib/modules/eic_overviews/src/GlobalOverviewPages.php

Notice: Undefined variable: bundles in Drupal\eic_overviews\GlobalOverviewPages->getGlobalOverviewPageOperations() 
(line 161 of /app/lib/modules/eic_overviews/src/GlobalOverviewPages.php).
`)

EICNET-2771: Fix uninitialised variables on global overviews.

---

lib/themes/eic_community/react/components/Block/NotifManagement/index.js

- Show empty message in manage email notifications page if there are no results by default.

EICNET-2433: Empty state of [My settings][Email notifications][Your %group_type% notifications] missing

---

lib/modules/eic_groups/src/Breadcrumb/GroupBreadcrumbBuilder.php
lib/modules/eic_groups/src/EICGroupsHelper.php

- Fix breadcrumb when viewing wiki page of a global event.

EICNET-2637: When going to the wiki tab inside a global event the breadcrumbs say group

---

lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-header-block.inc
lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GlobalEventResultItem.js

[EICNET-2368]chore: Display visibility label for events

---

lib/modules/eic_webservices/src/Plugin/rest/resource/EicUserResource.php
lib/modules/eic_webservices/src/Plugin/rest/resource/EicUserResourceBase.php

EICNET-2898: Validate user entity and send out custom message if not valid.

---

lib/modules/eic_groups/src/Controller/DiscussionController.php
lib/modules/eic_groups/src/Plugin/Block/CommentsFromDiscussionBlock.php
lib/modules/eic_moderation/src/ModerationHelper.php
lib/modules/eic_moderation/src/Service/ContentModerationManager.php

- Hide comments block and access to block api endpoints when content is in draft or unpublished state.

EICNET-2758: [Event] No one should be allowed to comment on a draft story

---

composer.lock
composer.patches.json
lib/modules/eic_contact/eic_contact.module

- Apply patch to keep "Sender" and "Reply-To" headers when sending email via smtp module.

EICNET-2899: contact form - sent mails - the reply message from is missing some information

---

config/sync/eic_admin.action_forms.group_membership_leave.yml
lib/modules/eic_groups/modules/eic_group_membership/eic_group_membership.module
lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-header-block.inc

- Update action form text for the group membership leave form;
- Update group operation label with neutral labels.

EICNET-2746: Relabel references to "group" with neutral labels

---

lib/modules/eic_messages/eic_messages.install
lib/modules/eic_messages/eic_messages.install.inc
lib/modules/eic_messages/eic_messages.module
lib/modules/eic_messages/src/Hooks/EntityOperations.php

- Create hook_update to delete activity stream messages with references to non-existing content.

EICNET-1921: Activity stream shows undefined link for deleted content

---

lib/modules/eic_search/eic_search.module
lib/modules/eic_search/eic_search.services.yml
lib/modules/eic_search/src/Search/DocumentProcessor/DocumentProcessor.php
lib/modules/eic_search/src/Search/DocumentProcessor/DocumentProcessorInterface.php
lib/modules/eic_statistics/src/Hooks/CronOperations.php
lib/modules/eic_statistics/src/NodeStatisticsDatabaseStorage.php
lib/modules/eic_statistics/src/StatisticsHelper.php

- Save node ID in a state cache whenever there is an update on the view counter so that we can re-index the node at a later stage with cron.

EICNET-2901: Views count in stories not working properly

---

lib/themes/eic_community/includes/preprocess/groups/group.inc
lib/themes/eic_community/patterns/compositions/extended-list/extended-list-item.html.twig

- Fix group header read more anchor.

EICNET-2876: Group description header read more anchor is not working

---

config/sync/context.context.book_pages.yml
config/sync/context.context.group_wiki_page.yml
lib/modules/eic_content/modules/eic_content_book/src/Hooks/EntityOperations.php
lib/modules/eic_content/modules/eic_content_book/src/Hooks/Preprocess.php
lib/modules/eic_content/modules/eic_content_book/src/Plugin/Block/EICBookNavigationBlock.php
lib/modules/eic_content/src/EICContentHelper.php
lib/modules/eic_content/src/EICContentHelperInterface.php
lib/modules/eic_groups/eic_groups.module
lib/modules/eic_messages/modules/eic_message_subscriptions/src/Hooks/FormOperations.php
lib/modules/eic_messages/src/Hooks/EntityAdminUpdateNotifier.php
lib/modules/eic_messages/src/Hooks/FormOperations.php
lib/modules/eic_messages/src/Service/CommentMessageCreator.php

- Refactor getGroupContentByEntity() method from EICContentHelper service.
- Refactor code using the method getGroupContentByEntity().

EICNET-2074: Improve method to get group content from entity

---

lib/modules/eic_groups/eic_groups.module

- Include group title in node page metatags.

EICNET-2615: Add parent_group_title in the meta & OG title of nodes within a group

---

config/sync/core.extension.yml

- Disable module group_outsider_in.

EICNET-2934: [Group access] Issue with groups access

---

config/sync/field.field.profile.member.field_vocab_topic_interest.yml
lib/modules/eic_user/eic_user.module
lib/modules/eic_user/src/Hooks/FieldWidgetOperations.php

- Remove match limit label from entity tree widget fields in user profile form.

EICNET-2739: [User profile] remove confusing text

---

lib/modules/eic_messages/modules/eic_message_subscriptions/src/Hooks/FormOperations.php

- Avoid triggering duplicated notification message about content of interest.

EICNET-2929: Duplicated item in news and stories in the email digest

---

lib/modules/eic_groups/eic_groups.install

EICNET-2924: Add missing 'edit memberships' permission.

---

config/sync/oe_authentication.settings.yml

we will enable 2FA for EU Login at that date!

EICNET-2949: Enable 2FA with EUlogin - Do NOT merge before 20/12/2022

---

lib/modules/eic_contact/eic_contact.module

Issue EICNET-2899: AWS SES is now checking if it can send emails in name of the sender domain

Release/0.49.4 - HotFix - disable overwiting of smtp sender field.

---

lib/modules/eic_groups/src/EICGroupsHelper.php

Allow entity to be null in getGroupFromContent so comments can work again with flagging

[EICNET-2963]fix: Avoid 500 when comment from discussion = 0

---

web/sites/default/default.settings.k8s.php

- [[EICINFRA-877](https://github.com/EIC-EA/EIC-community-D8/pull/2148/commits/b1c48685c12a7753c4aad09ab939d67cb9c4ade2)] - set registration url via environment parameter
- [[EICNET-2977](https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-2977)] - newly created  events / groups are not accessible 
[EIC-EA/hotfix/EICNET-readd-permissions](https://github.com/EIC-EA/EIC-community-D8/pull/2148/commits/3e1df06e80d0354f2858cac9f6dc7cde995be51f)

Release 1.51.2 - HF3 - fixing public access for groups / events + registration url

---

lib/modules/eic_user/modules/eic_user_login/src/EventSubscriber/CasEventSubscriber.php

- Remove duplicated status message when invalid user logs in via CAS.
- Hide the H3 tag in the status message and push the text next to the icon

EICNET-2824: Remove duplicated status message

---

lib/themes/eic_community/includes/preprocess/layout/page.inc
lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/StoryResultItem.js

EICNET-2845: Relabel restricted stories to private.
