EIC-EA/EIC-community-D8

config/sync/facets.facet_source.search_api__views_page__group_overviews__search_group.yml, config/sync/facets_summary.facets_summary.group_search_summary.yml
* Set "Access permission" for Group - Overviews > Search group page to "Unrestricted" (group permission doesn't work yet)
* "No results found." should not be displayed when there are search results
=> EICNET-767: Fix search group no results found

config/sync/context.context.groups_overview.yml, lib/themes/eic_community/includes/alter/theme_suggestions/views.inc, lib/themes/eic_community/sass/compositions/_filter-sidebar.scss, lib/themes/eic_community/templates/facets/facets-item-list--checkbox--groups-regions-countries.html.twig, lib/themes/eic_community/templates/facets/facets-item-list--checkbox--groups-topics.html.twig, lib/themes/eic_community/templates/facets/facets-item-list--checkbox--groups.html.twig, lib/themes/eic_community/templates/facets/facets-summary-item-list--groups-summary.html.twig, lib/themes/eic_community/templates/views/views-view--teaser-overview.html.twig
Filters styling
Teasers styling
=> EICNET-667: Started matching drupal output with storybook.

config/sync/context.context.homepage.yml, lib/modules/eic_homepage/config/install/context.context.homepage.yml, lib/themes/eic_community/templates/layout/page--front.html.twig
* Add blocks to homepage context: stay up to date, follow us, eic twitter feed, facts & figures
=> EICNET-553: Update context for the logged in homepage

lib/themes/eic_community/includes/preprocess/users/user.inc
```
TypeError: Argument 1 passed to Drupal\eic_community\ValueObject\ImageValueObject::fromImageItem() must be an instance of Drupal\image\Plugin\Field\FieldType\ImageItem, instance of Drupal\Core\Field\Plugin\Field\FieldType\EntityReferenceItem given, called in /var/www/html/lib/themes/eic_community/includes/preprocess/users/user.inc on line 60 in Drupal\eic_community\ValueObject\ImageValueObject::fromImageItem() (line 137 of /var/www/html/lib/themes/eic_community/src/ValueObject/ImageValueObject.php)
#0 /var/www/html/lib/themes/eic_community/includes/preprocess/users/user.inc(60): Drupal\eic_community\ValueObject\ImageValueObject::fromImageItem(Object(Drupal\Core\Field\Plugin\Field\FieldType\EntityReferenceItem))
#1 /var/www/html/lib/themes/eic_community/includes/preprocess/groups/group- …
```
=> EICNET-658: Fix user teaser display

lib/modules/eic_comments/src/Plugin/Block/LoginBlock.php, lib/themes/eic_community/includes/preprocess/blocks/block--login-block.inc
Improved code style regarding the render array.
=> EICNET-637: fix code style render array

config/sync/context.context.group_wiki_overview.yml, config/sync/context.context.group_wiki_page.yml, config/sync/context.context.groups_overview.yml, config/sync/core.entity_view_display.node.discussion.default.yml, config/sync/core.entity_view_display.node.document.default.yml, config/sync/facets.facet.discussions_regions_countries.yml, config/sync/facets.facet.discussions_topics.yml, config/sync/facets.facet.discussions_type.yml, config/sync/facets.facet.groups_regions_countries.yml, config/sync/facets.facet.groups_topics.yml, config/sync/facets.facet.members_job_title.yml, config/sync/facets.facet.members_languages.yml, config/sync/facets.facet.members_topics_of_expertise.yml, config/sync/facets.facet.members_topics_of_interest.yml, config/sync/facets.facet.search_content_type.yml, config/sync/facets.facet.search_group_content_type.yml, config/sync/facets.facet.search_group_regions_countries.yml, config/sync/facets.facet.search_group_topics.yml, config/sync/facets.facet.search_regions_countries.yml, config/sync/facets.facet.search_topics.yml
- Removed duplicated keys in entity view display configurations;
- Fix configurations from previous merges.
=> Bugfix: Duplicated keys in entity view display configurations

lib/themes/eic_community/data/comments.data.js, lib/themes/eic_community/patterns/components/author.html.twig, lib/themes/eic_community/patterns/compositions/comment/comment-overview.html.twig, lib/themes/eic_community/patterns/compositions/editorial-article.html.twig, lib/themes/eic_community/patterns/compositions/featured-contributors.html.twig, lib/themes/eic_community/sass/components/_author.scss, lib/themes/eic_community/sass/compositions/_comment-form.scss, lib/themes/eic_community/sass/compositions/_comment-overview.scss, lib/themes/eic_community/sass/compositions/_comment.scss, lib/themes/eic_community/sass/compositions/_editorial-article.scss, lib/themes/eic_community/sass/compositions/_featured-list.scss, lib/themes/eic_community/styleguide/components/author.docs.mdx, lib/themes/eic_community/styleguide/components/author.stories.js, lib/themes/eic_community/styleguide/compositions/comments.stories.js, lib/themes/eic_community/styleguide/compositions/featured-contributors.stories.js
This PR implements the Storybook example for the featured contributors within the comment overview.
It can be viewed within `Storybook > Compositions > Featured Contributors > Grid` or `Storybook > Compositions / Comments / Overview`
=> EICNET-842: Implements collapsible contributors within comment overview.

lib/themes/eic_community/includes/alter/theme_suggestions/table.inc, lib/themes/eic_community/templates/form/input--submit.html.twig, lib/themes/eic_community/templates/tables/table--with-fields.html.twig
This change will fix the form field that use a table theme, like topics and countries & regions.
It wil also fix submitting the forms. 
I tested the submit change as a trusted user with the add group form, /group/add/group. And adding a discussion to the group.
I tested the topic fields on the two previous forms and also on the member tab of the user.
The field layout of the forms is still messy.
=> EICNET-806: Fixed frontend forms

config/sync/pathauto.pattern.group_group.yml, lib/modules/eic_groups/src/Hooks/GroupTokens.php
Test:
- Create a group with a long title (40+ characters)
- Check that the group title in the alias is trunctaed after 40 characters
=> EICNET-1024: Create a token for truncated group titles.

lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php, lib/modules/oec_group_flex/src/OECGroupFlexHelper.php, lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-header-block.inc
- Show link "Log in to join group" when anonymous user views a public group page with **Open** joining method;
- Show link "log in to request membership" when anonymous user views a public group page with **Request (for trusted users)** joining method;
Test for "Open" joining method:
Test for "Request (for trusted users)" joining method:
=> EICNET-1039/EICNET-1042: As an anonymous user I can click on "log in to join group" or "log in to request membership"

composer.lock, composer.patches.json, config/sync/core.entity_form_display.flagging.request_archive_comment.default.yml, config/sync/core.entity_form_display.flagging.request_archive_content.default.yml, config/sync/core.entity_form_display.flagging.request_archive_group.default.yml, config/sync/core.entity_form_display.flagging.request_delete_comment.default.yml, config/sync/core.entity_form_display.flagging.request_delete_content.default.yml, config/sync/core.entity_form_display.flagging.request_delete_group.default.yml, config/sync/core.entity_view_display.flagging.request_archive_comment.default.yml, config/sync/core.entity_view_display.flagging.request_archive_content.default.yml, config/sync/core.entity_view_display.flagging.request_archive_group.default.yml, config/sync/core.entity_view_display.flagging.request_delete_comment.default.yml, config/sync/core.entity_view_display.flagging.request_delete_content.default.yml, config/sync/core.entity_view_display.flagging.request_delete_group.default.yml, config/sync/field.field.flagging.request_archive_comment.field_request_closed_date.yml, config/sync/field.field.flagging.request_archive_content.field_request_closed_date.yml, config/sync/field.field.flagging.request_archive_group.field_request_closed_date.yml, config/sync/field.field.flagging.request_delete_comment.field_request_closed_date.yml, config/sync/field.field.flagging.request_delete_content.field_request_closed_date.yml, config/sync/field.field.flagging.request_delete_group.field_request_closed_date.yml, config/sync/field.storage.flagging.field_request_closed_date.yml, config/sync/views.view.closed_requests.yml, lib/modules/eic_flags/eic_flags.module, lib/modules/eic_flags/src/Form/ListBuilderFilters.php, lib/modules/eic_flags/src/Service/AbstractRequestHandler.php
=> Feature/EICNET-1018: Create a view to display handled requests

config/sync/user.role.content_administrator.yml, lib/modules/eic_flags/eic_flags.module, lib/modules/eic_flags/eic_flags.permissions.yml, lib/modules/eic_flags/eic_flags.services.yml, lib/modules/eic_flags/src/Access/RequestAccessCheck.php, lib/modules/eic_flags/src/Plugin/GroupContentEnabler/RequestArchival.php, lib/modules/eic_flags/src/Plugin/GroupContentEnabler/RequestDelete.php, lib/modules/eic_flags/src/Routing/EntityRequestRouteProvider.php, lib/modules/eic_flags/src/Service/AbstractRequestHandler.php, lib/modules/eic_flags/src/Service/HandlerInterface.php, lib/modules/eic_groups/src/EICGroupsHelper.php
=> Feature/EICNET-1032: As a TU I can't request deletion for a group

lib/themes/eic_community/includes/preprocess/layout/page.inc
The footer content was not visible. This PR makes the footer content visible.
caveat:
- the body from the Footer - site info block has to be plain text.
=> EICNET-1023: Added footer content to storybook styling.

config/sync/flag.flag.follow_group.yml
- You should now see the follow group flag with a counter
=> EICNET-1061: Change the link type for the follow group flag.

config/sync/core.entity_form_display.message.notify_archived_republished.default.yml, config/sync/core.entity_view_display.message.notify_archived_republished.default.yml, config/sync/core.entity_view_display.message.notify_archived_republished.mail_body.yml, config/sync/core.entity_view_display.message.notify_archived_republished.mail_subject.yml, config/sync/field.field.message.notify_archived_republished.field_message_subject.yml, config/sync/field.field.message.notify_archived_republished.field_referenced_entity_label.yml, config/sync/field.storage.message.field_referenced_entity_label.yml, config/sync/language/en/message.template.notify_archived_republished.yml, config/sync/message.template.notify_archived_republished.yml, config/sync/user.role.content_administrator.yml, lib/modules/eic_flags/eic_flags.links.menu.yml, lib/modules/eic_flags/eic_flags.module, lib/modules/eic_flags/eic_flags.permissions.yml, lib/modules/eic_flags/src/Controller/FlagRequestController.php, lib/modules/eic_flags/src/FlaggedEntitiesListBuilder.php, lib/modules/eic_flags/src/Form/ListBuilderFilters.php, lib/modules/eic_flags/src/Hooks/EntityOperations.php, lib/modules/eic_flags/src/Routing/RequestRoutes.php, lib/modules/eic_messages/eic_messages.module, lib/modules/eic_messages/src/Hooks/EntityUpdate.php
This PR introduce the following changes:
- A publish button for unpublished contents on the handled archive requests list
- Allow sending notification to authors when an archived content gets published again
=> Feature/EICNET-893: Allow republishing an archived content + send notification when a content is unarchived

lib/themes/eic_community/includes/preprocess/layout/page.inc
Test:
Check you can click on the site header logo
=> EICNET-1073: Add link to site header logo

config/sync/language.content_settings.taxonomy_term.funding_source.yml, config/sync/taxonomy.vocabulary.funding_source.yml, lib/modules/eic_default_content/content/taxonomy_term/06ebe2d2-0d23-43a7-b38f-1a70cea0edbd.yml, lib/modules/eic_default_content/content/taxonomy_term/538468b5-718b-4e63-8846-323487bbf39c.yml, lib/modules/eic_default_content/content/taxonomy_term/589c3dc4-6e6c-4836-9630-0850f1c4cee7.yml, lib/modules/eic_default_content/content/taxonomy_term/6c4a40ca-d17b-44bd-828f-fbf0f28d99b7.yml, lib/modules/eic_default_content/content/taxonomy_term/8f482971-901d-4e8c-9a3f-4e7d171f6a41.yml, lib/modules/eic_default_content/content/taxonomy_term/eec3f017-d51e-4bfa-9abb-1fb3f7f2b1de.yml
- New taxonomy vocabular "Funding source";
- Export default taxonomy terms for vocabulary "Funding source";
=> EICNET-1095: Implement taxonomy "funding source"

config/sync/metatag.metatag_defaults.node__story.yml, lib/themes/eic_community/includes/preprocess/content/node--news--story.inc, lib/themes/eic_community/templates/content/node--story--full.html.twig
=> [EICNET-1107] As an anonymous user I can share a public story on social media

config/sync/user.role.content_administrator.yml, config/sync/user.role.site_admin.yml, lib/modules/eic_groups/eic_groups.group.permissions.yml, lib/modules/eic_groups/eic_groups.services.yml, lib/modules/eic_groups/src/Access/OrphanGroupContentAccessCheck.php, lib/modules/eic_groups/src/ForbiddenOrphanContentTypes.php, lib/modules/eic_groups/src/Routing/RouteSubscriber.php
Disable access to the node.add route for wiki_pages and discussion bundles
=> [EICNET-957] A a site user I'm not allowed to create group content outside of a group

lib/modules/oec_group_flex/src/Plugin/RestrictedGroupVisibilityBase.php
- Remove permissions to view group contents from outsider and anonymous roles when the group privacy changes from public to private or restricted.
=> EICNET-1157: Group content still accessible to anonymous users after visibility change to "private"

config/sync/flag.flag.like_content.yml, config/sync/flag.flag.recommend_group.yml
- Update flag labels ("Like").
=> EICNET-997: As an anonymous user I can like a public story

lib/themes/eic_community/includes/preprocess/content/node--news--story.inc, lib/themes/eic_community/includes/preprocess/paragraphs/paragraph--contributor.inc
Tests:
* Create story
* Don't add image caption
* Add external contributor with an email address
* Go to the story as anonymous
* _You should see no image caption_
* _You should se no email icon for the contributor_
=> Fixed bugs found by Q&A.

lib/themes/eic_community/templates/navigation/menu--main.html.twig
Tests:
* You should see the search form in the main menu on all the pages.
* When you add input in the search field, you should go to the search page and see your input in the search input of that page.
=> EICNET-1151: Added search form to main menu.

config/sync/context.context.members_overview.yml
=> [EICNET-841]fix: Change template to gallery instead of list

config/sync/context.context.members_overview.yml, config/sync/search_api.index.global.yml, lib/modules/eic_search/src/Search/Sources/UserGallerySourceType.php, lib/modules/eic_search/src/Search/Sources/UserListSourceType.php
=> [EICNET-580]feature: Add facets languages and roles + sorts fort last active user

config/sync/core.entity_form_display.fragment.banner.default.yml, config/sync/core.entity_form_display.fragment.disclaimer.default.yml, config/sync/core.entity_form_display.fragment.fact_figure.default.yml, config/sync/core.entity_view_display.fragment.banner.default.yml, config/sync/core.entity_view_display.fragment.disclaimer.default.yml, config/sync/core.entity_view_display.fragment.fact_figure.default.yml, config/sync/field.field.fragment.banner.field_body.yml, config/sync/field.field.fragment.disclaimer.field_body.yml, config/sync/field.field.fragment.fact_figure.field_body.yml, config/sync/field.storage.fragment.field_body.yml
- Replace fragments plain body field with formatted body field.
=> EICNET-976: As an anonymous user I can see the disclaimer of this story

config/sync/context.context.search.yml, config/sync/search_api.index.global.yml, lib/modules/eic_search/eic_search.module, lib/modules/eic_search/src/Controller/SolrSearchController.php, lib/modules/eic_search/src/Search/Sources/GlobalSourceType.php, lib/themes/eic_community/react/components/Block/Overview/Search/Field/SearchField.js, lib/themes/eic_community/react/components/Block/Overview/Search/Sidebar.js, lib/themes/eic_community/react/components/Block/Overview/entrypoint.js, lib/themes/eic_community/react/components/Block/Overview/index.js
Implement spellcheck on all overview search
How to test :
=> [EICNET-1175]feature: Add spellcheck on search and more filters

composer.json, composer.lock, config/sync/views.view.scheduler_scheduled_content.yml
- Update Drupal core (from 9.2.1 to 9.2.3);
- Update contrib modules: context, node_read_time, scheduler, search_api.
=> EICNET-1176: Maintenance sprint 21

config/sync/core.entity_form_display.node.document.default.yml, config/sync/field.storage.node.field_document_media.yml
=> [EICNET-1221] chore: Allow multiple media in Document's field_document_media

config/sync/flag.flag.highlight_content.yml, config/sync/group.role.group-admin.yml, config/sync/group.role.group-owner.yml, config/sync/search_api.index.global.yml, config/sync/system.action.flag_action.highlight_content_flag.yml, config/sync/system.action.flag_action.highlight_content_unflag.yml, lib/modules/eic_groups/eic_groups.group.permissions.yml, lib/modules/eic_groups/eic_groups.routing.yml, lib/modules/eic_groups/eic_groups.services.yml, lib/modules/eic_groups/src/Access/HighlightGroupContent.php, lib/modules/eic_groups/src/Access/HighlightGroupContentAccessCheck.php, lib/modules/eic_groups/src/Controller/GroupOperationsController.php, lib/modules/eic_search/eic_search.module
=> [EICNET-1191] feat: Add a permission and endpoint to highlight group content

lib/modules/eic_search/src/Controller/SolrSearchController.php, lib/modules/eic_search/src/Service/SolrDocumentProcessor.php, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GroupResultItem.js
=> [EICNET-1184]feature: Use statistics group information coming from SOLR

config/sync/core.entity_form_display.message.stream_document_insert_update.default.yml, config/sync/core.entity_form_display.message.stream_wiki_page_insert_update.default.yml, config/sync/field.field.message.stream_document_insert_update.field_group_ref.yml, config/sync/field.field.message.stream_document_insert_update.field_operation_type.yml, config/sync/field.field.message.stream_document_insert_update.field_referenced_node.yml, config/sync/field.field.message.stream_wiki_page_insert_update.field_group_ref.yml, config/sync/field.field.message.stream_wiki_page_insert_update.field_operation_type.yml, config/sync/field.field.message.stream_wiki_page_insert_update.field_referenced_node.yml, config/sync/search_api.index.global.yml, lib/modules/eic_messages/src/Hooks/FormOperations.php, lib/modules/eic_messages/src/Service/GroupContentMessageCreator.php
=> [EICNET-1090] feat: Send activity messages in solr for wiki & docs

lib/themes/eic_community/data/video.data.js, lib/themes/eic_community/patterns/components/video.html.twig, lib/themes/eic_community/patterns/compositions/video/video.full.html.twig, lib/themes/eic_community/sass/components/_video.scss, lib/themes/eic_community/sass/compositions/_editorial-header.scss, lib/themes/eic_community/sass/eic_community.screen.scss, lib/themes/eic_community/styleguide/bundles/video.stories.js, lib/themes/eic_community/styleguide/components/video.docs.mdx, lib/themes/eic_community/styleguide/components/video.stories.js
- Added video component
- Added video detail bundle
=> EICNET-1239 video detail page

lib/themes/eic_community/includes/preprocess/layout/page.inc, lib/themes/eic_community/templates/layout/page--groups.html.twig
=> [EICNET-1162] fix: Add login link on groups page and destination on all login links

config/sync/core.date_format.eu_format.yml, lib/modules/eic_groups/eic_groups.module, lib/modules/eic_groups/src/Plugin/Block/LastGroupMembersBlock.php, lib/modules/eic_groups/templates/eic-group-last-members.html.twig
=> [EICNET-1144]feat: show last five members of a group

lib/modules/eic_content/src/Controller/EntityTreeController.php, lib/modules/eic_content/src/Services/EntityTreeManager.php, lib/themes/eic_community/react/components/Field/EntityTree/Result/ResultItem.js, lib/themes/eic_community/react/components/Field/EntityTree/Result/Results.js, lib/themes/eic_community/react/components/Field/EntityTree/Result/Search.js, lib/themes/eic_community/react/components/Field/EntityTree/index.js
=> [EICNET-1163]fix: If the option disable top selection is enable, do not propose in search element and hide checkbox

config/sync/context.context.comment_pages.yml
https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-1111?focusedCommentId=4896668&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4896668
=> EICNET-111: Added please in the comments context.

Makefile
=> [EICNET] chore: call make build-front during update

composer.lock, composer.patches.json, lib/themes/eic_community/includes/preprocess/blocks/block--group-menu.inc
- Login as trusted user
- Navigate through a group menu by switching pages
- Check that the active menu item is always the one you just clicked
- Some of the group features might currently show the About page, this is due to dummy content that is shown for now until we have the actual overview pages for these
=> EICNET-1133: Patch the group_content_menu to fix the active trail.

config/sync/core.extension.yml, config/sync/filter.format.filtered_html.yml, config/sync/filter.format.full_html.yml, config/sync/oe_webtools_cookie_consent.settings.yml
- Enable module oe_webtools_cookie_consent; Enable cookie consent banner to show on iframes added via CKEditor.
=> EICNET-400: Text formats - input filter to block iframes

lib/themes/eic_community/includes/preprocess/comments/comment.inc, lib/themes/eic_community/includes/preprocess/content/node--discussion.inc, lib/themes/eic_community/includes/preprocess/groups/group.inc, lib/themes/eic_community/includes/preprocess/layout/page.inc, lib/themes/eic_community/templates/content/comment.html.twig, lib/themes/eic_community/templates/content/node--discussion--full.html.twig, lib/themes/eic_community/templates/field/field--node--field-comments.html.twig
https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-1162?focusedCommentId=4900224&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4900224
=> EICNET-1162: Multiple fixes.

lib/themes/eic_community/includes/preprocess/layout/page.inc
=> [EICNET-874] chore: Compute reading time in preprocess node

lib/themes/eic_community/includes/preprocess/blocks/block--latest-news-stories.inc
https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-1285?focusedCommentId=4901932&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4901932
=> EICNET-1285: Show story author teaser display and statistics on homepage

lib/themes/eic_community/includes/preprocess/blocks/block--latest-news-stories.inc
https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-1286?focusedCommentId=4903266&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4903266
=> EICNET-1286: Equalize image width and height for story/news teasers.

lib/themes/eic_community/react/components/Block/Overview/Search/TopOptions/SortOption.js
https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-1233?focusedCommentId=4903702&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4903702
=> EICNET-1233: Fixed visibility search sort options arrow.

lib/modules/eic_search/src/Search/Sources/GlobalSourceType.php
How to test:
Check description of this ticket: https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-1217
=> [EICNET-1217]fix: add more fields to search in

lib/modules/eic_flags/src/Hooks/EntityOperations.php
=> EICNET-1344: Fix issue when entity doesn't have a status field.

lib/modules/oec_group_flex/src/Plugin/CustomRestrictedVisibility/RestrictedEmailDomains.php
=> [EICNET-1236]fix: Remove first spaces in domain mails field

config/sync/migrate_plus.migration.smed_job_titles.yml, lib/modules/eic_webservices/config/install/migrate_plus.migration.smed_job_titles.yml
=> EICNET-1294: Import the job titles from SMED.

lib/modules/eic_groups/src/Access/GroupContentNodeAccessControlHandler.php
- Allow SA/SCM users to edit any group content of any group.
=> EICNET-1345: SA/SCM should be able to edit all group content of any group

config/sync/flag.flag.bookmark_content.yml, config/sync/flag.flag.like_content.yml, config/sync/flag.flag.recommend.yml, lib/themes/eic_community/includes/preprocess/content/node--video.inc
- For some reason, the Bookmark and Highlight are not displaed properly, this should be tackled in the theme
=> EICNET-1366: Allow video and gallery for recommend, like and bookmark flags

config/sync/core.entity_form_display.node.book.default.yml, config/sync/core.entity_form_display.node.news.default.yml, config/sync/core.entity_form_display.node.page.default.yml, config/sync/core.entity_form_display.node.story.default.yml, config/sync/core.entity_view_display.message.log_group_state_change.pre_render.yml, config/sync/core.entity_view_display.node.video.default.yml, config/sync/core.entity_view_display.node.wiki_page.default.yml, config/sync/core.entity_view_display.node.wiki_page.teaser.yml, config/sync/filter.format.filtered_html.yml
- I also included some config that needed to be updated in the repo
=> EICNET-1368: Fix the display of topics for videos.

.gitlab-ci.yml, composer.json, composer.lock, phpstan.neon
This PR introduce PHPStan analysis (static code analysis) for the lib/modules path
It also moves the deployment job to release/* branches
=> [EICNET] feat: Introduce static code analysis

lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GlobalResultItem.js
=> [EICNET]feat: Decode special characters into global search

lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/ActivityStream/Footer.js, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GroupResultItem.js, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/DocumentLibraryResultItem.js, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/GalleryLibraryResultItem.js, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/VideoLibraryResultItem.js
=> [EICNET-1184]feat: Add also statistics for likes + fix icon time

lib/modules/eic_groups/src/Form/SearchMenuGroupForm.php, lib/modules/eic_search/src/Controller/SolrSearchController.php, lib/modules/eic_search/src/Search/Sources/ActivityStreamSourceType.php, lib/modules/eic_search/src/Search/Sources/GlobalSourceType.php, lib/modules/eic_search/src/Search/Sources/GroupSourceType.php, lib/modules/eic_search/src/Search/Sources/LibrarySourceType.php, lib/modules/eic_search/src/Search/Sources/SourceType.php, lib/modules/eic_search/src/Search/Sources/SourceTypeInterface.php, lib/modules/eic_search/src/Search/Sources/UserGallerySourceType.php, lib/modules/eic_search/src/Search/Sources/UserListSourceType.php
=> [EICNET-843]fix: contextualize global search to group with redirect

config/sync/context.context.search.yml, lib/modules/eic_search/eic_search.module, lib/modules/eic_search/src/Search/Sources/GlobalSourceType.php, lib/modules/eic_search/src/Service/SolrDocumentProcessor.php, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GlobalResultItem.js
=> [EICNET-1101]feat: Add total downloaded document into solr and react

lib/modules/oec_group_flex/src/Entity/Form/GroupForm.php
- Set "invite members" enabled by default when creating a new group with joining method set to "tu_group_membership_request".
=> EICNET-1373: Change "invite member" default settings in group creation form based on joining method

config/sync/field.field.node.document.field_document_media.yml
- Make the document field mandatory in CT Document.
=> EICNET-1189: CT document back-end (rework)

lib/themes/eic_community/sass/compositions/_comment-overview.scss
Update for spacing issues when comment form is not shown.
=> EICNET-1433: Video comments styling fix.

lib/themes/eic_community/templates/field/field--node--field-disclaimer.html.twig, lib/themes/eic_community/templates/field/fragment.html.twig
https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-976?focusedCommentId=4952187&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4952187
=> EICNET-976: Removed unneeded html to get disclaimer styling correct

lib/modules/eic_groups/src/EICGroupsHelper.php, lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
- Improve logic from getGroupContentOperationLinks() method in order to return only links the user has access to.
=> EICNET-1226: As a GM, I can upload my own videos

lib/themes/eic_community/patterns/compositions/member/member.teaser.html.twig, lib/themes/eic_community/sass/compositions/_teaser.scss, lib/themes/eic_community/styleguide/bundles/member.stories.js
Fixed height of member container to stretch with other items on the same line.
=> EICNET-1136: Member country overflow fix.

lib/themes/eic_community/patterns/compositions/editorial-header.html.twig, lib/themes/eic_community/patterns/compositions/simple-banner.html.twig, lib/themes/eic_community/sass/compositions/_collapsible-options.scss, lib/themes/eic_community/styleguide/bundles/group.stories.js, lib/themes/eic_community/styleguide/compositions/collapsible-options.stories.js, lib/themes/eic_community/templates/navigation/eic-content-actions.html.twig
- Added variant with yellow background on collapsible options.
=> EICNET-1099: Collapsible options new variant.

lib/themes/eic_community/data/subnavigation/overview.data.js, lib/themes/eic_community/styleguide/bundles/group.stories.js
Updated labels and flags for group pending state
=> EICNET-784 update stats / removed unneeded flags / update copy of menu

config/sync/metatag.metatag_defaults.node__video.yml
=> EICNET-1367: Add metatags configuration for Video CT.

config/sync/core.entity_view_display.node.gallery.default.yml, config/sync/core.entity_view_display.node.gallery.full.yml, config/sync/core.entity_view_display.node.gallery.teaser.yml, lib/modules/eic_media/src/MediaHelper.php, lib/themes/eic_community/includes/preprocess/content/node--document.inc, lib/themes/eic_community/includes/preprocess/content/node--gallery.inc, lib/themes/eic_community/includes/preprocess/content/node--news--story.inc, lib/themes/eic_community/includes/preprocess/content/node--video.inc, lib/themes/eic_community/includes/preprocess/field/field--media--eic-document.inc, lib/themes/eic_community/includes/preprocess/users/user.inc, lib/themes/eic_community/templates/content/node--gallery--full.html.twig
https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-1204?focusedCommentId=4954178&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4954178
I had to create the full detail page too, the display of the slides is not done.
=> EICNET-1204: Added video detail page with filelist.

lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Answer.js, lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/TopAnswer.js
CommentForm break the actions line in the footer of each comment. So I move it
=> EICNET-635 Fix: change position of the CommentForm

lib/themes/eic_community/patterns/components/follow-us.html.twig, lib/themes/eic_community/patterns/compositions/follow-us.html.twig, lib/themes/eic_community/patterns/pages/homepage/homepage.private.html.twig, lib/themes/eic_community/patterns/pages/homepage/homepage.public.html.twig, lib/themes/eic_community/sass/components/_follow-us.scss, lib/themes/eic_community/sass/eic_community.screen.scss, lib/themes/eic_community/styleguide/components/follow-us.docs.mdx, lib/themes/eic_community/styleguide/components/follow-us.stories.js, lib/themes/eic_community/styleguide/compositions/follow-us.docs.mdx, lib/themes/eic_community/styleguide/compositions/follow-us.stories.js, lib/themes/eic_community/styleguide/pages/homepage.stories.js
Check in storybook 
/?path=/story/compositions-follow--base
/?path=/story/pages-homepage--homepage-private
=> EICNET-1367 | Feat: Follow-us item for the homepage

lib/themes/eic_community/react/components/Field/EntityTree/index.js
=> [EICNET-1405]feat: if there is no values for required field tree, scroll to it

lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Answers.js, lib/themes/eic_community/react/components/Block/CommentsDiscussion/Services/Permissions.js, lib/themes/eic_community/react/components/Block/CommentsDiscussion/Services/UrlHelper.js, lib/themes/eic_community/react/components/Block/CommentsDiscussion/index.js
=> [EICNET]fix: Fix community path on different env

lib/themes/eic_community/sass/compositions/_editorial-header.scss
http://localhost:9000/?path=/story/bundles-story--full-public
=> EICNET-1476 | Fix: wrap header in a story

lib/modules/eic_comments/eic_comments.module
=> EICNET-1520: Fix issue when creating a new node.

lib/modules/eic_groups/src/EICGroupsHelper.php, lib/modules/eic_search/eic_search.services.yml, lib/modules/eic_search/src/Service/SolrDocumentProcessor.php, lib/modules/oec_group_flex/src/OECGroupFlexHelper.php, lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-header-block.inc, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GroupResultItem.js
=> [EICNET-1350]feat: Keep same label visibility type

config/sync/context.context.group_files_overviews.yml, config/sync/context.context.search.yml
Remove old blocks not linked to context_id
=> [EICNET]fix: remove bad config eic_search_block

config/sync/search_api.index.global.yml, lib/modules/eic_search/src/Search/Sources/GlobalSourceType.php, lib/modules/eic_search/src/Search/Sources/LibrarySourceType.php
=> EICNET-1223: Also search on gallery media names.

lib/themes/eic_community/sass/compositions/_table.scss, lib/themes/eic_community/sass/eic_community.screen.scss, lib/themes/eic_community/templates/views/views-view-table.html.twig
Tickets [EICNET-1621](https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&view=detail&selectedIssue=EICNET-1621&quickFilter=26820&quickFilter=26822) & [EICNET-1622](https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&view=detail&selectedIssue=EICNET-1622&quickFilter=26820&quickFilter=26822) & [EICNET-1623](https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&view=detail&selectedIssue=EICNET-1623&quickFilter=26820&quickFilter=26822)
=> [EICNET-1621] table style

config/sync/views.view.group_pending_members.yml
=> [EICNET-1623] add empty state in the table

lib/modules/eic_default_content/src/Generator/GroupGenerator.php
=> EICNET-1531: Add Event CT to default content.

lib/themes/eic_community/patterns/compositions/collapsible-options.html.twig, lib/themes/eic_community/sass/compositions/_collapsible-options.scss, lib/themes/eic_community/styleguide/compositions/collapsible-options.stories.js
=> [EICNET-1651] Feat: storybook add "manage" in collapsible options

lib/themes/eic_community/patterns/compositions/notification-banner.html.twig, lib/themes/eic_community/sass/compositions/_notification-banner.scss, lib/themes/eic_community/sass/eic_community.screen.scss, lib/themes/eic_community/templates/status/status-messages.html.twig
- got to home
- flush all caches
- and see the new style
https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&view=detail&selectedIssue=EICNET-1658&quickFilter=26822
=> [EICNET-1658] FEAT: new style for notification

config/sync/core.entity_form_display.group_content.group-group_invitation.default.yml, config/sync/core.entity_view_display.group_content.group-group_invitation.default.yml, config/sync/field.field.group_content.group-group_invitation.field_invitation_counter.yml, config/sync/field.storage.group_content.field_invitation_counter.yml, config/sync/group.content_type.group-group_invitation.yml, config/sync/views.view.group_invitations.yml, lib/modules/eic_groups/eic_groups.module, lib/modules/eic_groups/eic_groups.routing.yml, lib/modules/eic_groups/src/Controller/GroupMembershipInvitationController.php, lib/modules/eic_groups/src/EICGroupsHelper.php, lib/modules/eic_groups/src/Plugin/views/field/ResendInvitation.php, lib/themes/eic_community/includes/preprocess/form/input--search.inc
=> [EICNET-1647] I want an option on group invitation so that I can resend an invitation to a user

config/sync/context.context.homepage.yml, lib/modules/eic_content/eic_content.module, lib/modules/eic_content/src/Plugin/Block/ContentOperationsBlock.php, lib/themes/eic_community/includes/preprocess/theme/eic-content-actions.inc, lib/themes/eic_community/templates/navigation/eic-content-actions.html.twig
- Update eic_content_operations block so that it contains optional title, description and link to the user activity stream;
- Update eic_content_operations block template;
- Update homepage context with new block changes.
=> EICNET-1652: Homepage welcome message for logged in users

lib/themes/eic_community/sass/components/_form.scss
https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-1677
=> [EICNET] Request group join | FEAT: change style of form actions

config/sync/core.entity_view_display.overview_page.overview_page.default.yml, lib/modules/eic_overviews/eic_overviews.module, lib/modules/eic_overviews/templates/overview-page.html.twig, lib/modules/eic_topics/eic_topics.module, lib/themes/eic_community/templates/taxonomy/taxonomy-term--topics.html.twig
How to test:
Go to /groups, /people, /search or topic detail and be sure you have an awesome overview image
=> [EICNET]feat: implement banner image in back template

config/sync/user.role.content_administrator.yml, config/sync/user.role.site_admin.yml, config/sync/user.role.trusted_user.yml, lib/modules/eic_private_message/eic_private_message.permissions.yml, lib/modules/eic_private_message/eic_private_message.routing.yml, lib/modules/eic_private_message/src/Form/PrivateMessageForm.php, lib/modules/eic_private_message/src/Plugin/EntityReferenceSelection/MembershipSelection.php, lib/modules/oec_group_flex/src/Plugin/GroupVisibility/CustomRestrictedVisibility.php
PS: you can search with firstname, lastname and email
=> [EICNET-1608]feat: Create new route to contact multiple users in a group

lib/modules/eic_content/src/Plugin/Block/ContentOperationsBlock.php
=> EICNET-XXXX: Add event node type and use bundle label.

config/sync/context.context.group_group_homepage.yml, config/sync/views.view.group_events.yml, lib/themes/eic_community/includes/alter/theme_suggestions/views.inc
- Create view list of group events and place block in group overview page.
=> EICNET-XXXX: Group overview events list

lib/themes/eic_community/sass/compositions/_table.scss
add more padding on table row on groups pending members
=> [EICNET-1623] Feat: add more padding on members tables

config/sync/context.context.homepage.yml, config/sync/context.context.homepage_anonymous.yml, config/sync/search_api.index.global.yml, config/sync/views.view.groups_homepage.yml, lib/modules/eic_search/src/Service/SolrDocumentProcessor.php, lib/themes/eic_community/includes/alter/theme_suggestions/views.inc, lib/themes/eic_community/includes/preprocess/views.inc, lib/themes/eic_community/templates/views/views-view--featured-content-collection--compact.html.twig, lib/themes/eic_community/templates/views/views-view--featured-content-collection.html.twig
- Create new view block to show last updated groups in the homepage;
- Create new view block to show list of upcoming events in the homepage;
- Add group moderation state and date changed to group solr index.
=> EICNET-1689/EICNET-296: Homepage groups/events

config/sync/search_api.index.global.yml, lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
=> [EICNET-1493]feat: put an url on the user teaser for group

lib/themes/eic_community/react/components/Block/Overview/Search/Results.js, lib/themes/eic_community/react/components/Block/Overview/index.js
=> [EICNET-1698]feat: Check if results has been initiated before showing no results message

lib/modules/eic_topics/eic_topics.module, lib/themes/eic_community/templates/layout/page--taxonomy--term.html.twig, lib/themes/eic_community/templates/taxonomy/taxonomy-term--topics.html.twig
=> [EICNET]feat: Set sidebar on the right and banner outside content region for Topic

lib/themes/eic_community/sass/components/_form.scss
=> [EICNET] Fix: add padding on the form

config/sync/core.entity_form_display.overview_page.overview_page.default.yml, config/sync/core.entity_view_display.overview_page.overview_page.default.yml, config/sync/field.field.overview_page.overview_page.field_overview_id.yml, config/sync/field.storage.overview_page.field_overview_id.yml, lib/modules/eic_default_content/src/Generator/OverviewPageGenerator.php, lib/modules/eic_groups/src/Breadcrumb/GroupBreadcrumbBuilder.php, lib/modules/eic_overviews/eic_overviews.module, lib/modules/eic_overviews/src/GlobalOverviewPages.php, lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-header-block.inc, lib/themes/eic_community/includes/preprocess/views.inc
Now we get overview page by an ID directly linked to the entity via the new field "field_overview_id"
=> [EICNET-1719]chore: Refactor the way we get global overview page

lib/themes/eic_community/react/components/Block/ShareModal/components/ShareModal.js
- Add an event listener on the modal to close it when I press on "esc" key
=> [EICNET] Feat: add "esc" event listener on the modal to close it

lib/themes/eic_community/patterns/components/filelist.html.twig, lib/themes/eic_community/sass/components/_filelist.scss
=> [EICNET-1695]fix: make file label clickable

lib/themes/eic_community/templates/oe_webtools/oe-webtools-social-share.html.twig
=> [EICNET-1683] add share icon in group flags

lib/modules/eic_groups/src/Access/FlagRequestAccessCheck.php
=> [EICNET-1709] chore: Allow delete/archival requests for draft groups

lib/themes/eic_community/patterns/compositions/topic/topic.overview.subitem.html.twig, lib/themes/eic_community/sass/compositions/_topic.scss, lib/themes/eic_community/styleguide/bundles/topic.stories.js
http://localhost:9000/iframe.html?id=bundles-topic--topic-overview&viewMode=story
add empty image state
=> [EICNET] add image empty state

lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/DiscussionResultItem.js, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/DocumentLibraryResultItem.js, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/GalleryLibraryResultItem.js, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/Partials/HighlightLink.js, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/VideoLibraryResultItem.js
=> [EICNET-1694]fix: ADd correct permission + icon state for highlight content

config/sync/group.role.event-admin.yml, config/sync/group.role.event-outsider.yml, config/sync/group.role.event-owner.yml, config/sync/views.view.admin_groups.yml
- Create owner role for group type event;
- Update member and outsider permissions.
=> EICNET-1727: Event admin view - creation of owner

lib/themes/eic_community/patterns/components/attachment.html.twig, lib/themes/eic_community/sass/components/_attachment.scss
=> [EICNET] align the style with the figma

lib/themes/eic_community/sass/components/_form.scss
As a SCM go to the add group front-end form and check if the the label of the fields is ok 
https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&view=detail&selectedIssue=EICNET-1667&quickFilter=26820&quickFilter=26822
https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&view=detail&selectedIssue=EICNET-1643&quickFilter=26820&quickFilter=26822
=> [EICNET] Fix label style for media field in a form

lib/themes/eic_community/patterns/compositions/member-information-block.html.twig, lib/themes/eic_community/patterns/compositions/member/member.teaser.html.twig, lib/themes/eic_community/sass/compositions/_contact-information-block.scss, lib/themes/eic_community/sass/compositions/_teaser.scss, lib/themes/eic_community/styleguide/bundles/group.stories.js, lib/themes/eic_community/styleguide/bundles/member.stories.js
http://localhost:9000/?path=/story/bundles-group--group-member-private
http://localhost:9000/?path=/story/bundles-member--teaser-user-no-image
https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&projectKey=EICNET&view=detail&selectedIssue=EICNET-1768&quickFilter=26822
=> [EICNET] add image empty state on all member teaser

lib/themes/eic_community/data/teaser/group.data.js, lib/themes/eic_community/data/teaser/project.data.js, lib/themes/eic_community/patterns/compositions/featured-content-grid.html.twig, lib/themes/eic_community/patterns/compositions/group/group.teaser.html.twig, lib/themes/eic_community/patterns/compositions/project/project.teaser.html.twig
add click on teaser image http://localhost:9000/?path=/story/pages-homepage--homepage-private
=> [EICNET] add click on the teasers image

lib/modules/eic_groups/src/Plugin/Block/CommentsFromDiscussionBlock.php, lib/themes/eic_community/react/components/Block/CommentsDiscussion/index.js
Refactor to have a better code
=> [EICNET] refactor comments in react

lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/UserGalleryResultItem.js, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/UserListResultItem.js
=> [EICNET] add no image state on member in react items

lib/themes/eic_community/mails/mail-dist/group_ownership_transfer.html, lib/themes/eic_community/mails/mail-dist/template.html, lib/themes/eic_community/mails/mail-dist/template_02.html, lib/themes/eic_community/mails/src/group_ownership_transfer.mjml, lib/themes/eic_community/mails/src/template.mjml, lib/themes/eic_community/mails/src/template_02.mjml
check if the mail is correct; http://localhost:8080//themes/custom/eic_community/mails/mail-dist/group_ownership_transfer.html
=> [EICNET] create mail template

lib/modules/eic_search/eic_search.module, lib/modules/eic_search/src/Plugin/search_api/processor/GroupAccessContent.php, lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
=> [EICNET-1830]feat: Filter on the correct group id

lib/themes/eic_community/includes/preprocess/layout/page.inc
=> [EICNET-1761]feat: Add first section of the footer menu

config/sync/core.entity_form_display.message.stream_share_content.default.yml, config/sync/core.entity_view_display.user.user.compact.yml, config/sync/views.view.group_discussions.yml, config/sync/views.view.group_documents.yml, config/sync/views.view.group_events.yml, lib/modules/oec_group_features/src/Plugin/views/access/GroupFeatureAccess.php
=> [EICNET-1656]feat: Implement new access views plugin to allow block if linked feature enabled

config/sync/views.view.group_events.yml
- Show upcoming events in group overview page.
=> EICNET-1841: List of events in group overview page - show ongoing events

lib/themes/eic_community/templates/group/eic-group-search-menu-field-search-submit.html.twig
=> [EICNET] add search icon in subnav search

lib/themes/eic_community/sass/components/_gallery.scss, lib/themes/eic_community/sass/compositions/_editorial-article.scss, lib/themes/eic_community/templates/content/node--gallery--full.html.twig
=> [EICNET] correct width on mobile for .ecl-editorial-article__content

lib/themes/eic_community/sass/components/_filelist.scss
NEED https://github.com/EIC-EA/EIC-community-D8/pull/982 When it is approved, I will merge it into this branch so that you can have a correct view.
=> [EICNET] Event filelist add space between files and change btn style

lib/themes/eic_community/templates/content/node--discussion--full.html.twig
=> [EICNET] Group discussions change the key author by name in the twig file

lib/themes/eic_community/patterns/compositions/filelist/filelist.teaser.html.twig, lib/themes/eic_community/patterns/compositions/gallery/gallery.teaser.html.twig, lib/themes/eic_community/patterns/compositions/group/group.teaser.html.twig, lib/themes/eic_community/patterns/compositions/member/member.teaser.html.twig, lib/themes/eic_community/patterns/compositions/organisation/organisation.teaser.html.twig, lib/themes/eic_community/patterns/compositions/project/project.teaser.html.twig, lib/themes/eic_community/patterns/compositions/story/story.teaser.html.twig, lib/themes/eic_community/patterns/compositions/video/video.teaser.html.twig, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/DiscussionResultItem.js, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GlobalEventResultItem.js, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GroupEventResultItem.js, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GroupResultItem.js, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/DocumentLibraryResultItem.js, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/GalleryLibraryResultItem.js, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/VideoLibraryResultItem.js, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/StoryResultItem.js, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/UserGalleryResultItem.js, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/UserListResultItem.js
Normally now we have a click on all empty state's teaser elements (twig and react)
=> [EICNET] Teaser elements add click on empty state image

lib/themes/eic_community/sass/compositions/_teaser.scss
=> [EICNET] members card remove margin on organisation

lib/themes/eic_community/react/components/Block/Overview/Search/Library/AddLibraryContent.js
=> [EICNET-1846] remove empty svg in sidebar of overview layout in react

lib/themes/eic_community/sass/components/_checkbox.scss, lib/themes/eic_community/sass/eic_community.screen.scss
https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-1849
=> [EICNET-1849] correct checkbox style

lib/themes/eic_community/react/components/Block/Overview/Search/TopOptions/ActiveFacet.js, lib/themes/eic_community/sass/components/_tag.scss
https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-1850
=> [EICNET-1850] correct icon for tag in group overview

lib/themes/eic_community/patterns/compositions/organisation/organisation.overview.html.twig, lib/themes/eic_community/patterns/compositions/teaser-overview.html.twig, lib/themes/eic_community/sass/compositions/_teaser-overview.scss, lib/themes/eic_community/sass/compositions/_teaser.scss, lib/themes/eic_community/styleguide/bundles/organisation.stories.js
- overview: http://localhost:9000/?path=/story/bundles-organisation--overview
- teaser: http://localhost:9000/?path=/story/compositions-teaser--organisation-teaser
https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&view=planning&selectedIssue=EICNET-1790&issueLimit=100
=> [EICNET-1790] correct design for Organisation overview in storybook

lib/themes/eic_community/sass/compositions/_table.scss, lib/themes/eic_community/templates/views/views-view-table.html.twig
=> [EICNET] Groups tables change view on mobile

config/sync/context.context.comments.yml, lib/modules/eic_groups/src/Controller/DiscussionController.php, lib/modules/eic_groups/src/Plugin/Block/CommentsFromDiscussionBlock.php, lib/modules/oec_group_comments/src/Plugin/Field/FieldFormatter/CommentGroupContentFormatter.php
=> [EICNET-1670]feat: Adapt comment section for non-group content

lib/themes/eic_community/includes/preprocess/content/node--document.inc, lib/themes/eic_community/includes/preprocess/content/node--gallery.inc, lib/themes/eic_community/patterns/components/filelist.html.twig, lib/themes/eic_community/patterns/compositions/filelist/filelist.gallery.html.twig, lib/themes/eic_community/react/components/Block/Gallery/FileInfo.jsx, lib/themes/eic_community/react/components/Block/Gallery/Gallery.jsx, lib/themes/eic_community/react/components/Block/Gallery/Image.jsx, lib/themes/eic_community/react/components/Block/Gallery/entrypoint.js, lib/themes/eic_community/sass/components/_filelist.scss, lib/themes/eic_community/sass/components/_gallery.scss
=> [EICNET-1853] gallery/file detailed front end rework

config/sync/context.context.group_files_overviews.yml, config/sync/search_api.index.global.yml, lib/modules/eic_search/src/Search/Sources/LibrarySourceType.php, lib/modules/eic_search/src/Service/SolrDocumentProcessor.php, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Partials/StatisticsFooterResult.js
=> [EICNET-1101]feat: Handle likes differently when indexing

lib/modules/eic_private_message/src/Form/PrivateMessageForm.php
=> [EICNET-1608]feat: Set big number on maxlength for selecting users in group

lib/themes/eic_community/react/components/Block/Overview/Search/TopOptions/ActiveFacet.js, lib/themes/eic_community/sass/components/_tag.scss
https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&projectKey=EICNET&view=detail&selectedIssue=EICNET-1850&quickFilter=26822
now entire tag is clickable
=> [EICNET-1850] Overview header tags

lib/themes/eic_community/sass/components/_highlight.scss
https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&projectKey=EICNET&view=detail&selectedIssue=EICNET-1889&quickFilter=26822
=> [EICNET-1889] add hover effect on Highlighted icon

lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/DocumentLibraryResultItem.js
https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&projectKey=EICNET&view=detail&selectedIssue=EICNET-1895&quickFilter=26822
=> [EICNET-1895] bugfix missing div container for document librabry

lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.module, lib/modules/eic_statistics/modules/eic_group_statistics/eic_group_statistics.services.yml, lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsHelper.php, lib/modules/eic_statistics/modules/eic_group_statistics/src/Plugin/views/field/GroupMemberCommentCount.php, lib/modules/eic_statistics/modules/eic_group_statistics/src/Plugin/views/field/GroupMemberContentCount.php, lib/modules/eic_statistics/modules/eic_group_statistics/src/Plugin/views/field/GroupMemberHelper.php, lib/modules/eic_statistics/modules/eic_group_statistics/src/Plugin/views/field/GroupMemberLatestActivity.php
- Views plugins for member latest activity, content count and comment count
=> EICNET-1860: Group members data export

lib/modules/eic_content/src/Services/EntityTreeManager.php
=> [EICNET-1474]fix: Be able to search in fullname and not only first or last name

config/sync/core.entity_form_display.profile.member.default.yml
- Apply entity tree widget in user profile interests.
=> EICNET-1725: Error when adding same topic of interest multiple times in user profile

lib/themes/eic_community/sass/components/_form.scss, lib/themes/eic_community/templates/form/form.html.twig
https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&projectKey=EICNET&view=detail&selectedIssue=EICNET-1643&quickFilter=26822
=> [EICNET-1643] responsive form improvement

lib/modules/eic_groups/src/Plugin/Block/CommentsFromDiscussionBlock.php, lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Answer.js, lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/TopAnswer.js
https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&view=detail&selectedIssue=EICNET-1916&quickFilter=26822
https://www.figma.com/file/WZH3qhNynnmm0H6FKmD3hi/EASME_v1?node-id=3381%3A45
=> [EICNET-1916] change "reply to" to "reply" and remove name

lib/themes/eic_community/data/extended-list/interests.data.js, lib/themes/eic_community/sass/compositions/_extended-list.scss
https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&projectKey=EICNET&view=detail&selectedIssue=EICNET-1808&quickFilter=26822
https://www.figma.com/file/WZH3qhNynnmm0H6FKmD3hi/EASME_v1?node-id=3275%3A0
=> [EICNET-1808] Visual - Bullet points

lib/themes/eic_community/react/components/Block/Overview/Search/Pagination.js, lib/themes/eic_community/sass/compositions/_pagination.scss
https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&view=detail&selectedIssue=EICNET-1852&quickFilter=26820&quickFilter=26822
- missing pagination separator
-  hand cursor on Previous link on first page
=> [EICNET-1852] Group library overview

lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php, lib/themes/eic_community/react/components/Block/Overview/Search/Field/CheckboxField.js
=> [EICNET-1516]feat: Implement news article label for facet

lib/themes/eic_community/sass/components/_timestamp.scss, lib/themes/eic_community/sass/compositions/_teaser.scss
https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-296
=> [EICNET-296] Homepage upcoming events

lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php, lib/themes/eic_community/react/components/Block/Overview/Search/Sidebar.js, lib/themes/eic_community/react/components/Block/Overview/index.js
https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-1939
https://www.figma.com/file/WZH3qhNynnmm0H6FKmD3hi/EASME_v1?node-id=3461%3A0
- change title of the sidebar in the group search
from "Filter" to "Refine your search "
=> [EICNET-1939] group search change title sidebar

lib/themes/eic_community/sass/compositions/_mainmenu.scss
https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&projectKey=EICNET&view=planning&selectedIssue=EICNET-1898&quickFilter=26822&issueLimit=100
=> [EICNET-1898] add global search on mobile

lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/Partials/HighlightLink.js, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/Partials/Meta.js, lib/themes/eic_community/sass/components/_filelist.scss, lib/themes/eic_community/sass/components/_highlight.scss, lib/themes/eic_community/sass/compositions/_teaser.scss
https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&projectKey=EICNET&view=planning&selectedIssue=EICNET-1919&quickFilter=26822&issueLimit=100
- add highlight icon in AU
- add style on uploaded by ****
- add max height on filelist teaser
=> [EICNET-1919] add highlight and change style of user in library

config/sync/config_ignore.settings.yml, config/sync/group.role.organisation-a416e6833.yml, config/sync/group.role.organisation-bf4b46c3a.yml, config/sync/group.role.organisation-eca6128ca.yml, config/sync/group.role.organisation-outsider.yml, config/sync/system.site.yml
=> [EICNET-190]fix: Add organisation permissions to outsider roles

lib/themes/eic_community/sass/components/_form.scss
https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&projectKey=EICNET&view=detail&selectedIssue=EICNET-1744&quickFilter=26822
add a little red stars for required field
=> [EICNET-1744] add required field

lib/themes/eic_community/sass/compositions/_teaser.scss
https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&projectKey=EICNET&view=detail&selectedIssue=EICNET-1895&quickFilter=26822
=> [EICNET-1895] add space between two highlighted teaser

config/sync/core.entity_form_display.group.organisation.default.yml
=> (draft)[EICNET-1744]feat: Re-order field offers and needs

lib/modules/eic_groups/eic_groups.routing.yml, lib/modules/eic_groups/eic_groups.services.yml, lib/modules/eic_groups/src/Access/LikeGroupContentAccessCheck.php, lib/modules/eic_groups/src/Controller/GroupOperationsController.php, lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/DocumentLibraryResultItem.js, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/GalleryLibraryResultItem.js, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/Partials/HighlightLink.js, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/Partials/LikeLink.js, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/Library/VideoLibraryResultItem.js, lib/themes/eic_community/react/components/Block/Overview/Search/Services/UrlHelper.js
=> [EICNET-1851]feat: On Library teaser item set dynamic like action

lib/themes/eic_community/react/components/Block/Overview/Search/Pagination.js, lib/themes/eic_community/react/components/Block/Overview/index.js, lib/themes/eic_community/react/components/Utils/Url.js, lib/themes/eic_community/sass/compositions/_pagination.scss
https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-1879?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel
- add params 'page'  in url
- get params 'page' from url
=> [EICNET-1879] add current page in url

lib/themes/eic_community/react/components/Block/Overview/index.js
https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&projectKey=EICNET&view=detail&selectedIssue=EICNET-1877&quickFilter=26822
- I move the prefilter facet in a function and call only 1 times _searchSolr_  when the component is mount
=> [EICNET-1877] 

config/sync/pathauto.pattern.group_event.yml
- Create pathauto pattern for Group type Event
=> EICNET-1479: Global event detailed (improvements)

lib/themes/eic_community/includes/preprocess/groups/group.inc, lib/themes/eic_community/sass/components/_tag.scss
=> [EICNET-1896]feat: Add extraclasses for tag color in group teaser

lib/modules/eic_flags/eic_flags.services.yml, lib/modules/eic_flags/src/Service/TransferOwnershipRequestHandler.php, lib/modules/eic_groups/src/Hooks/EntityOperations.php, lib/modules/eic_search/src/Controller/SolrSearchController.php, lib/modules/eic_search/src/Service/SolrDocumentProcessor.php
=> [EICNET-1821]feat: Handle blocked group state with group content

lib/modules/eic_search/src/Controller/SolrSearchController.php, lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php, lib/modules/eic_search/src/Search/Sources/NewsStorySourceType.php
=> [EICNET-1780]feat: add filter private + sort created

lib/themes/eic_community/sass/compositions/_notification-banner.scss
https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&view=detail&selectedIssue=EICNET-1986&quickFilter=26822
=> [EICNET-1986] add space between notifications

lib/themes/eic_community/react/components/Block/ActivityStream/partials/ResultItemWrapper.js, lib/themes/eic_community/sass/components/_author.scss
=> [EICNET] Author image empty state

composer.lock, composer.patches.json, config/sync/user.role.content_administrator.yml, config/sync/user.role.site_admin.yml
- Revert permissions to masquerade as authenticated users and apply patch ("Masquerade as ROLE" permission not granting access https://www.drupal.org/project/masquerade/issues/3181882)
Follow tests from PR #1118
=> EICNET-1825: Masquerade a user (rework)

lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Answer.js, lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/TopAnswer.js
- As an admin, go to your favorite group discussion
- send a comment
- and delete it
=> [EICNET-2075] hide stats and likes action on hidden comments

config/sync/core.entity_form_display.group.organisation.default.yml, config/sync/core.entity_form_display.paragraph.organisation_location.default.yml, config/sync/core.entity_view_display.group.organisation.default.yml, config/sync/core.entity_view_display.paragraph.organisation_location.default.yml, config/sync/field.field.group.organisation.field_locations.yml, config/sync/field.field.paragraph.organisation_location.field_city.yml, config/sync/field.field.paragraph.organisation_location.field_country.yml, config/sync/field.storage.group.field_locations.yml, config/sync/field.storage.paragraph.field_city.yml, config/sync/field.storage.paragraph.field_country.yml, config/sync/paragraphs.paragraphs_type.organisation_location.yml, config/sync/search_api.index.global.yml, lib/modules/eic_private_message/src/Plugin/EntityReferenceSelection/MembershipSelection.php, lib/themes/eic_community/includes/preprocess/groups/organisation.inc, lib/themes/eic_community/templates/group/group--organisation--full.html.twig
=> [EICNET-1881]fix: Replace translation + addresses label + autocomplete internal link

composer.json, composer.lock, config/sync/facets.facet.discussions_regions_countries.yml, config/sync/facets.facet.discussions_topics.yml, config/sync/facets.facet.discussions_type.yml, config/sync/facets.facet.global_members_job_title.yml, config/sync/facets.facet.global_members_languages.yml, config/sync/facets.facet.global_members_location_country_code.yml, config/sync/facets.facet.global_members_topics_of_expertise.yml, config/sync/facets.facet.groups_regions_countries.yml, config/sync/facets.facet.groups_topics.yml, config/sync/facets.facet.members_languages.yml, config/sync/facets.facet.members_topics_of_expertise.yml, config/sync/facets.facet.members_topics_of_interest.yml, config/sync/facets.facet.search_content_type.yml, config/sync/facets.facet.search_group_content_type.yml, config/sync/facets.facet.search_group_regions_countries.yml, config/sync/facets.facet.search_group_topics.yml, config/sync/facets.facet.search_regions_countries.yml, config/sync/facets.facet.search_topics.yml, lib/modules/eic_default_content/eic_default_content.info.yml, lib/modules/eic_default_content/eic_default_content.services.yml, lib/modules/eic_default_content/src/Generator/GroupGenerator.php, lib/modules/eic_default_content/src/Generator/OrganisationGenerator.php, lib/modules/eic_groups/src/Breadcrumb/GroupBreadcrumbBuilder.php
- Add missing fixture for group Wiki pages;
- Fix issue in group wiki breadcrumbs;
- Add missing fields in Organisation fixture;
- Update drupal core to 9.3.6;
- Update contrib modules (facets, search_api_spellcheck, publication_date);
=> EICNET-2101: Maintenance Sprint 32

config/sync/context.context.group_global.yml, config/sync/context.context.my_profile.yml, lib/modules/eic_user/eic_user.routing.yml, lib/modules/eic_user/src/Controller/MyProfileController.php, lib/modules/eic_user/src/Plugin/Block/MyProfileHeaderBlock.php
=> [EICNET]feat: Change route url for my interests

lib/modules/eic_groups/eic_groups.module
=> [EICNET-1985]fix: If user is not logged in, do not authorize organisations

config/sync/context.context.following.yml, config/sync/context.context.interests.yml, config/sync/context.context.my_profile.yml, lib/modules/eic_search/eic_search.services.yml, lib/modules/eic_search/src/Controller/SolrSearchController.php, lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorFlags.php, lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorMessage.php, lib/modules/eic_search/src/Search/Sources/Profile/FollowingSourceType.php, lib/modules/eic_search/src/Search/Sources/SourceType.php, lib/modules/eic_search/src/Search/Sources/SourceTypeInterface.php, lib/modules/eic_user/eic_user.routing.yml, lib/modules/eic_user/eic_user.services.yml, lib/modules/eic_user/src/Controller/MyProfileController.php, lib/modules/eic_user/src/EventSubscriber/FlagEventSubscriber.php, lib/modules/eic_user/src/Plugin/Block/MyProfileHeaderBlock.php
=> [EICNET-1961]feat: Create the "following" activities overview

lib/themes/eic_community/includes/preprocess/groups/group.inc, lib/themes/eic_community/includes/preprocess/groups/organisation.inc, lib/themes/eic_community/templates/group/group--organisation--about-page.html.twig
=> [EICNET-1742]feat: Implement template + refactor about page organisation

docker-compose.yml, docker/php/Dockerfile
Restore the dockerfile as it is required to run the drupal pod
=> [EICNET]chore: Restore the PHP dockerfile

lib/modules/eic_search/src/Controller/SolrSearchController.php, lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php, lib/modules/eic_search/src/Search/Sources/Profile/FollowingSourceType.php, lib/modules/eic_search/src/Search/Sources/SourceType.php, lib/modules/eic_search/src/Search/Sources/SourceTypeInterface.php
=> [EICNET-1962]feat: Implement method to prefilter some fields to avoid empty values

config/sync/context.context.events.yml, config/sync/core.entity_form_display.group.event.default.yml, config/sync/core.entity_view_display.group.event.default.yml, config/sync/core.entity_view_display.group.event.small_teaser.yml, config/sync/core.entity_view_display.group.event.teaser.yml, config/sync/field.field.group.event.field_funding_source.yml, config/sync/field.storage.group.field_funding_source.yml, config/sync/search_api.index.global.yml, lib/modules/eic_events/src/Plugin/search_api/processor/EventWeightState.php, lib/modules/eic_search/eic_search.module, lib/modules/eic_search/eic_search.services.yml, lib/modules/eic_search/src/Controller/SolrSearchController.php, lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php, lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobalEvent.php, lib/modules/eic_search/src/Search/Sources/Profile/MyEventsSourceType.php, lib/modules/eic_search/src/Search/Sources/SourceType.php, lib/modules/eic_search/src/Search/Sources/SourceTypeInterface.php, lib/modules/eic_search/templates/search-overview-block.html.twig, lib/modules/eic_user/eic_user.routing.yml, lib/modules/eic_user/src/Plugin/Block/UserActivitySubnavigationBlock.php, lib/themes/eic_community/react/components/Block/Overview/Search/Sidebar.js, lib/themes/eic_community/react/components/Block/Overview/entrypoint.js, lib/themes/eic_community/react/components/Block/Overview/index.js
=> [EICNET-1956]feat: Add events activities source type

lib/themes/eic_community/react/components/Block/Overview/index.js
https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&view=detail&selectedIssue=EICNET-2142&quickFilter=26822
- Now we stay on the same place when we click on load more (http://localhost:8080/user/1/following)
=> [EICNET-2147]remove bump when we load more activity

lib/themes/eic_community/patterns/compositions/organisation/organisation.details.html.twig, lib/themes/eic_community/sass/compositions/_featured-list.scss, lib/themes/eic_community/templates/group/group--organisation--full.html.twig
- Now in organizations details, if you have more of 2 addresses, this is expandable
=> [EICNET-2142] Organisation contact information: expandable addresses

config/sync/core.extension.yml, config/sync/locale.settings.yml
Implementing the the user interface translation.
You can now edit every labels, texts, etc. that have been implemented via the t() method.
=> [EICNET] Enable UIT

lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php, lib/modules/eic_search/src/Search/Sources/GlobalSourceType.php, lib/modules/eic_search/src/Search/Sources/LibrarySourceType.php, lib/modules/eic_search/src/Search/Sources/Profile/ActivityStreamSourceType.php, lib/modules/eic_search/src/Search/Sources/Profile/ContributionSourceType.php, lib/modules/eic_search/src/Search/Sources/Profile/FollowingSourceType.php, lib/themes/eic_community/react/components/Block/Overview/Search/Field/SearchField.js
=> [EICNET-1953]fix: Set correct label for topic filter and search input

lib/modules/eic_user/templates/user-activity-subnavigation-block.html.twig, lib/themes/eic_community/styleguide/bundles/member.stories.js
=> [EICNET-1943] send icon_file_path to my activity view

lib/themes/eic_community/sass/compositions/_teaser.scss
- add margin right on  image  in organization member teaser
=> [EICNET-2138] add space between image and info in organization member teaser

lib/modules/eic_groups/src/Access/GroupPageAccessChecker.php, lib/modules/eic_groups/src/EICGroupsHelper.php, lib/modules/eic_groups/src/Routing/RouteSubscriber.php
=> EICNET-2137: Deny access to GO/GA to group edit page for blocked groups.

lib/modules/eic_search/src/Controller/SolrSearchController.php, lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php, lib/themes/eic_community/react/components/Block/Overview/Search/Field/DateField.js, lib/themes/eic_community/react/components/Block/Overview/Search/Field/SearchField.js, lib/themes/eic_community/react/components/Block/Overview/Search/Sidebar.js
=> [EICNET-1956]fix: Add more translations keys + filter on same day

lib/modules/eic_moderation/eic_moderation.module, lib/modules/eic_moderation/src/Hooks/FormOperations.php, lib/modules/eic_moderation/src/Service/ContentModerationManager.php
=> EICNET-2160: Make sure only allowed workflow states show up in groups.

config/sync/group.content_type.group_content_type_544ffa9c3791b.yml, config/sync/group.content_type.group_content_type_b47cbb19c399d.yml, lib/modules/eic_flags/src/Service/AbstractRequestHandler.php
=> [EICNET-1810]chore: Add delete/archival request links to organisations

config/sync/group.role.organisation-member.yml
=> [EICNET]fix: Add view group permission to GM

lib/themes/eic_community/data/teaser/index.js, lib/themes/eic_community/patterns/compositions/member-information-block.html.twig, lib/themes/eic_community/patterns/compositions/member/member.full.html.twig, lib/themes/eic_community/patterns/compositions/member/member.teaser.html.twig, lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Answer.js, lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/TopAnswer.js, lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/components/TopContrib.js, lib/themes/eic_community/sass/compositions/_comment.scss, lib/themes/eic_community/sass/compositions/_contact-information-block.scss, lib/themes/eic_community/sass/compositions/_teaser.scss, lib/themes/eic_community/styleguide/bundles/member.stories.js, lib/themes/eic_community/styleguide/compositions/teaser.stories.js
https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-2185
- Rework of Profile User
http://localhost:9000/?path=/story/bundles-member--full-public-top-contributor
- Rework of Member teaser
http://localhost:9000/?path=/story/compositions-teaser--member-teaser-top-contributors
- Rework of Member Teaser Gallery view
http://localhost:9000/?path=/story/bundles-member--overview-gallery
-Rework of Comments to add top contributor
=> [EICNET-2185] Top contributor

lib/modules/eic_user/src/Plugin/Block/UserHeaderBlock.php, lib/themes/eic_community/patterns/compositions/member/email-notification.html.twig
https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&projectKey=EICNET&view=detail&selectedIssue=EICNET-2055&quickFilter=26822
- I change icon from gear to user in btn my profile
=> [EICNET-2055] change icone in my profile btn in notif management

lib/themes/eic_community/includes/preprocess/layout/page.inc, lib/themes/eic_community/templates/layout/page--4xx.html.twig
- add template for page 4xx
- http://localhost:8080/dfdfdsfsd
- see the new page
=> [EICNET] add template for page 4xx

config/sync/group.role.organisation-4c7e676f7.yml, config/sync/group.role.organisation-admin.yml, config/sync/group.role.organisation-dcb2f93df.yml, config/sync/group.role.organisation-eca6128ca.yml, config/sync/group.role.organisation-outsider.yml, config/sync/group.role.organisation-owner.yml
=> [EICNET-2191]fix: Do not authorized the group node overview for all outsider

config/sync/user.role.content_administrator.yml, config/sync/user.role.site_admin.yml
=> [EICNET-2197]fix: Add access to SA SCM to edit their own book

lib/modules/eic_search/src/Controller/SolrSearchController.php
=> [EICNET-2201]fix: Show own contents even in draft for current user

lib/themes/eic_community/react/components/Block/CommentsDiscussion/index.js
https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-2210
- I fix the bug that we can tag a user on comment in the reply 
- go to discussion
- reply to a comment 
- and check if you can tag user, archive, delete, and click outside close the modal
=> [EICNET-2122] Fix click outside bug

lib/modules/eic_search/src/Plugin/Block/ActivityStreamBlock.php, lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php, lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorFlags.php, lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorMessage.php, lib/modules/eic_statistics/eic_statistics.routing.yml, lib/modules/eic_statistics/src/Controller/EntityStatisticsController.php, lib/modules/eic_statistics/src/StatisticsHelper.php, lib/themes/eic_community/package-lock.json, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/ActivityStreamResultItem.js
=> [EICNET-1450]fix: Activity stream item statistics endpoint

lib/modules/eic_messages/modules/eic_message_subscriptions/src/Hooks/FormOperations.php
=> [EICNET]fix: Fix wrong published condition

lib/modules/eic_flags/src/Service/TransferOwnershipRequestHandler.php, lib/modules/eic_groups/modules/eic_group_membership/eic_group_membership.info.yml, lib/modules/eic_groups/modules/eic_group_membership/eic_group_membership.services.yml, lib/modules/eic_groups/modules/eic_group_membership/src/EventSubscriber/MembershipTransitionSubscriber.php
=> [EICNET-2026]feat: Send e-mails when a membership request is approved

lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GroupResultItem.js, lib/themes/eic_community/sass/compositions/_teaser.scss
https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&view=detail&selectedIssue=EICNET-2200&quickFilter=26822
- Now the group title is truncated when it is longer than 2 lines
=> [EICNET-2200] change group teaser title style

config/sync/core.extension.yml, config/sync/filter.format.filtered_html.yml, config/sync/filter.format.full_html.yml, lib/modules/eic_wysiwyg/eic_wysiwyg.info.yml, lib/modules/eic_wysiwyg/src/Plugin/Filter/FilterTableDivs.php
=> EICNET-2227: Create a text filter to add divs around tables.

lib/modules/eic_flags/src/Service/AbstractRequestHandler.php
=> [EICNET-1810]fix: TU should not request archival/deletion

config/sync/context.context.drafts.yml, config/sync/search_api.index.global.yml, e2e/cypress/helper/login.js, e2e/cypress/integration/group/group.spec.js, e2e/cypress/integration/user/activity/my-drafts.spec.js, lib/modules/eic_search/eic_search.services.yml, lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php, lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobal.php, lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorMessage.php, lib/modules/eic_search/src/Search/Sources/Profile/DraftSourceType.php, lib/modules/eic_search/src/Search/Sources/SourceType.php, lib/modules/eic_search/src/Search/Sources/SourceTypeInterface.php, lib/modules/eic_search/src/Service/SolrSearchManager.php, lib/modules/eic_user/eic_user.routing.yml, lib/modules/eic_user/src/Plugin/Block/UserActivitySubnavigationBlock.php
=> [EICNET-1970]feat: Create my drafts overview

lib/modules/eic_groups/eic_groups.module
=> [EICNET-2152]fix: remove access for anonymous user to /people

lib/modules/eic_groups/src/EventSubscriber/SearchApiSubscriber.php
=> [EICNET-2256]feat: Add x-requested-with to handle ajax call for custom endpoints

lib/themes/eic_community/react/components/Block/NotifManagement/components/RowNotif.js
https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-2060?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel
- Add URL on items in the tab of notification management
=> [EICNET-2060] add url on item in notif management

lib/themes/eic_community/eic_community.libraries.yml, lib/themes/eic_community/js/common/drupal.ecl.js, lib/themes/eic_community/js/common/overides.js
https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-2057?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel
-  Previously, when you are on mobile and you swipe left, the main menu opens, I have disabled this as on some components we need to swipe...
=> [EICNET-2057] remove mobile menu event 

config/sync/migrate_plus.migration.smed_target_markets_lvl1.yml, config/sync/migrate_plus.migration.smed_target_markets_lvl2.yml, lib/modules/eic_webservices/config/install/migrate_plus.migration.smed_target_markets_lvl1.yml, lib/modules/eic_webservices/config/install/migrate_plus.migration.smed_target_markets_lvl2.yml
=> EICNET-2208: Add targeted_markets migration.

config/sync/group.role.event-a416e6833.yml, config/sync/group.role.event-bf4b46c3a.yml, config/sync/group.role.event-eca6128ca.yml, config/sync/group.role.event-member.yml
=> [EICNET-2291]fix: Authorize user to view their unpublished content

lib/modules/eic_user/src/Controller/MySettingsController.php
=> [EICNET-2060]chore: Sort by created DESC

lib/themes/eic_community/sass/overrides/_media-library.scss
https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-2296?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel
- as a SCM, media form FE glue to the design
=> [EICNET-2296] fix front end on media form

lib/modules/eic_topics/src/TopicsManager.php
=> EICNET-XXXX: Replace topics statistics documents from media to node.

lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobal.php
=> [EICNET-2313]fix: do not always put parent published to true for group

lib/themes/eic_community/patterns/compositions/featured-content-collapse-expand.html.twig, lib/themes/eic_community/patterns/compositions/organisation/organisation.details.html.twig, lib/themes/eic_community/templates/group/group--organisation--full.html.twig
- http://localhost:9000/?path=/story/bundles-organisation--detail
improve the code for featured content expand collapse
=> [EICNET] refactor featured content expand collapse

lib/modules/eic_groups/src/Access/GroupContentNodeAccessControlHandler.php
=> EICNET-2291: Fix group content view access.

config/sync/core.entity_form_display.message.notify_group_wait_approval.default.yml, config/sync/core.entity_view_display.message.notify_group_wait_approval.default.yml, config/sync/core.entity_view_display.message.notify_group_wait_approval.mail_body.yml, config/sync/core.entity_view_display.message.notify_group_wait_approval.mail_subject.yml, config/sync/field.field.message.notify_group_wait_approval.field_event_executing_user.yml, config/sync/field.field.message.notify_group_wait_approval.field_group_ref.yml, config/sync/language/en/message.template.notify_group_wait_approval.yml, config/sync/message.template.notify_group_wait_approval.yml, lib/modules/eic_groups/src/Hooks/CronOperations.php, web/sites/default/default.settings.local.php
=> [EICNET-2029]feat: Notify all SCM/SA for reminder of group waiting for approval

config/sync/core.entity_form_display.message.notify_group_admin_promoted.default.yml, config/sync/core.entity_view_display.message.notify_group_admin_promoted.default.yml, config/sync/core.entity_view_display.message.notify_group_admin_promoted.mail_body.yml, config/sync/core.entity_view_display.message.notify_group_admin_promoted.mail_subject.yml, config/sync/field.field.message.notify_group_admin_promoted.field_group_owner.yml, config/sync/field.storage.message.field_group_owner.yml, config/sync/language/en/message.template.notify_group_admin_promoted.yml, config/sync/message.template.notify_group_admin_promoted.yml, lib/modules/eic_groups/modules/eic_group_membership/eic_group_membership.module
https://www.figma.com/file/j583oU3vO3YfrU3SnZp4vQ/EIC---Analysis?node-id=153%3A3062
=> [EICNET-2036]feat: If a TU is promoted to group-admin, send a notify message

config/sync/core.entity_form_display.message.notify_contact_user.default.yml, config/sync/core.entity_view_display.message.notify_contact_user.default.yml, config/sync/core.entity_view_display.message.notify_contact_user.mail_body.yml, config/sync/core.entity_view_display.message.notify_contact_user.mail_subject.yml, config/sync/field.field.message.notify_contact_user.field_body.yml, config/sync/field.field.message.notify_contact_user.field_sender.yml, config/sync/field.field.message.notify_contact_user.field_subject.yml, config/sync/field.storage.message.field_body.yml, config/sync/field.storage.message.field_sender.yml, config/sync/field.storage.message.field_subject.yml, config/sync/language/en/message.template.notify_contact_user.yml, config/sync/message.template.notify_contact_user.yml, lib/modules/eic_private_message/src/Form/PrivateMessageForm.php
=> [EICNET-2232]feat: Send message correctly formated for contact user

config/sync/migrate_plus.migration.upgrade_d7_group_old_path_redirect.yml, config/sync/migrate_plus.migration.upgrade_d7_group_path_redirect.yml, config/sync/migrate_plus.migration.upgrade_d7_node_path_redirect.yml, config/sync/migrate_plus.migration.upgrade_d7_node_url_alias_to_path_redirect.yml, lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_group_old_path_redirect.yml, lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_group_path_redirect.yml, lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_path_redirect.yml, lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_node_url_alias_to_path_redirect.yml, lib/modules/eic_migrate/src/Plugin/migrate/source/GroupOldPathRedirect.php, lib/modules/eic_migrate/src/Plugin/migrate/source/GroupPathRedirect.php, lib/modules/eic_migrate/src/Plugin/migrate/source/PathRedirect.php, lib/modules/eic_migrate/src/Plugin/migrate/source/UrlAliasToPathRedirect.php
- Implement path redirect migrations for nodes and groups
Migrate node redirects:
Migrate group redirects:
=> EICNET-1443: Path redirect migration

config/sync/user.role.content_administrator.yml, config/sync/user.role.site_admin.yml
=> EICNET-2370: Allow SA/SCM to bypass groups workflow permissions.

config/sync/core.entity_form_display.message.notify_contact_user_copy.default.yml, config/sync/core.entity_view_display.message.notify_contact_user_copy.default.yml, config/sync/core.entity_view_display.message.notify_contact_user_copy.mail_body.yml, config/sync/core.entity_view_display.message.notify_contact_user_copy.mail_subject.yml, config/sync/field.field.message.notify_contact_user_copy.field_body.yml, config/sync/field.field.message.notify_contact_user_copy.field_subject.yml, config/sync/language/en/message.template.notify_contact_user_copy.yml, config/sync/message.template.notify_contact_user.yml, config/sync/message.template.notify_contact_user_copy.yml, lib/modules/eic_private_message/src/Form/PrivateMessageForm.php
https://citnet.tech.ec.europa.eu/CITnet/confluence/display/EICNET/SN+-+User+notifications#:~:text=logged%20in%20user.-,%23U2,-Contact%20user%20email
=> [EICNET-2362]feat: Send email with self copy to current user

config/sync/user.role.anonymous.yml, lib/themes/eic_community/includes/preprocess/layout/page.inc, lib/themes/eic_community/patterns/compositions/editorial-header.html.twig, lib/themes/eic_community/patterns/compositions/featured-contributors.html.twig, lib/themes/eic_community/patterns/compositions/featured-stories.html.twig, lib/themes/eic_community/patterns/compositions/featured-topics.html.twig, lib/themes/eic_community/sass/compositions/_editorial-article.scss, lib/themes/eic_community/sass/compositions/_editorial-header.scss, lib/themes/eic_community/templates/content/node--story--full.html.twig, lib/themes/eic_community/templates/layout/page--node--story.html.twig
https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&projectKey=EICNET&view=detail&selectedIssue=EICNET-2105&quickFilter=26822
- edit editorial header style
- edit featured content title style in sidebar
- Removed 'view bookmark content' from anonymous users
=> News & Stories - fix inconsistenties FE vs design

config/sync/core.entity_form_display.contact_message.contact_form.default.yml, config/sync/core.entity_view_display.contact_message.contact_form.default.yml, config/sync/field.field.contact_message.contact_form.field_contact_message.yml, config/sync/field.storage.contact_message.field_contact_message.yml, config/sync/user.role.anonymous.yml, config/sync/user.role.authenticated.yml, lib/modules/eic_contact/eic_contact.module
=> [EICNET-2350] chore: Use basic_text format for the contact message field

config/sync/core.entity_form_display.message.notify_contact_global_copy.default.yml, config/sync/core.entity_view_display.message.notify_contact_global_copy.default.yml, config/sync/core.entity_view_display.message.notify_contact_global_copy.mail_body.yml, config/sync/core.entity_view_display.message.notify_contact_global_copy.mail_subject.yml, config/sync/field.field.message.notify_contact_global_copy.field_body.yml, config/sync/field.field.message.notify_contact_global_copy.field_sender.yml, config/sync/field.field.message.notify_contact_global_copy.field_subject.yml, config/sync/message.template.notify_contact_global_copy.yml, lib/modules/eic_contact/eic_contact.module
How to test:
https://citnet.tech.ec.europa.eu/CITnet/confluence/display/EICNET/SN+-+User+notifications
=> [EICNET-2233]feature: if send_copy is checked, send a self copy

lib/themes/eic_community/react/components/Block/NotifManagement/index.js, lib/themes/eic_community/sass/compositions/_my-notifications.scss, lib/themes/eic_community/sass/compositions/_subnavigation.scss
https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&view=detail&selectedIssue=EICNET-2060&quickFilter=26822
- Fix relaod when you press enter on focus of search
- Fix zoom on input on IOS
=> [EICNET-2060] fix search enter reload the page and fix zoom on input on IOS

lib/modules/eic_overviews/src/GlobalOverviewPages.php, lib/themes/eic_community/includes/preprocess/overview_pages/overview-page.inc
=> [EICNET-2382]chore: Add create entity CTAs on global overview pages

lib/themes/eic_community/react/components/Block/Overview/Search/Pagination.js, lib/themes/eic_community/sass/compositions/_pagination.scss
https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-2091
- Now on mobile, we can always see first page and last page
=> [EICNET-2091] add last page in pagination on mobile

e2e/cypress/integration/articles/articles.spec.js, lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGroupContent.php, lib/modules/eic_search/src/Service/SolrSearchManager.php
=> [EICNET-2211]feat: Hide news/stories from organisation as anonymous

config/sync/core.entity_form_display.message.notify_group_invitation_reminder.default.yml, config/sync/core.entity_view_display.message.notify_group_invitation_reminder.default.yml, config/sync/core.entity_view_display.message.notify_group_invitation_reminder.mail_body.yml, config/sync/core.entity_view_display.message.notify_group_invitation_reminder.mail_subject.yml, config/sync/core.entity_view_display.message.notify_group_wait_approval.default.yml, config/sync/field.field.message.notify_group_invitation_reminder.field_event_executing_user.yml, config/sync/field.field.message.notify_group_invitation_reminder.field_group_invitation.yml, config/sync/field.field.message.notify_group_invitation_reminder.field_group_ref.yml, config/sync/field.field.message.notify_group_invitation_reminder.field_invitee.yml, config/sync/field.field.message.notify_group_invitation_reminder.field_inviter.yml, config/sync/field.storage.message.field_group_invitation.yml, config/sync/field.storage.message.field_invitee.yml, config/sync/field.storage.message.field_inviter.yml, config/sync/language/en/message.template.notify_group_invitation_reminder.yml, config/sync/message.template.notify_group_invitation_reminder.yml, lib/modules/eic_groups/src/Hooks/CronOperations.php, web/sites/default/default.settings.local.php
How to test:
PS: you have a settings to configure if you want to run cron multiple times
=> [EICNET-2035]feat: Send notification reminder to all TU that didnt approve group invite

lib/themes/eic_community/react/components/Block/Overview/Search/Pagination.js, lib/themes/eic_community/react/components/Block/Overview/index.js
https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-1935
- in overview, when the filter changes the number of elements, we go back to the page 1
=> [EICNET-1935] return to page 1 if filter change the number on elements

lib/themes/eic_community/patterns/layout/base.html.twig, lib/themes/eic_community/sass/compositions/_4xx.scss, lib/themes/eic_community/sass/core/_viewport.scss, lib/themes/eic_community/sass/eic_community.screen.scss, lib/themes/eic_community/templates/layout/page--4xx.html.twig
https://citnet.tech.ec.europa.eu/CITnet/jira/secure/RapidBoard.jspa?rapidView=6628&projectKey=EICNET&view=detail&selectedIssue=EICNET-2385&quickFilter=26822
- set footer always at the bottom
- set viewport min height to 100vh
- go to the 4xx page like "/fgdgfdgasaswerew"
- see if it's working
=> [EICNET-2385] set viewport height to min 100vh

lib/themes/eic_community/react/components/Field/EntityTree/Result/Search.js
https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-688
- now, clear button make clear action
- key down "enter" add new tag or select first suggestion
- As admin
- Go to add story
- You can play with the topics or tags fields
=> [EICNET-688] Fix entity tree widget autocomplete 

config/sync/context.context.group_event_homepage.yml, lib/modules/eic_default_content/src/Generator/TaxonomyGenerator.php, lib/modules/eic_groups/src/Plugin/Block/EICGroupOverviewMessageBlock.php
=> [EICNET-2360]chore: Display the overview message block on global events

lib/modules/eic_groups/src/Plugin/Block/CommentsFromDiscussionBlock.php
=> [EICNET-2105]chore: Hide contributors on comments for news

lib/modules/eic_groups/eic_groups.module, lib/modules/eic_groups/src/EICGroupsHelper.php, lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php
=> [EICNET-2386]chore: Add an 'edit members' link to group management dropdown

config/sync/editor.editor.filtered_html.yml, config/sync/editor.editor.full_html.yml, config/sync/language/en/message.template.notify_contact_user_copy.yml, config/sync/message.template.notify_contact_global_copy.yml, config/sync/message.template.notify_contact_user_copy.yml
=> [EICNET-2233]fix: Add quote + horizontal line on copy contact

lib/modules/eic_search/eic_search.services.yml, lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobal.php, lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-header-block.inc, lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GroupResultItem.js
=> [EICNET-2397] Display moderation state as tag for groups

lib/modules/eic_user/eic_user.module, lib/modules/eic_user/src/Plugin/Block/AccountHeaderBlock.php, lib/modules/eic_user/templates/account-header-block.html.twig, lib/themes/eic_community/includes/preprocess/layout/page.inc, lib/themes/eic_community/patterns/compositions/global-header.html.twig
While having your caches enabled
=> [EICNET-2080]chore: Move the account header component into a plugin block

lib/modules/eic_content/src/Plugin/Field/FieldWidget/EntityTreeWidget.php
=> [EICNET-2404]fix: Keep selected values for entity tree widget on form error

lib/modules/eic_groups/src/Access/GroupContentNodeAccessControlHandler.php, lib/modules/eic_user/eic_user.routing.yml, lib/modules/eic_user/src/Controller/MySettingsController.php, lib/modules/eic_user/src/NotificationTypes.php, lib/modules/eic_user/src/Plugin/Block/NotificationsSettingsBlock.php, lib/modules/eic_user/src/Service/NotificationSettingsManager.php
=> [EICNET-1933]feat: Introduce notification settings for organisations

lib/modules/eic_contact/eic_contact.module
=> [EICNET-2233]feat: Unset default copy checkbox from contact + add custom

lib/themes/eic_community/react/components/Block/Overview/Search/Sidebar.js, lib/themes/eic_community/react/components/Block/Overview/index.js
=> [EICNET-2414]fix: If anonymous user do not show post content in sidebar

lib/modules/eic_user/src/Controller/MySettingsController.php, lib/themes/eic_community/react/components/Block/NotifManagement/index.js
https://citnet.tech.ec.europa.eu/CITnet/jira/browse/EICNET-2411?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel
- refetch url to show reel content
=> [EICNET-2411] notification unsubcribe reload when we unsubscribe

config/sync/filter.format.basic_text.yml
=> [EICNET-2410]chore: Allow p tags in basic_html text format

config/sync/group.content_type.organisation-group_node-document.yml, config/sync/group.content_type.organisation-group_node-gallery.yml, config/sync/migrate_plus.migration.upgrade_d7_content_membership.yml, config/sync/migrate_plus.migration.upgrade_d7_node_share_to_group_content.yml, lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_book.yml, lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_content_membership.yml
Temporary workaround for content membership migration, we'll need to decide what to do with those contents if we don't want to enable those content types for Organisations
=> EICNET-1441: Enable Gallery and Document CTs for Organisations.

lib/modules/eic_groups/src/Plugin/Block/EICGroupHeaderBlock.php, lib/modules/eic_statistics/modules/eic_group_statistics/src/GroupStatisticsStorage.php, lib/modules/eic_statistics/modules/eic_group_statistics/src/Hooks/EntityOperations.php
=> [EICNET-1113]fix: Get data from solr for event statistics

lib/themes/eic_community/includes/preprocess/comments/comment.inc, lib/themes/eic_community/mails/src/templates/user_tagged.mjml, lib/themes/eic_community/templates/content/comment--notification-teaser.html.twig
=> [EICNET-2423]fix: Send author avatar if exists in tagged comment

config/sync/core.entity_form_display.group.group.default.yml, config/sync/core.entity_form_display.message.notify_group_request_denied.default.yml, config/sync/core.entity_view_display.message.notify_group_request_denied.default.yml, config/sync/core.entity_view_display.message.notify_group_request_denied.mail_body.yml, config/sync/core.entity_view_display.message.notify_group_request_denied.mail_subject.yml, config/sync/field.field.message.notify_group_request_denied.field_group_ref.yml, config/sync/field.field.message.notify_group_request_denied.field_reason.yml, config/sync/field.storage.message.field_reason.yml, config/sync/language/en/message.template.notify_group_request_denied.yml, config/sync/message.template.notify_group_request_denied.yml, config/sync/workflows.workflow.groups.yml, lib/modules/eic_groups/eic_groups.module, lib/modules/eic_groups/src/GroupsModerationHelper.php, lib/modules/eic_messages/src/Service/GroupMessageCreator.php
=> [EICNET-2022]feat: send notification when group request has been denied

lib/modules/eic_user/eic_user.services.yml, lib/modules/eic_user/src/Breadcrumb/UserBreadcrumbBuilder.php, lib/modules/eic_user/src/Routing/UserRouteSubscriber.php
=> [EICNET-2421]chore: Change breadcrumbs for edit account & profile pages

config/sync/metatag.metatag_defaults.global.yml, config/sync/metatag.metatag_defaults.media__eic_document.yml, config/sync/metatag.metatag_defaults.node.yml
=> [EICNET-1892]fix: Improvide title & og_title tags for all contents

lib/modules/eic_user/modules/eic_user_login/src/EventSubscriber/RequestEventSubscriber.php
=> EICNET-2257: Allow users missing their profile to logout.

lib/modules/eic_flags/src/FlagType.php, lib/modules/eic_search/eic_search.services.yml, lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php, lib/modules/eic_search/src/Search/DocumentProcessor/DocumentProcessorInterface.php, lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGroup.php, lib/modules/eic_search/src/Search/Sources/GlobalEventSourceType.php, lib/modules/eic_search/src/Search/Sources/GroupEventSourceType.php, lib/modules/eic_search/src/Search/Sources/GroupSourceType.php, lib/modules/eic_search/src/Search/Sources/Profile/ActivityStreamSourceType.php, lib/modules/eic_search/src/Search/Sources/Profile/ContributionSourceType.php, lib/modules/eic_search/src/Search/Sources/Profile/DraftSourceType.php, lib/modules/eic_search/src/Search/Sources/Profile/FollowingSourceType.php, lib/modules/eic_search/src/Search/Sources/Profile/MyEventsSourceType.php, lib/modules/eic_search/src/Search/Sources/Profile/MyGroupsSourceType.php, lib/modules/eic_search/src/Search/Sources/SourceType.php, lib/modules/eic_search/src/Search/Sources/SourceTypeInterface.php, lib/modules/eic_search/src/Search/Sources/UserGallerySourceType.php, lib/modules/eic_search/src/Search/Sources/UserInvitesListSourceType.php, lib/modules/eic_search/src/Search/Sources/UserListSourceType.php, lib/modules/eic_search/src/Search/Sources/UserTaggingCommentsSourceType.php
=> [EICNET-2043]feat: Add most active for groups + fix overview block config

lib/modules/eic_search/eic_search.services.yml, lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorUser.php, lib/modules/eic_search/src/Search/Sources/UserGallerySourceType.php, lib/modules/eic_search/src/Search/Sources/UserListSourceType.php, lib/modules/eic_user/src/UserHelper.php
=> [EICNET-2045]feat: Calculate most active score for User entity in SOLR

lib/modules/eic_search/src/Search/Sources/OrganisationSourceType.php
=> [EICNET-2044]feat: Add most active sort for organisations

config/sync/core.entity_form_display.node.event.default.yml
- Update node event form display (new tabs + update widgets).
=> EICNET-2437: Front-end content form for the content type Event

config/sync/core.entity_form_display.node.story.default.yml
- Update node story form display (new tabs + update widgets).
=> EICNET-1794: Front-end content form for the content type Stories

config/sync/core.entity_form_display.node.discussion.default.yml
- Update node discussion form display (new tabs + update widgets).
=> EICNET-1798: Front-end content form for the content type Discusssions

config/sync/core.entity_form_display.node.wiki_page.default.yml
- Update node wiki page form display (new tabs + update widgets).
=> EICNET-1799: Front-end content form for the content type Wiki page

config/sync/core.entity_form_display.node.gallery.default.yml, lib/themes/eic_community/sass/components/_form.scss, lib/themes/eic_community/sass/eic_community.screen.scss, lib/themes/eic_community/sass/overrides/drupal_tabs.scss
- Update node gallery form display (new tabs + update widgets).
=> EICNET-1801: Front-end content form for the content type Gallery

config/sync/core.entity_form_display.node.video.default.yml
- Update node video form display (new tabs + update widgets).
=> EICNET-1802: Front-end content form for the content type Video

config/sync/core.entity_form_display.group.group.default.yml, lib/themes/eic_community/sass/components/_form.scss
- Add horizontal tabs to the group form display.
=> EICNET-1795: Front-end content form for the group type Group

config/sync/core.entity_form_display.group.event.default.yml, lib/themes/eic_community/sass/components/_form.scss
- Add horizontal tabs to the group event form display.
=> EICNET-1796 Front-end content form for the group type Event

config/sync/core.entity_form_display.group.organisation.default.yml, lib/themes/eic_community/sass/components/_form.scss
- Re-order organisation fields in form display + add more tabs.
Test
=> EICNET-1797: Front-end content form for the group type Organisation

lib/modules/eic_groups/src/Controller/DiscussionController.php
=> [EICNET-2045]fix: Resync dependant entities when adding comment

config/sync/core.entity_form_display.node.page.default.yml, lib/modules/eic_messages/modules/eic_message_subscriptions/src/Hooks/FormOperations.php
- Update node page form display (new tabs + update widgets) + hide "Send notification" field.
=> EICNET-1792: Front-end content form for the content type Page (Basic page)

lib/modules/eic_groups/templates/eic-group-last-activities-members.html.twig, lib/modules/eic_search/src/Plugin/Block/ActivityStreamBlock.php
=> [EICNET-2455]fix: set correct url for contributors

lib/modules/eic_search/src/Service/SolrSearchManager.php
=> [EICNET-2371]fix: Add discussion case to show draft for user

config/sync/core.extension.yml, config/sync/oe_webtools_analytics.settings.yml
=> EICNET-2302: Enable and configure oe_webtools_analytics module.

config/sync/migrate_plus.migration.upgrade_d7_group_pending_visitor_invitations.yml, lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_group_pending_visitor_invitations.yml
=> EICNET-2468: Fix wrong group type for events.

config/sync/migrate_plus.migration.upgrade_d7_taxonomy_term_c4m_vocab_tag.yml, lib/modules/eic_migrate/config/install/migrate_plus.migration.upgrade_d7_taxonomy_term_c4m_vocab_tag.yml, lib/modules/eic_migrate/src/Plugin/migrate/source/VocabTag.php
=> EICNET-2510: Add tags migration.

lib/modules/eic_messages/modules/eic_subscription_digest/src/Collector/GroupCollector.php, lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-header-block.inc, lib/themes/eic_community/templates/message/message--notify-digest.html.twig
=> [EICNET-2490] Digest e-mail changes

lib/modules/eic_overviews/src/Controller/GroupOverviewsController.php, lib/modules/eic_search/src/Service/SolrSearchManager.php
=> [EICNET-2522]fix: If member is group admin he should see content even if group is restricted

config/sync/core.entity_view_display.node.wiki_page.default.yml
=> [EICNET-2497]fix: Hide field_language in wiki

config/sync/core.entity_form_display.group.event.default.yml, config/sync/core.entity_view_display.node.event.default.yml, config/sync/core.entity_view_display.node.event.teaser.yml, config/sync/field.field.group.event.field_document_additional.yml, config/sync/field.field.group.event.field_document_agenda.yml, config/sync/field.field.group.event.field_document_presentations.yml, config/sync/field.storage.group.field_document_additional.yml, config/sync/field.storage.group.field_document_agenda.yml, config/sync/field.storage.group.field_document_presentations.yml, lib/themes/eic_community/includes/preprocess/events.inc, lib/themes/eic_community/includes/preprocess/groups/group.inc, lib/themes/eic_community/sass/components/_filelist.scss, lib/themes/eic_community/templates/group/group--event--full.html.twig, lib/themes/eic_community/templates/group/group-attachments.html.twig
=> [EICNET-2529]feat: Add attachment displays for global events

lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGlobal.php
=> [EICNET-2536]fix: Send first selected language to Solr

lib/modules/eic_recommend_content/src/Access/RecommendContentAccessCheck.php, lib/modules/eic_recommend_content/src/Services/RecommendContentManager.php, lib/modules/eic_search/eic_search.services.yml, lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorUser.php, lib/modules/eic_search/src/Search/Sources/UserRecommendSourceType.php, lib/modules/eic_search/src/Service/SolrSearchManager.php
=> [EICNET-2548]fix: Add recommend source type and strict private visibility

lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GlobalResultItem.js
=> [EICNET-2434]fix: Implement url for user on global result

lib/modules/eic_default_content/modules/eic_dummy_content/src/Generator/GroupGenerator.php, lib/modules/eic_default_content/modules/eic_dummy_content/src/Generator/GroupTypeEventGenerator.php, lib/modules/eic_default_content/modules/eic_dummy_content/src/Generator/OrganisationGenerator.php
- Fix group menu items generating groups, global events and organisations with fixtures.
=> EICNET-2546: Double group navigation items shown for organizations

config/sync/config_split.config_split.development.yml, lib/themes/eic_community/includes/preprocess/groups/group.inc
=> [EICNET-2550]chore: Icons for file attachments in events

config/sync/core.entity_view_display.message.notify_user_tagged_on_comment.mail_body.yml, config/sync/core.entity_view_display.message.notify_user_tagged_on_comment.mail_subject.yml, lib/themes/eic_community/templates/content/comment--notification-teaser.html.twig
=> [EICNET-1664] fix: user image in comment email

lib/modules/eic_search/eic_search.module, lib/modules/eic_search/eic_search.services.yml, lib/modules/eic_search/src/Controller/SolrSearchController.php, lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php, lib/modules/eic_search/src/Search/Sources/SourceType.php, lib/modules/eic_search/src/Search/Sources/SourceTypeInterface.php, lib/modules/eic_search/src/Search/Sources/UserProfile/MyGroupsSourceType.php, lib/modules/eic_search/src/Service/SolrSearchManager.php, lib/modules/eic_search/templates/search-overview-block.html.twig, lib/themes/eic_community/includes/preprocess/users/user.inc, lib/themes/eic_community/react/components/Block/Overview/entrypoint.js, lib/themes/eic_community/react/components/Block/Overview/index.js
=> [EICNET-2495]fix: Replace my groups by react component

lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorGroupContent.php
How to test:
The field  used in search api was: search_api_reverse_entity_references_group_content__entity_id:gid
But the query behind loaded all gid from group_content without checking group_type so we had 3 different results for the same entity_id
=> [EICNET-2535]fix: Do not use the search_api_reverse_reference but load correctly the gid from group content

lib/themes/eic_community/includes/preprocess/layout/page.inc
- Service name has changed in the latest version of module, this commit, just fixes that
=> EICNET-XXXX: Fix new service name for reading time.

lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/GlobalResultItem.js
=> [EICNET-2434]fix: Set correctly url dynamically depending proxy

config/sync/views.view.my_invitations.yml
=> EICNET-2526: Update my invitations view.

lib/themes/eic_community/react/components/Block/Overview/Search/ResultItem/ActivityStreamResultItem.js
- Fix react issue when showing migrated latest activity stream messages.
=> EICNET-1438: Message migration (Fix activity stream overview)

docker/php/Dockerfile, e2e/cypress.json, e2e/cypress/integration/global/permissions-check.spec.js, e2e/cypress/integration/group/group.spec.js, e2e/cypress/support/commands.js
=> [EICNET-2611]fix: Fix cypress issues with new comment from Quill

lib/themes/eic_community/includes/preprocess/content/node--news--story.inc, lib/themes/eic_community/templates/content/node--story--full.html.twig
- Implement video player in Story video.
=> EICNET-390: Implement video player in Story video.

lib/modules/eic_flags/src/Service/DeleteRequestHandler.php
- Fix error when accept delete request `"InvalidArgumentException: Field comment_body is unknown"`;
- Remove related group content when node is deleted via request.
=> EICNET-1815: Critical actions admin view (Fix request deletion)

config/sync/group.role.event-admin.yml, config/sync/group.role.event-owner.yml, config/sync/group.role.group-admin.yml, config/sync/group.role.group-owner.yml
=> EICNET-2602: Add missing permission for GO/GA to administer membership requests.

config/sync/workflows.workflow.default.yml, lib/modules/eic_content/src/Constants/DefaultContentModerationStates.php, lib/modules/eic_flags/src/Service/ArchiveRequestHandler.php
=> Feature/eicnet 2595  archived content visibility

config/sync/eic_admin.action_forms.ginvite.invitation.accept.yml
- No code/functional change, it's just a copy text fix
=> EICNET-2526: Update copy for invite accept action form.

config/sync/language/en/message.template.sub_group_content_updated.yml, config/sync/language/en/message.template.sub_new_group_content_published.yml, config/sync/message.template.sub_group_content_updated.yml, config/sync/message.template.sub_new_group_content_published.yml
=> [EICNET-2439]chore: Add Content title and link on some e-mails

config/sync/core.entity_view_display.message.sub_new_group_content_published.default.yml, config/sync/language/en/message.template.sub_group_content_shared.yml, config/sync/message.template.sub_group_content_shared.yml, config/sync/migrate_plus.migration.upgrade_d7_node_photo_to_media.yml, lib/modules/eic_groups/modules/eic_share_content/eic_share_content.services.yml, lib/modules/eic_groups/modules/eic_share_content/src/Service/ShareManager.php, lib/modules/eic_messages/modules/eic_message_subscriptions/src/MessageSubscriptionTypes.php
=> [EICNET-2480]fix: Send content shared notifications to following users

lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorUser.php
=> [EICNET-2046]feat: Process total groups/events calculation after

e2e/cypress/integration/group/group.spec.js, e2e/cypress/integration/organisation/organisation.spec.js, e2e/cypress/support/commands.js, e2e/cypress/support/index.js
=> [EICNET-2614]feat: Add cypress coverage organisation

lib/modules/eic_migrate/src/Plugin/migrate/source/UrlAliasToPathRedirect.php
=> EICNET-2627: Prevent duplicate redirect migration.

config/sync/eic_admin.action_forms.group_deletion_request.yml
=> EICNET-2299: Group deletion action form typo.

config/sync/group.role.group-anonymous.yml, lib/modules/eic_moderation/config/install/field.storage.message.field_message.yml, lib/themes/eic_community/react/components/Block/CommentsDiscussion/index.js
This reverts commit 1ec2144b5b8297edace6446538d976a69c1d4651, reversing
changes made to 2cba4b2f6850b0e88932e3f80f52163809f7505a.
=> Revert "Merge branch 'master' into acceptance"

lib/themes/eic_community/sass/core/_viewport.scss
=> EICNET-2592: enable modal scrolling

composer.lock
- I went through all modules release notes, I didn't see any breaking change that could occur
- Search API has potential breaking changes, but this does not apply to us
=> EICNET-XXXX: Packages update.

config/sync/eic_admin.action_forms.group_archival_request.yml, config/sync/eic_admin.action_forms.group_membership_edit.yml, config/sync/eic_admin.action_forms.group_ownership_transfer_request_cancel.yml, lib/modules/eic_flags/src/Form/RequestCancelForm.php, lib/themes/eic_community/sass/components/_checkbox.scss
=> EICNET-2311: Fix typo.

web/sites/default/default.settings.k8s.php
This reverts commit 2d9e144ee6a23a8897f05bb8ffcb223cf87791e8.
=> Revert "EICNET-2678: disabling redis for cli commands with drush."

config/sync/context.context.global.yml, config/sync/system.menu.footer---european-commision.yml, config/sync/system.menu.footer---european-innovation-cou.yml, lib/themes/eic_community/includes/preprocess/layout/page.inc, lib/themes/eic_community/sass/compositions/_site-footer.scss
=> [EICNET-2685]feat: Add EU council menu + change some styling

config/sync/field.field.profile.member.field_vocab_geo.yml
=> [EICNET-2687]fix: Change label target region & countries

lib/themes/eic_community/includes/preprocess/blocks/block--cta-tiles.inc, lib/themes/eic_community/patterns/compositions/bulletin-block.html.twig
=> EICNET-2679: Respect field format.

docker/php/Dockerfile, docker/php/start.sh
EICINFRA-465: added debugger - created start script to include ability to start tideways.
=> EICINFRA-465: added debugger - created start script to include ability to start tideways.

docker/php/Dockerfile, docker/php/start.sh
=> EICINFRA-465: added debugger - different approach to run php-fpm and tideways.

config/sync/context.context.contribution.yml, config/sync/context.context.events_overview.yml, config/sync/context.context.following.yml, config/sync/context.context.group_discussions_overviews.yml, config/sync/context.context.group_events_overviews.yml, config/sync/context.context.group_files_overviews.yml, config/sync/context.context.group_members_overviews.yml, config/sync/context.context.group_news_overviews.yml, config/sync/context.context.group_search.yml, config/sync/context.context.groups_overview.yml, config/sync/context.context.interests.yml, config/sync/context.context.members_overview.yml, config/sync/context.context.search.yml, config/sync/core.entity_form_display.user.user.default.yml, config/sync/search_api_solr.solr_field_type.text_und_6_0_0.yml, config/sync/search_api_solr.solr_field_type.text_und_7_0_0.yml, config/sync/views.view.global_index_group_content.yml
=> EICNET-2680: Check why config always needs to be synced

lib/modules/eic_search/src/Service/SolrSearchManager.php
=> EICNET-2701: Filter out blocked users in search overviews.

lib/modules/eic_search/src/Search/Sources/Profile/DraftSourceType.php, lib/modules/eic_search/src/Search/Sources/SourceTypeInterface.php, lib/modules/eic_search/src/Service/SolrSearchManager.php
=> EICNET-2721: Allow other statuses for my drafts.

config/sync/workflows.workflow.eic_moderated_workflow.yml
=> EICNET-2754: Moderated workflow: allow Publish transistion from unpublished.

lib/modules/eic_moderation/src/Service/ContentModerationManager.php
- Prevent users from saving a newly created News/Stories as unpublished in the context of groups until the node has a published version.
=> EICNET-2760: [Event] News have confusing instructions

composer.patches.json
=> EICNET-2705: Fix issue with group permissions.

lib/modules/eic_search/src/Plugin/search_api/processor/GroupAccessContent.php, lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorMessage.php, lib/themes/eic_community/includes/preprocess/groups/group.inc, lib/themes/eic_community/includes/preprocess/users/user.inc
=> [EICNET-2781]feat: Do not allow group content (from event) to be shown for non-members (only SOLR)

config/sync/flag.flag.bookmark_content.yml
=> [EICNET-2787]feat: Disable bookmark content

lib/modules/eic_user/src/Hooks/FormAlter.php
=> EICNET-2733: Disable user type for SMED users.

config/sync/entity_usage.settings.yml
=> EICNET-2794: Follow taxonomy terms for entitu_usage.

lib/themes/eic_community/includes/preprocess/blocks/block--latest-news-stories.inc
=> EICNET-2799: Latest News/Stories, change thumbnail source.

lib/modules/eic_groups/eic_groups.install.inc
to clean up the list of role ids.
=> EICNET-2817: need to reinitialize the array

lib/modules/eic_user/modules/eic_user_login/src/Hooks/FormAlter.php
=> EICNET-2840: Allow power users to edit first and last name.

lib/modules/eic_user/modules/eic_user_login/src/Service/SmedUserManager.php
=> Issue EICNET-2826: updated response messages when user is blocked, based on the smed status

lib/modules/eic_contact/eic_contact.module
=> EICNET-2867: Do not send contact submissions to SA/SCM.

lib/themes/eic_community/includes/preprocess/content/message.inc
=> EICNET-2875: mails from contact form are stuck in the queue 

lib/modules/eic_topics/eic_topics.services.yml, lib/modules/eic_topics/src/TermBreadcrumbBuilder.php
=> EICNET-2880: Fix Topics breadrcumb.

lib/modules/eic_search/src/Service/SolrSearchManager.php, lib/themes/eic_community/includes/preprocess/blocks/block--eic-group-header-block.inc
=> [EICNET-2879]fix: place correctly the recommend action as second option without removing like

lib/themes/eic_community/sass/components/_drupal-webforms.scss
=> [EICNET-2712]fix: remove unused required svg call

composer.lock, composer.patches.json
- Apply patch to fix issue with required address fields selecting the first country in the list by default.
=> EICNET-2885: On user profile edition Country should be empty not afghanistan by default

lib/themes/eic_community/includes/preprocess/events.inc
=> EICNET-2488: Fix epty items for Event GT.

config/sync/entity_usage.settings.yml
- To update the existing contents run `drush entity-usage:recreate`
=> EICNET-2846: Enable the media_embed plugin for entity_usage.

lib/modules/eic_user/modules/eic_user_login/src/Hooks/FormAlter.php
=> EICNET-2890: Fix missing DependencySerializationTrait.

lib/modules/eic_search/src/Search/Sources/GlobalSourceType.php, lib/modules/eic_search/src/Search/Sources/SourceType.php, lib/modules/eic_search/src/Search/Sources/SourceTypeInterface.php, lib/modules/eic_search/src/Service/SolrSearchManager.php
=> [EICNET-2888]fix: Set OR operator for certain facet fields

config/sync/user.role.content_administrator.yml, config/sync/user.role.site_admin.yml, config/sync/user.role.trusted_user.yml
=> [EICNET-2830]fix: Allow trusted user to create tag on fly

lib/modules/eic_search/src/Plugin/Block/SearchOverviewBlock.php, lib/themes/eic_community/react/components/Block/Overview/Search/Library/AddLibraryContent.js, lib/themes/eic_community/react/components/Block/Overview/Search/Sidebar.js
- Add button to create discussion in group discussions overview page.
=> EICNET-2761: Add button to create discussion at the dicsussion level

lib/modules/eic_content/src/Services/EntityTreeManager.php, lib/themes/eic_community/react/components/Block/CommentsDiscussion/Partials/Answers.js, lib/themes/eic_community/react/components/Block/CommentsDiscussion/index.js
=> [EICNET-2620]feat: make chip message for comment translatable

config/sync/views.view.entity_reference_user.yml
- This is a workaround since we removed the permission for TUs to view other users' email address
=> EICNET-2753: Remove email from entity user reference view.

lib/themes/eic_community/sass/compositions/_mainmenu.scss
=> [EICNET-2859]fix: show nested menu on mobile

lib/themes/eic_community/sass/compositions/_editorial-article.scss
=> [EICNET-2748]fix: remove sticky position

lib/themes/eic_community/react/components/Block/Overview/Search/Sidebar.js
=> [EICNET-1723]fix: fix link cursor

lib/modules/eic_flags/eic_flags.services.yml, lib/modules/eic_flags/src/Service/AbstractRequestHandler.php, lib/modules/eic_flags/src/Service/BlockRequestHandler.php
=> EICNET-XXXX: chore: Fix missing dependency on install.

config/sync/field.field.group.group.field_vocab_topics.yml
=> EICNET-2728: Make topics mandatory for Group GT.

config/sync/search_api.index.global.yml
- Change indexed field_body type to fulltext.
=> EICNET-2919: Solr crash when indexing a Story

lib/modules/eic_blocks/src/Plugin/Block/Eulogin2FABannerBlock.php, lib/themes/eic_community/includes/preprocess/blocks/block--page-banner.inc
=> release/0.49.1 - 2fa popup

composer.lock
=> EICNET-2962: Coder repo is under a new address.

lib/modules/eic_groups/eic_groups.module
=> [EICNET-2972]fix: Add hook entity delete for nodes and not only group content

lib/modules/eic_search/src/Search/DocumentProcessor/ProcessorDiscussion.php
=> EICNET-2923: Fix processing of discussions.

lib/themes/eic_community/mails/mail-dist/digest.html, lib/themes/eic_community/mails/mail-dist/header_footer.html, lib/themes/eic_community/mails/mail-dist/layout.html, lib/themes/eic_community/mails/src/templates/header_footer.mjml
=> [EICNET-2820]fix: email header logo

lib/modules/oec_group_flex/src/Plugin/GroupVisibility/CommunityMembersRestrictedVisibility.php, lib/modules/oec_group_flex/src/Plugin/GroupVisibility/PrivateVisibility.php, lib/modules/oec_group_flex/src/Plugin/GroupVisibility/SensitiveVisibility.php
It seems this ticket was already done.
Here are some some improvements, mainly titles and descriptions.
=> EICNET-2969: Modify the group visibility labels and descriptions.
